// Club directory data — 90 USA lawn bowling clubs seeded from research
// Each club represents a real lawn bowling club in the United States

export type USRegion = "west" | "east" | "south" | "midwest";
export type ClubStatus = "active" | "seasonal" | "inactive" | "unverified" | "claimed";
export type SurfaceType = "natural_grass" | "synthetic" | "hybrid" | "unknown";
export type BowlsUSADivision =
  | "pacific_intermountain"
  | "southwest"
  | "south_central"
  | "southeast"
  | "central"
  | "eastern"
  | "northeast"
  | "northwest"
  | "none";

export interface ClubData {
  id: string;
  name: string;
  city: string;
  state: string;
  stateCode: string;
  region: USRegion;
  address?: string;
  lat?: number;
  lng?: number;
  website?: string;
  phone?: string;
  email?: string;
  memberCount?: number;
  greens?: number;
  rinks?: number;
  surfaceType: SurfaceType;
  division: BowlsUSADivision;
  activities: string[];
  facilities: string[];
  founded?: number;
  description?: string;
  status: ClubStatus;
  hasOnlinePresence: boolean;
  socialMedia?: {
    facebook?: string;
    instagram?: string;
    youtube?: string;
  };
  tags: string[];
}

export const US_STATES: Record<string, { name: string; code: string; region: USRegion }> = {
  AL: { name: "Alabama", code: "AL", region: "south" },
  AK: { name: "Alaska", code: "AK", region: "west" },
  AZ: { name: "Arizona", code: "AZ", region: "west" },
  AR: { name: "Arkansas", code: "AR", region: "south" },
  CA: { name: "California", code: "CA", region: "west" },
  CO: { name: "Colorado", code: "CO", region: "west" },
  CT: { name: "Connecticut", code: "CT", region: "east" },
  DE: { name: "Delaware", code: "DE", region: "east" },
  FL: { name: "Florida", code: "FL", region: "south" },
  GA: { name: "Georgia", code: "GA", region: "south" },
  HI: { name: "Hawaii", code: "HI", region: "west" },
  ID: { name: "Idaho", code: "ID", region: "west" },
  IL: { name: "Illinois", code: "IL", region: "midwest" },
  IN: { name: "Indiana", code: "IN", region: "midwest" },
  IA: { name: "Iowa", code: "IA", region: "midwest" },
  KS: { name: "Kansas", code: "KS", region: "midwest" },
  KY: { name: "Kentucky", code: "KY", region: "south" },
  LA: { name: "Louisiana", code: "LA", region: "south" },
  ME: { name: "Maine", code: "ME", region: "east" },
  MD: { name: "Maryland", code: "MD", region: "east" },
  MA: { name: "Massachusetts", code: "MA", region: "east" },
  MI: { name: "Michigan", code: "MI", region: "midwest" },
  MN: { name: "Minnesota", code: "MN", region: "midwest" },
  MS: { name: "Mississippi", code: "MS", region: "south" },
  MO: { name: "Missouri", code: "MO", region: "midwest" },
  MT: { name: "Montana", code: "MT", region: "west" },
  NE: { name: "Nebraska", code: "NE", region: "midwest" },
  NV: { name: "Nevada", code: "NV", region: "west" },
  NH: { name: "New Hampshire", code: "NH", region: "east" },
  NJ: { name: "New Jersey", code: "NJ", region: "east" },
  NM: { name: "New Mexico", code: "NM", region: "west" },
  NY: { name: "New York", code: "NY", region: "east" },
  NC: { name: "North Carolina", code: "NC", region: "south" },
  ND: { name: "North Dakota", code: "ND", region: "midwest" },
  OH: { name: "Ohio", code: "OH", region: "midwest" },
  OK: { name: "Oklahoma", code: "OK", region: "south" },
  OR: { name: "Oregon", code: "OR", region: "west" },
  PA: { name: "Pennsylvania", code: "PA", region: "east" },
  RI: { name: "Rhode Island", code: "RI", region: "east" },
  SC: { name: "South Carolina", code: "SC", region: "south" },
  SD: { name: "South Dakota", code: "SD", region: "midwest" },
  TN: { name: "Tennessee", code: "TN", region: "south" },
  TX: { name: "Texas", code: "TX", region: "south" },
  UT: { name: "Utah", code: "UT", region: "west" },
  VT: { name: "Vermont", code: "VT", region: "east" },
  VA: { name: "Virginia", code: "VA", region: "east" },
  WA: { name: "Washington", code: "WA", region: "west" },
  WV: { name: "West Virginia", code: "WV", region: "east" },
  WI: { name: "Wisconsin", code: "WI", region: "midwest" },
  WY: { name: "Wyoming", code: "WY", region: "west" },
  DC: { name: "Washington DC", code: "DC", region: "east" },
};

export const REGION_LABELS: Record<USRegion, { label: string; emoji: string }> = {
  west: { label: "West", emoji: "🌅" },
  east: { label: "East", emoji: "🗽" },
  south: { label: "South", emoji: "☀️" },
  midwest: { label: "Midwest", emoji: "🌾" },
};

export const SURFACE_LABELS: Record<SurfaceType, string> = {
  natural_grass: "Natural Grass",
  synthetic: "Synthetic",
  hybrid: "Hybrid",
  unknown: "Unknown",
};

export const ACTIVITY_OPTIONS = [
  "Social Bowls",
  "League/Pennant",
  "Tournaments",
  "Barefoot Bowls",
  "Corporate Events",
  "Coaching/Lessons",
  "Junior Programs",
  "Open Days",
] as const;

export const DIVISION_LABELS: Record<BowlsUSADivision, string> = {
  pacific_intermountain: "Pacific Inter-Mountain",
  southwest: "Southwest",
  south_central: "South Central",
  southeast: "Southeast",
  central: "Central",
  eastern: "Eastern",
  northeast: "Northeast",
  northwest: "Northwest",
  none: "Unaffiliated",
};

// 90 USA lawn bowling clubs seeded from research data
export const CLUBS: ClubData[] = [
  // ===================== CALIFORNIA — PIMD =====================
  { id: "ca-san-francisco", name: "San Francisco Lawn Bowling Club", city: "San Francisco", state: "California", stateCode: "CA", region: "west", address: "Bowling Green Dr., Golden Gate Park, San Francisco, CA", website: "https://www.sflbc.org", memberCount: 130, greens: 3, surfaceType: "natural_grass", division: "pacific_intermountain", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Open Days", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking", "Restrooms"], founded: 1901, description: "Oldest public lawn bowling club in America. 1915 Edwardian clubhouse is SF City Landmark #181. Free lessons Wednesdays.", status: "active", hasOnlinePresence: true, socialMedia: { facebook: "SFLawnBowlingClub" }, tags: ["historic", "public-park", "beginner-friendly", "free-lessons"] },
  { id: "ca-berkeley", name: "Berkeley Lawn Bowling Club", city: "Berkeley", state: "California", stateCode: "CA", region: "west", address: "2270 Acton St., Berkeley, CA 94702", website: "https://berkeleylawnbowling.org/", phone: "510-841-2174", memberCount: 95, greens: 2, surfaceType: "natural_grass", division: "pacific_intermountain", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons", "Open Days"], facilities: ["Clubhouse"], founded: 1928, description: "Founded 1928, non-profit since 1963. Free Sunday lessons.", status: "active", hasOnlinePresence: true, tags: ["public-park", "beginner-friendly", "free-lessons"] },
  { id: "ca-palo-alto", name: "Palo Alto Lawn Bowls Club", city: "Palo Alto", state: "California", stateCode: "CA", region: "west", address: "474 Embarcadero Rd., Palo Alto, CA", website: "https://www.palbc.org/", greens: 1, rinks: 8, surfaceType: "natural_grass", division: "pacific_intermountain", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking", "Restrooms"], founded: 1933, description: "Community club since 1933 with full kitchen and locker rooms.", status: "active", hasOnlinePresence: true, tags: ["beginner-friendly"] },
  { id: "ca-santa-cruz", name: "Santa Cruz Lawn Bowls Club", city: "Santa Cruz", state: "California", stateCode: "CA", region: "west", address: "137 Dakota Ave., San Lorenzo Park, Santa Cruz, CA 95060", website: "https://www.sclawnbowls.org/", phone: "831-469-4807", greens: 1, surfaceType: "synthetic", division: "pacific_intermountain", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse"], description: "World-class artificial green near downtown and the ocean.", status: "active", hasOnlinePresence: true, tags: ["public-park", "downtown"] },
  { id: "ca-oakland", name: "Oakland Lawn Bowling Club", city: "Oakland", state: "California", stateCode: "CA", region: "west", address: "660 Bellevue Ave., Lakeside Park, Oakland, CA 94610", website: "https://www.oaklandlawnbowlingclub.com/", phone: "510-625-9937", greens: 2, surfaceType: "natural_grass", division: "pacific_intermountain", activities: ["Social Bowls", "League/Pennant", "Corporate Events"], facilities: ["Clubhouse"], founded: 1903, description: "Founded 1903 by Scottish bowlers. Beautiful Lake Merritt setting.", status: "active", hasOnlinePresence: true, tags: ["historic", "lake-view", "corporate-events"] },
  { id: "ca-rossmoor", name: "Rossmoor Lawn Bowling Club", city: "Walnut Creek", state: "California", stateCode: "CA", region: "west", address: "3400 Lower Golden Rain Rd., Walnut Creek, CA 94595", website: "https://www.rlbc.net/", phone: "925-289-8011", greens: 3, rinks: 24, surfaceType: "natural_grass", division: "pacific_intermountain", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1967, description: "Large 55+ community club with three greens and certification program.", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community", "large-club"] },
  { id: "ca-san-jose", name: "San Jose Lawn Bowls Club", city: "San Jose", state: "California", stateCode: "CA", region: "west", address: "Willow Street Frank Bramhall Park, San Jose, CA", website: "https://sjlbc-home.org/", greens: 1, surfaceType: "synthetic", division: "pacific_intermountain", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Corporate Events"], facilities: ["Parking"], description: "Championship-quality synthetic green from 2017 city renovation.", status: "active", hasOnlinePresence: true, tags: ["public-park", "beginner-friendly"] },
  { id: "ca-santa-clara", name: "Santa Clara Lawn Bowls Club", city: "Santa Clara", state: "California", stateCode: "CA", region: "west", website: "https://www.santaclaralawnbowls.org/", phone: "408-204-0154", greens: 1, surfaceType: "natural_grass", division: "pacific_intermountain", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Parking"], status: "active", hasOnlinePresence: true, tags: ["public-park", "beginner-friendly"] },
  { id: "ca-sunnyvale", name: "Sunnyvale Lawn Bowls Club", city: "Sunnyvale", state: "California", stateCode: "CA", region: "west", address: "Martin Murphy Jr. Historical Park, Sunnyvale, CA", website: "https://www.svlbc.org/", phone: "408-730-7356", greens: 1, surfaceType: "natural_grass", division: "pacific_intermountain", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Parking"], status: "active", hasOnlinePresence: true, tags: ["public-park", "historic", "beginner-friendly"] },
  { id: "ca-del-mesa-carmel", name: "Del Mesa Carmel Lawn Bowling Club", city: "Carmel", state: "California", stateCode: "CA", region: "west", website: "http://dmclbc.org/", memberCount: 55, greens: 1, surfaceType: "natural_grass", division: "pacific_intermountain", activities: ["Social Bowls"], facilities: ["Clubhouse"], description: "Only regulation green in Monterey County. Open to non-residents.", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community"] },
  { id: "ca-fresno", name: "Fresno Lawn Bowls Club", city: "Fresno", state: "California", stateCode: "CA", region: "west", address: "Holmes Park, Fresno, CA", website: "http://www.fresnolawnbowls.org/", phone: "559-224-2240", greens: 1, surfaceType: "natural_grass", division: "pacific_intermountain", activities: ["Social Bowls", "Tournaments"], facilities: ["Parking"], description: "Only lawn bowling club in California's Central Valley.", status: "active", hasOnlinePresence: true, tags: ["public-park"] },
  { id: "ca-oakmont-santa-rosa", name: "Oakmont Lawn Bowling Club", city: "Santa Rosa", state: "California", stateCode: "CA", region: "west", address: "310 White Oak Dr., Santa Rosa, CA 95409", website: "https://www.oakmontlawnbowling.com/", greens: 1, surfaceType: "synthetic", division: "pacific_intermountain", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse"], description: "Hosted 1998 North American Challenge Tournament.", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community"] },
  // ===================== CALIFORNIA — SWD =====================
  { id: "ca-laguna-beach", name: "Laguna Beach Lawn Bowling Club", city: "Laguna Beach", state: "California", stateCode: "CA", region: "west", address: "455 Cliff Dr., Heisler Park, Laguna Beach, CA", website: "https://lagunabeachlawnbowlingclub.com/", memberCount: 376, greens: 2, rinks: 16, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1931, description: "LARGEST lawn bowling club in the USA (376 members). Ocean-view greens. 'Lawn Bowling Capital of the United States' since 1957.", status: "active", hasOnlinePresence: true, socialMedia: { facebook: "LagunaBeachLawnBowling", instagram: "lagunabeachlbc" }, tags: ["ocean-view", "year-round", "beginner-friendly", "largest-club"] },
  { id: "ca-long-beach", name: "Long Beach Lawn Bowling Club", city: "Long Beach", state: "California", stateCode: "CA", region: "west", address: "1109 Federation Dr., Long Beach, CA 90804", website: "https://longbeachlbc.com/", memberCount: 100, greens: 3, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1928, description: "Three greens in Recreation Park. Home to past National Champions.", status: "active", hasOnlinePresence: true, tags: ["year-round", "competitive"] },
  { id: "ca-santa-monica", name: "Santa Monica Lawn Bowling Club", city: "Santa Monica", state: "California", stateCode: "CA", region: "west", address: "Douglas Park, Wilshire Blvd., Santa Monica, CA", memberCount: 75, greens: 1, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse", "Parking"], founded: 1945, description: "Laser-leveled hybrid Bermuda green on 18 inches of sand.", status: "active", hasOnlinePresence: true, tags: ["public-park", "year-round"] },
  { id: "ca-beverly-hills", name: "Beverly Hills Lawn Bowling Club", city: "Beverly Hills", state: "California", stateCode: "CA", region: "west", address: "471 S. Roxbury Dr., Beverly Hills, CA 90210", website: "https://bhlbc.com/", greens: 2, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Coaching/Lessons"], facilities: ["Clubhouse", "Restrooms", "Parking"], founded: 1926, description: "Historic club in Roxbury Park. Walt Disney was a member.", status: "active", hasOnlinePresence: true, socialMedia: { facebook: "BeverlyHillsLBC" }, tags: ["historic", "celebrity-history", "public-park"] },
  { id: "ca-holmby-park", name: "Holmby Park Lawn Bowling Club", city: "Los Angeles", state: "California", stateCode: "CA", region: "west", address: "646 Comstock Ave., Los Angeles, CA 90024", website: "https://www.losangeleslawnbowling.com/", memberCount: 130, greens: 2, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1927, description: "130 members from 17 countries. $95/year dues unchanged since 2008.", status: "active", hasOnlinePresence: true, tags: ["international", "beginner-friendly", "year-round"] },
  { id: "ca-pasadena", name: "Pasadena Lawn Bowling Club", city: "Pasadena", state: "California", stateCode: "CA", region: "west", address: "275 S. Raymond Ave., Central Park, Pasadena, CA", website: "https://www.plbcc.org/", greens: 2, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Open Days"], facilities: ["Clubhouse", "Parking"], founded: 1921, description: "Oldest continuously operating lawn bowling club in the USA. Hosts Rose Lawn Bowl on New Year's Eve.", status: "active", hasOnlinePresence: true, tags: ["historic", "oldest-club", "year-round", "beginner-friendly"] },
  { id: "ca-san-diego", name: "San Diego Lawn Bowling Club", city: "San Diego", state: "California", stateCode: "CA", region: "west", address: "2125 Park Blvd., Balboa Park, San Diego, CA 92134", website: "https://sandiegolawnbowling.org/", memberCount: 100, greens: 2, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Tournaments", "Junior Programs", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1932, description: "Iconic Balboa Park location. Youth membership from age 12.", status: "active", hasOnlinePresence: true, socialMedia: { facebook: "SanDiegoLawnBowling", instagram: "sandiegolawnbowling" }, tags: ["year-round", "competitive", "junior-program", "iconic"] },
  { id: "ca-coronado", name: "Coronado Lawn Bowling Club", city: "Coronado", state: "California", stateCode: "CA", region: "west", address: "1019 7th St., Coronado, CA", website: "https://coronadolawnbowling.com/", greens: 1, rinks: 6, surfaceType: "synthetic", division: "southwest", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1935, description: "World-class artificial green dedicated March 2010.", status: "active", hasOnlinePresence: true, tags: ["year-round", "beginner-friendly"] },
  { id: "ca-santa-anita", name: "Santa Anita Bowling Green Club", city: "Arcadia", state: "California", stateCode: "CA", region: "west", address: "405 S. Santa Anita Ave., Arcadia, CA", website: "https://santaanitalawnbowling.com/", greens: 4, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse", "Parking"], description: "One of only two clubs in the US with four greens. Night bowling on lighted greens.", status: "active", hasOnlinePresence: true, tags: ["large-club", "night-bowling", "year-round"] },
  { id: "ca-mackenzie-park", name: "MacKenzie Park Lawn Bowls Club", city: "Santa Barbara", state: "California", stateCode: "CA", region: "west", address: "MacKenzie Park, Los Positas Rd., Santa Barbara, CA", website: "https://mplbc.com/", greens: 2, rinks: 16, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], description: "Modern clubhouse with full kitchen. One of two clubs in Santa Barbara.", status: "active", hasOnlinePresence: true, tags: ["year-round", "beginner-friendly"] },
  { id: "ca-santa-barbara", name: "Santa Barbara Lawn Bowls Club", city: "Santa Barbara", state: "California", stateCode: "CA", region: "west", address: "1216 De La Vina St., Santa Barbara, CA 93101", website: "https://www.santabarbaralbc.org/", greens: 1, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Corporate Events"], facilities: ["Parking"], founded: 1937, description: "Non-profit co-sponsored by City Parks & Rec.", status: "active", hasOnlinePresence: true, tags: ["public-park", "corporate-events", "beginner-friendly"] },
  { id: "ca-newport-harbor", name: "Newport Harbor Lawn Bowling Club", city: "Corona del Mar", state: "California", stateCode: "CA", region: "west", address: "1550 Crown Dr. North, Corona del Mar, CA 92625", website: "https://www.newportharborlbc.com/", greens: 2, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Open Days"], facilities: ["Clubhouse", "Parking"], description: "One of the largest and most beautiful clubs in the US.", status: "active", hasOnlinePresence: true, tags: ["year-round", "beginner-friendly"] },
  { id: "ca-laguna-woods", name: "Laguna Woods Lawn Bowling Club", city: "Laguna Woods", state: "California", stateCode: "CA", region: "west", address: "24112 Moulton Parkway, Laguna Woods, CA 92637", website: "https://www.lwlbc.org/", greens: 2, surfaceType: "synthetic", division: "southwest", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], description: "Active 7 days a week. Hosted North American Challenge (2019) and U.S. Open (2023).", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community", "year-round"] },
  { id: "ca-redlands", name: "Redlands Lawn Bowling Club", city: "Redlands", state: "California", stateCode: "CA", region: "west", address: "Sylvan Park, 411 N. University St., Redlands, CA", website: "https://www.redlandslawnbowlingclub.com/", memberCount: 45, greens: 2, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse", "Parking"], founded: 1921, description: "Second oldest in SoCal. 1926 Mission Revival clubhouse is a historic resource.", status: "active", hasOnlinePresence: true, tags: ["historic", "year-round"] },
  { id: "ca-riverside", name: "Riverside Lawn Bowling Club", city: "Riverside", state: "California", stateCode: "CA", region: "west", address: "4020 Bowling Green Dr., Fairmount Park, Riverside, CA", website: "https://riversidelawnbowlingclub.godaddysites.com/", greens: 2, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Parking"], founded: 1926, description: "Celebrating 100 years in 2026. First month free for newcomers.", status: "active", hasOnlinePresence: true, tags: ["historic", "public-park", "beginner-friendly"] },
  { id: "ca-santa-ana", name: "Santa Ana Lawn Bowling Club", city: "Santa Ana", state: "California", stateCode: "CA", region: "west", address: "510 E. Memory Lane, Santiago Park, Santa Ana, CA 92706", website: "https://www.santaanalawnbowling.com/", greens: 2, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1938, description: "Green built 1935-36 with WPA funding.", status: "active", hasOnlinePresence: true, tags: ["historic", "public-park"] },
  { id: "ca-oaks-north", name: "Oaks North Lawn Bowling Club", city: "San Diego", state: "California", stateCode: "CA", region: "west", address: "12578 Oaks North Dr., San Diego, CA 92128", website: "https://www.oaksnorthcommunity.org/lawn-bowling/", greens: 1, surfaceType: "synthetic", division: "southwest", activities: ["Social Bowls", "League/Pennant", "Tournaments"], facilities: ["Clubhouse"], founded: 1974, description: "Active since 1974 in Rancho Bernardo.", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community"] },
  { id: "ca-oxnard", name: "Oxnard-Joslyn Lawn Bowls Club", city: "Oxnard", state: "California", stateCode: "CA", region: "west", address: "350 N. C St., Wilson Park, Oxnard, CA 93030", website: "https://www.oxnardlbc.com/", greens: 1, surfaceType: "synthetic", division: "southwest", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Parking"], status: "active", hasOnlinePresence: true, tags: ["public-park", "beginner-friendly"] },
  { id: "ca-hermosa-beach", name: "Hermosa Beach Lawn Bowling Club", city: "Hermosa Beach", state: "California", stateCode: "CA", region: "west", address: "861 Valley Dr., Hermosa Beach, CA", website: "https://hblbc.org/", greens: 1, surfaceType: "unknown", division: "southwest", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse"], founded: 1936, description: "Founded 1936 by former Mayor John Clark.", status: "active", hasOnlinePresence: true, tags: ["beach-community", "year-round"] },
  { id: "ca-cambria", name: "Cambria Lawn Bowls Club", city: "Cambria", state: "California", stateCode: "CA", region: "west", address: "Joslyn Recreation Center, 950 Main St., Cambria, CA 93428", greens: 1, surfaceType: "synthetic", division: "southwest", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse"], founded: 1968, description: "Northernmost club in the Southwest Division.", status: "active", hasOnlinePresence: true, tags: ["central-coast"] },
  { id: "ca-pomona", name: "Pomona Lawn Bowling Club", city: "Pomona", state: "California", stateCode: "CA", region: "west", address: "451 E. Arrow Highway, Pomona, CA 91767", website: "http://pomonalawnbowlingclub.com/", greens: 1, surfaceType: "unknown", division: "southwest", activities: ["Social Bowls"], facilities: ["Parking"], description: "Active for 80+ years.", status: "active", hasOnlinePresence: true, tags: ["public-park"] },
  { id: "ca-hemet", name: "Hemet-Joslyn Lawn Bowls Club", city: "Hemet", state: "California", stateCode: "CA", region: "west", address: "Gibbel Park, 2625 W. Devonshire Ave., Hemet, CA 92543", greens: 1, surfaceType: "synthetic", division: "southwest", activities: ["Social Bowls", "League/Pennant"], facilities: ["Parking"], founded: 1976, description: "Welcomes Canadian snowbird visitors.", status: "active", hasOnlinePresence: false, tags: ["snowbird-friendly"] },
  { id: "ca-friendly-valley", name: "Friendly Valley Lawn Bowls Club", city: "Santa Clarita", state: "California", stateCode: "CA", region: "west", address: "19345 Avenue of the Oaks, Newhall, CA 91321", website: "https://friendlyvalley.com/lawn-bowls", greens: 1, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse"], founded: 1966, description: "Tournament-legal green in a private 55+ community.", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community"] },
  { id: "ca-sun-city-menifee", name: "Sun City Lawn Bowls Club", city: "Menifee", state: "California", stateCode: "CA", region: "west", address: "26921 Sun City Blvd., Sun City, CA 92586", website: "https://www.suncitylawnbowls.com/", greens: 2, surfaceType: "natural_grass", division: "southwest", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse", "Parking"], founded: 1963, description: "Night bowling in summer. Second green built by members in 1969.", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community", "night-bowling", "year-round"] },
  { id: "ca-groves-irvine", name: "The Groves Lawn Bowling Club", city: "Irvine", state: "California", stateCode: "CA", region: "west", address: "5200 Irvine Blvd., Irvine, CA 92620", greens: 1, surfaceType: "synthetic", division: "southwest", activities: ["Social Bowls", "Tournaments", "Corporate Events"], facilities: ["Clubhouse"], description: "Hosts divisional tournaments and corporate events.", status: "active", hasOnlinePresence: false, tags: ["corporate-events"] },
  { id: "ca-casta-del-sol", name: "Casta del Sol Lawn Bowling Club", city: "Mission Viejo", state: "California", stateCode: "CA", region: "west", address: "24351 Via Albeniz, Mission Viejo, CA", greens: 1, surfaceType: "synthetic", division: "southwest", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse"], description: "Gated 55+ community club. Participates in SWD Ladies Day events.", status: "unverified", hasOnlinePresence: false, tags: ["55+", "retirement-community"] },
  // ===================== ARIZONA =====================
  { id: "az-bell", name: "Bell Lawn Bowls Club", city: "Sun City", state: "Arizona", stateCode: "AZ", region: "west", address: "Bell Recreation Center, 16820 N. 99th Ave., Sun City, AZ 85351", website: "https://suncityaz.org/recreation/clubs/bell-lawn-bowls/", greens: 2, rinks: 16, surfaceType: "synthetic", division: "south_central", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking", "Restrooms"], description: "Recently renovated synthetic greens. Special aids for those needing assistance.", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community", "year-round"] },
  { id: "az-johnson", name: "Johnson Lawn Bowls Club", city: "Sun City West", state: "Arizona", stateCode: "AZ", region: "west", address: "R.H. Johnson Recreation Center, Sun City West, AZ", website: "https://lawnbowls.scwclubs.com/", greens: 4, rinks: 32, surfaceType: "synthetic", division: "south_central", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking", "Restrooms"], description: "Four greens — one of the largest facilities in the US. Hosted international competitions.", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community", "year-round", "large-club"] },
  { id: "az-lakeview", name: "Lakeview Lawn Bowls Club", city: "Sun City", state: "Arizona", stateCode: "AZ", region: "west", address: "Lakeview Recreation Center, 10626 W. Thunderbird Blvd., Sun City, AZ", website: "https://suncityaz.org/recreation/clubs/lakeview-lawn-bowls/", greens: 2, surfaceType: "synthetic", division: "south_central", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse", "Parking"], description: "Lakeside setting with lighted greens. Hosted U.S. Open events.", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community", "night-bowling", "lake-view", "year-round"] },
  { id: "az-oakmont", name: "Oakmont Lawn Bowls Club", city: "Sun City", state: "Arizona", stateCode: "AZ", region: "west", address: "Oakmont Recreation Center, 10725 W. Oakmont Dr., Sun City, AZ", website: "https://suncityaz.org/recreation/clubs/oakmont-lawn-bowls/", greens: 2, surfaceType: "synthetic", division: "south_central", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], description: "Original Sun City lawn bowling location. Hosted North American Challenge.", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community", "historic", "year-round"] },
  { id: "az-leisure-world-mesa", name: "Leisure World Lawn Bowling Club", city: "Mesa", state: "Arizona", stateCode: "AZ", region: "west", address: "908 S. Power Rd., Mesa, AZ", greens: 1, surfaceType: "unknown", division: "south_central", activities: ["Social Bowls"], facilities: ["Parking"], status: "active", hasOnlinePresence: false, tags: ["55+", "retirement-community", "year-round"] },
  { id: "az-paradise-rv", name: "Paradise RV Resort Lawn Bowls Club", city: "Sun City", state: "Arizona", stateCode: "AZ", region: "west", address: "10950 W. Union Hills Dr., Sun City, AZ 85373", greens: 1, surfaceType: "unknown", division: "south_central", activities: ["Social Bowls", "Coaching/Lessons"], facilities: ["Parking"], description: "RV resort with weekly lawn bowling classes.", status: "active", hasOnlinePresence: false, tags: ["55+", "snowbird-friendly", "year-round"] },
  { id: "az-fairway-mountain-view", name: "Fairway/Mountain View Lawn Bowls Club", city: "Sun City", state: "Arizona", stateCode: "AZ", region: "west", address: "Fairway Recreation Center, 10600 W. Peoria Ave., Sun City, AZ", website: "https://suncityaz.org/recreation/clubs/fairway-mountain-view-lawn-bowls/", greens: 2, surfaceType: "synthetic", division: "south_central", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], description: "Combined club across two recreation centers. Special aids for those needing assistance.", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community", "year-round", "accessible"] },
  // ===================== FLORIDA =====================
  { id: "fl-clearwater", name: "Clearwater Lawn Bowls Club", city: "Clearwater", state: "Florida", stateCode: "FL", region: "south", address: "1040 Calumet Street, Clearwater, FL 33755", website: "https://clearwaterlawnbowlingclub.org/", memberCount: 100, rinks: 22, surfaceType: "synthetic", division: "southeast", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Open Days"], facilities: ["Clubhouse", "Parking", "Restrooms"], founded: 1924, description: "Largest number of rinks (22) in the Southern US. Celebrated centennial in 2024.", status: "active", hasOnlinePresence: true, tags: ["year-round", "beginner-friendly", "historic", "large-club"] },
  { id: "fl-sun-city-center", name: "Sun City Center Lawn Bowling Club", city: "Sun City Center", state: "Florida", stateCode: "FL", region: "south", address: "1009 N. Pebble Beach Blvd., Sun City Center, FL 33573", website: "https://www.suncitycenterlbc.com/", greens: 3, surfaceType: "unknown", division: "southeast", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking", "Restrooms"], founded: 1962, description: "Hosted 2023 US National Championships. Evening bowling under lights.", status: "active", hasOnlinePresence: true, tags: ["55+", "large-club", "retirement-community", "year-round", "night-bowling"] },
  { id: "fl-sarasota", name: "Sarasota Lawn Bowling Club", city: "Sarasota", state: "Florida", stateCode: "FL", region: "south", address: "951 Circus Boulevard, Sarasota, FL 34232", website: "https://www.sarasotalawnbowlingclub.com/", greens: 1, surfaceType: "unknown", division: "southeast", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], description: "Also offers croquet. Hosts certified coach training.", status: "active", hasOnlinePresence: true, tags: ["year-round", "beginner-friendly"] },
  { id: "fl-lakeland", name: "Lakeland Lawn Bowling Club", city: "Lakeland", state: "Florida", stateCode: "FL", region: "south", address: "Lake Parker Park, 820 E. Robson St., Lakeland, FL 33805", greens: 1, rinks: 8, surfaceType: "synthetic", division: "southeast", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse", "Parking"], founded: 1923, description: "One of the oldest in Florida. Very fast pro carpet synthetic.", status: "active", hasOnlinePresence: true, tags: ["historic", "year-round"] },
  { id: "fl-mount-dora", name: "Mount Dora Lawn Bowling Club", city: "Mount Dora", state: "Florida", stateCode: "FL", region: "south", address: "125 N Edgerton Court, Mount Dora, FL 32757", website: "https://www.mountdoralbc.com/", memberCount: 240, rinks: 14, surfaceType: "synthetic", division: "southeast", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking", "Restrooms"], description: "One of the largest Bowls USA clubs (240+ members). Night bowling. Lake Dora views.", status: "active", hasOnlinePresence: true, socialMedia: { facebook: "MTDoraLawnBowling" }, tags: ["large-club", "lake-view", "night-bowling", "year-round"] },
  { id: "fl-st-petersburg", name: "St. Petersburg Lawn Bowling Club", city: "St. Petersburg", state: "Florida", stateCode: "FL", region: "south", address: "536 4th Avenue N, St. Petersburg, FL 33701", greens: 2, rinks: 13, surfaceType: "natural_grass", division: "southeast", activities: ["Social Bowls"], facilities: ["Clubhouse", "Parking", "Restrooms"], founded: 1916, description: "Oldest organized lawn bowling club in Florida. Clubhouse on National Register of Historic Places.", status: "active", hasOnlinePresence: true, tags: ["historic", "year-round", "international"] },
  { id: "fl-delray-beach", name: "Delray Beach Lawn Bowling Club", city: "Delray Beach", state: "Florida", stateCode: "FL", region: "south", address: "Veterans Park, Atlantic Ave, Delray Beach, FL", greens: 1, rinks: 6, surfaceType: "synthetic", division: "southeast", activities: ["Social Bowls", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1962, description: "Less than one hour north of Miami. Welcomes international guests.", status: "active", hasOnlinePresence: false, tags: ["year-round", "beginner-friendly"] },
  { id: "fl-kings-point", name: "Kings Point West Lawn Bowling Club", city: "Sun City Center", state: "Florida", stateCode: "FL", region: "south", address: "2526 Lancaster Drive, Sun City Center, FL 33573", website: "https://sites.google.com/view/kingspointwestlawnbowlingclub/", greens: 1, surfaceType: "unknown", division: "southeast", activities: ["Social Bowls", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], description: "Free lessons. Ages 55-90.", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community", "year-round", "beginner-friendly"] },
  { id: "fl-maple-leaf", name: "Maple Leaf Lawn Bowling Club", city: "Port Charlotte", state: "Florida", stateCode: "FL", region: "south", address: "2100 Kings Highway, Port Charlotte, FL 33980", website: "https://www.lawnbowlingml.com/", memberCount: 100, greens: 1, rinks: 8, surfaceType: "unknown", division: "southeast", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse", "Parking"], founded: 1987, description: "'Home of International Lawn Bowling in SW Florida'. Members from USA, Canada, and UK.", status: "seasonal", hasOnlinePresence: true, tags: ["55+", "retirement-community", "seasonal", "international"] },
  { id: "fl-villages", name: "The Villages Lawn Bowls Club", city: "The Villages", state: "Florida", stateCode: "FL", region: "south", address: "1228 Rio Grande Ave., The Villages, FL 32162", website: "http://www.thevillageslbc.org/", greens: 3, surfaceType: "natural_grass", division: "southeast", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"], facilities: ["Parking"], founded: 2014, description: "Three greens across America's largest 55+ community (130,000+ residents).", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community", "year-round", "beginner-friendly"] },
  { id: "fl-sun-n-fun", name: "Sun-n-Fun Lawn Bowling Club", city: "Sarasota", state: "Florida", stateCode: "FL", region: "south", address: "7125 Fruitville Road, Sarasota, FL 34240", greens: 1, surfaceType: "unknown", division: "southeast", activities: ["Social Bowls", "League/Pennant", "Coaching/Lessons"], facilities: ["Parking"], status: "seasonal", hasOnlinePresence: false, tags: ["seasonal", "snowbird-friendly"] },
  { id: "fl-world-parkway", name: "World Parkway Lawn Bowling Club", city: "Clearwater", state: "Florida", stateCode: "FL", region: "south", address: "On Top of the World Community, Clearwater, FL", greens: 1, surfaceType: "unknown", division: "southeast", activities: ["Social Bowls"], facilities: ["Parking"], description: "Within On Top of the World 55+ community (est. 1947).", status: "seasonal", hasOnlinePresence: false, tags: ["55+", "retirement-community", "seasonal"] },
  // ===================== NEW YORK =====================
  { id: "ny-central-park", name: "New York Lawn Bowling Club", city: "New York", state: "New York", stateCode: "NY", region: "east", address: "Central Park, West 69th Street, New York, NY", website: "https://www.nybowls.com/", greens: 2, rinks: 10, surfaceType: "natural_grass", division: "northeast", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Corporate Events", "Open Days", "Coaching/Lessons"], facilities: ["Clubhouse", "Restrooms"], founded: 1926, description: "Iconic Central Park location. Premier club in the Eastern US.", status: "seasonal", hasOnlinePresence: true, socialMedia: { facebook: "newyorklbc", instagram: "nybowls" }, tags: ["iconic", "central-park", "corporate-events", "seasonal", "beginner-friendly"] },
  { id: "ny-ausable", name: "Ausable Lawn Bowling Club", city: "St. Huberts", state: "New York", stateCode: "NY", region: "east", address: "137 Ausable Road, St. Huberts, NY 12943", website: "https://www.ausableclub.org/", greens: 1, surfaceType: "natural_grass", division: "northeast", activities: ["Social Bowls", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1887, description: "Ultra-exclusive Adirondack private club dating to 1887.", status: "seasonal", hasOnlinePresence: true, tags: ["private", "exclusive", "seasonal", "resort"] },
  // ===================== CONNECTICUT =====================
  { id: "ct-thistle", name: "Thistle Lawn Bowling Club", city: "West Hartford", state: "Connecticut", stateCode: "CT", region: "east", address: "1561 Asylum Avenue, Elizabeth Park, West Hartford, CT 06117", website: "https://thistlelawnbowlinginfo.wordpress.com/", greens: 2, surfaceType: "natural_grass", division: "northeast", activities: ["Social Bowls", "League/Pennant"], facilities: ["Clubhouse", "Parking"], founded: 1913, description: "Oldest lawn bowling club in Connecticut.", status: "active", hasOnlinePresence: true, socialMedia: { facebook: "ThistleLawnBowling" }, tags: ["historic", "public-park", "seasonal"] },
  { id: "ct-fernleigh", name: "Fernleigh Lawn Bowling Club", city: "West Hartford", state: "Connecticut", stateCode: "CT", region: "east", address: "35 Lancaster Road, West Hartford, CT", website: "http://www.flbc.info/", memberCount: 60, greens: 1, rinks: 7, surfaceType: "natural_grass", division: "northeast", activities: ["Social Bowls", "League/Pennant"], facilities: ["Clubhouse"], founded: 1923, description: "Evening lighting available. 'West Hartford's best-kept secret.'", status: "active", hasOnlinePresence: true, socialMedia: { facebook: "FernleighLawnBowlingClub" }, tags: ["historic", "night-bowling", "seasonal"] },
  { id: "ct-greenwich", name: "Greenwich Lawn Bowling Association", city: "Greenwich", state: "Connecticut", stateCode: "CT", region: "east", address: "Bruce Park, Greenwich, CT", greens: 1, surfaceType: "natural_grass", division: "northeast", activities: ["Social Bowls", "Open Days"], facilities: ["Parking"], founded: 1940, description: "In Greenwich's oldest public park (est. 1908).", status: "active", hasOnlinePresence: false, tags: ["public-park", "seasonal"] },
  // ===================== NEW JERSEY =====================
  { id: "nj-essex-county", name: "Essex County Lawn Bowling Club", city: "Bloomfield", state: "New Jersey", stateCode: "NJ", region: "east", address: "Watsessing Park, Bloomfield, NJ", website: "https://www.njbowls.com/", memberCount: 35, greens: 1, surfaceType: "synthetic", division: "northeast", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse"], founded: 1924, description: "Only synthetic surface in Northern NJ. Centennial in 2024.", status: "active", hasOnlinePresence: true, tags: ["historic", "seasonal", "beginner-friendly"] },
  // ===================== PENNSYLVANIA =====================
  { id: "pa-frick-park", name: "Frick Park Lawn Bowling Club", city: "Pittsburgh", state: "Pennsylvania", stateCode: "PA", region: "east", address: "7300 Reynolds Street, Pittsburgh, PA 15208", website: "https://www.lawnbowlingpittsburgh.org/", memberCount: 86, greens: 2, surfaceType: "natural_grass", division: "northeast", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons", "Open Days"], facilities: ["Clubhouse", "Parking"], founded: 1938, description: "Best-run club in the Eastern US. Only public greens in PA. Winter indoor short mat.", status: "seasonal", hasOnlinePresence: true, socialMedia: { facebook: "FrickParkLBC", instagram: "frickparklawnbowlingclub" }, tags: ["public-park", "seasonal", "beginner-friendly", "competitive"] },
  { id: "pa-buck-hill-falls", name: "Buck Hill Falls Lawn Bowling Association", city: "Buck Hill Falls", state: "Pennsylvania", stateCode: "PA", region: "east", address: "Buck Hill Falls, Barrett Township, PA", website: "https://www.buckhillfalls.com/public/community/lawn-bowling", greens: 2, rinks: 4, surfaceType: "natural_grass", division: "northeast", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1931, description: "Hosted National Finals multiple times.", status: "seasonal", hasOnlinePresence: true, tags: ["historic", "resort", "seasonal"] },
  { id: "pa-skytop", name: "Skytop Lawn Bowling Club", city: "Skytop", state: "Pennsylvania", stateCode: "PA", region: "east", address: "Skytop Lodge, Route 390, Skytop, PA", website: "https://www.skytop.com/activity/lawn-bowling/", greens: 1, surfaceType: "natural_grass", division: "northeast", activities: ["Social Bowls", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], description: "Luxury Pocono Mountains resort. Complimentary daily classes.", status: "seasonal", hasOnlinePresence: true, tags: ["resort", "seasonal", "beginner-friendly"] },
  // ===================== DELAWARE =====================
  { id: "de-dupont", name: "DuPont Country Club Lawn Bowling Club", city: "Wilmington", state: "Delaware", stateCode: "DE", region: "east", address: "DuPont Country Club, Rockland Road, Wilmington, DE", website: "https://www.dupontcountryclub.com/", greens: 1, surfaceType: "natural_grass", division: "northeast", activities: ["Social Bowls"], facilities: ["Clubhouse", "Parking", "Restrooms"], founded: 1956, status: "unverified", hasOnlinePresence: true, tags: ["private", "country-club"] },
  // ===================== MARYLAND =====================
  { id: "md-leisure-world", name: "Leisure World Lawn Bowls Club", city: "Silver Spring", state: "Maryland", stateCode: "MD", region: "east", address: "3700 Rossmoor Boulevard, Silver Spring, MD 20906", greens: 1, surfaceType: "unknown", division: "northeast", activities: ["Social Bowls"], facilities: ["Clubhouse", "Parking", "Restrooms"], description: "Within 610-acre gated 55+ community.", status: "active", hasOnlinePresence: false, tags: ["55+", "retirement-community"] },
  // ===================== VIRGINIA =====================
  { id: "va-chesapeake-bay", name: "Chesapeake Bay Lawn Bowls", city: "Hartfield", state: "Virginia", stateCode: "VA", region: "east", address: "1834 Twiggs Ferry Road, Hartfield, VA 23071", website: "https://www.cblawnbowls.com/", greens: 1, surfaceType: "natural_grass", division: "northeast", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Open Days"], facilities: ["Parking"], description: "Successor to the historic Williamsburg Inn LBC. Free Tuesdays.", status: "active", hasOnlinePresence: true, tags: ["year-round", "beginner-friendly", "free-lessons"] },
  // ===================== NORTH CAROLINA =====================
  { id: "nc-asheville", name: "Asheville Lawn Bowling Club", city: "Asheville", state: "North Carolina", stateCode: "NC", region: "south", address: "220 Amboy Road, Carrier Park, Asheville, NC 28806", website: "https://www.ashevillelawnbowls.com/", greens: 1, surfaceType: "synthetic", division: "southeast", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Parking"], description: "Claims 'premier artificial green in the USA'. Thursday bowling + brewery pub crawl.", status: "active", hasOnlinePresence: true, tags: ["year-round", "young-demographic", "beginner-friendly"] },
  { id: "nc-pinehurst", name: "Pinehurst Lawn Bowls Club", city: "Pinehurst", state: "North Carolina", stateCode: "NC", region: "south", address: "80 Carolina Vista Drive, Pinehurst, NC 28374", website: "https://www.pinehurst.com/activities/lawn-sports/", greens: 2, surfaceType: "natural_grass", division: "southeast", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1920, description: "Part of world-famous Pinehurst Resort. Hosted US Championships.", status: "active", hasOnlinePresence: true, tags: ["resort", "year-round", "competitive"] },
  // ===================== ARKANSAS =====================
  { id: "ar-hot-springs-village", name: "Village Green Bowls Club", city: "Hot Springs Village", state: "Arkansas", stateCode: "AR", region: "south", address: "200 DeSoto Park Lane, Hot Springs Village, AR 71909", website: "https://www.village-green-bowls-club.com/", greens: 1, surfaceType: "natural_grass", division: "none", activities: ["Social Bowls", "League/Pennant", "Tournaments"], facilities: ["Clubhouse", "Parking"], founded: 1978, description: "Only lawn bowling club in Arkansas. Themed tournament schedule.", status: "active", hasOnlinePresence: true, tags: ["55+", "retirement-community", "year-round"] },
  // ===================== TENNESSEE =====================
  { id: "tn-nashville-fogg-street", name: "Fogg Street Lawn Club", city: "Nashville", state: "Tennessee", stateCode: "TN", region: "south", address: "648 Fogg Street, Nashville, TN", website: "https://www.foggstreet.com/", greens: 1, rinks: 8, surfaceType: "natural_grass", division: "none", activities: ["Social Bowls", "Barefoot Bowls", "Corporate Events"], facilities: ["Clubhouse", "Parking", "Bar/Lounge", "Restrooms"], founded: 2024, description: "Nashville's rooftop lawn bowling bar/restaurant. Complimentary bowling with food purchase.", status: "active", hasOnlinePresence: true, tags: ["commercial-venue", "rooftop", "year-round", "young-demographic"] },
  // ===================== ILLINOIS =====================
  { id: "il-chicago-lakeside", name: "Lakeside Lawn Bowling Club", city: "Chicago", state: "Illinois", stateCode: "IL", region: "midwest", address: "Jackson Park, 5800 South Lake Shore Drive, Chicago, IL", website: "https://www.lawnbowlingchicago.com/", greens: 2, surfaceType: "natural_grass", division: "central", activities: ["Social Bowls", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1927, description: "In historic Jackson Park, adjacent to Museum of Science and Industry.", status: "active", hasOnlinePresence: true, tags: ["historic", "seasonal", "lakefront", "public-park", "beginner-friendly"] },
  // ===================== WISCONSIN =====================
  { id: "wi-milwaukee-lake-park", name: "Milwaukee Lake Park Lawn Bowling Club", city: "Milwaukee", state: "Wisconsin", stateCode: "WI", region: "midwest", address: "3131 East Newberry Boulevard, Milwaukee, WI 53211", website: "https://milwaukeelawnbowls.com/", greens: 2, surfaceType: "natural_grass", division: "central", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Barefoot Bowls", "Corporate Events", "Open Days", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking", "Restrooms"], founded: 1920, description: "100+ years in Frederick Law Olmsted-designed Lake Park. Bowls USA '100% member club'.", status: "seasonal", hasOnlinePresence: true, socialMedia: { facebook: "MKELawnBowling" }, tags: ["historic", "lake-view", "corporate-events", "seasonal", "beginner-friendly"] },
  // ===================== OHIO =====================
  { id: "oh-cincinnati", name: "Cincinnati Lawn Bowling Club", city: "Cincinnati", state: "Ohio", stateCode: "OH", region: "midwest", address: "3811 Newtown Road, Cincinnati, OH 45244", website: "https://www.cincinnatilawnbowlingclub.org/", greens: 1, surfaceType: "natural_grass", division: "central", activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Open Days"], facilities: ["Parking"], founded: 1922, description: "Only lawn bowling within 250 miles of Cincinnati. Trial membership $65/2 months.", status: "seasonal", hasOnlinePresence: true, tags: ["historic", "seasonal", "beginner-friendly"] },
  { id: "oh-lorain", name: "Lorain Lakeview Park Lawn Bowling", city: "Lorain", state: "Ohio", stateCode: "OH", region: "midwest", address: "1800 W. Erie Avenue, Lorain, OH 44052", website: "https://www.loraincountymetroparks.com/lakeview-park", greens: 1, surfaceType: "natural_grass", division: "central", activities: ["Social Bowls", "League/Pennant"], facilities: ["Parking", "Restrooms"], description: "Lakeside park with Lorain Lighthouse views.", status: "seasonal", hasOnlinePresence: true, tags: ["public-park", "lake-view", "seasonal"] },
  // ===================== INDIANA =====================
  { id: "in-fort-wayne", name: "Fort Wayne Lawn Bowls", city: "Fort Wayne", state: "Indiana", stateCode: "IN", region: "midwest", address: "3837 N. Wells Street, Fort Wayne, IN 46808", website: "https://fortwaynelawnbowls.com/", greens: 1, surfaceType: "natural_grass", division: "central", activities: ["Social Bowls", "League/Pennant", "Corporate Events", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 2025, description: "First lawn bowling in Indiana. Dual-sport model with curling club. Opening spring 2026.", status: "unverified", hasOnlinePresence: true, tags: ["new-club", "beginner-friendly"] },
  // ===================== MINNESOTA =====================
  { id: "mn-brits-pub", name: "Brit's Pub Lawn Bowling", city: "Minneapolis", state: "Minnesota", stateCode: "MN", region: "midwest", address: "1110 Nicollet Mall, Minneapolis, MN 55403", website: "https://britspub.com/minneapolis-brit-s-pub-lawn-bowling", greens: 1, rinks: 4, surfaceType: "natural_grass", division: "none", activities: ["Social Bowls", "League/Pennant", "Corporate Events"], facilities: ["Clubhouse", "Bar/Lounge", "Restrooms"], founded: 1998, description: "Iconic rooftop green. 10-year waitlist for league. $12/person/hour open bowling.", status: "seasonal", hasOnlinePresence: true, tags: ["commercial-venue", "rooftop", "seasonal", "urban"] },
  { id: "mn-brookview", name: "Brookview Golf & Lawn Bowling", city: "Golden Valley", state: "Minnesota", stateCode: "MN", region: "midwest", address: "200 Brookview Parkway, Golden Valley, MN 55426", website: "https://www.brookviewgolf.com/lawn-bowling", greens: 1, rinks: 8, surfaceType: "natural_grass", division: "none", activities: ["Social Bowls", "Corporate Events"], facilities: ["Parking", "Restrooms"], description: "Largest lawn bowling green in Minnesota. Municipal hourly rentals.", status: "seasonal", hasOnlinePresence: true, tags: ["public-park", "seasonal", "beginner-friendly"] },
  { id: "mn-centennial-lakes", name: "Centennial Lakes Park Lawn Bowling", city: "Edina", state: "Minnesota", stateCode: "MN", region: "midwest", address: "7499 France Avenue South, Edina, MN 55435", website: "https://www.edinamn.gov/2145/Activities-Events", surfaceType: "natural_grass", division: "none", activities: ["Social Bowls", "League/Pennant", "Tournaments"], facilities: ["Clubhouse", "Parking"], description: "Championship-caliber bentgrass in a 24-acre urban park. $20/hour per rink.", status: "seasonal", hasOnlinePresence: true, tags: ["public-park", "seasonal", "beginner-friendly"] },
  { id: "mn-maddens", name: "Madden's on Gull Lake Lawn Bowling", city: "Brainerd", state: "Minnesota", stateCode: "MN", region: "midwest", address: "11266 Pine Beach Peninsula, Brainerd, MN 56401", website: "https://www.maddens.com/recreation/", greens: 1, surfaceType: "natural_grass", division: "none", activities: ["Social Bowls", "League/Pennant"], facilities: ["Clubhouse", "Parking", "Restrooms"], description: "Only resort-based lawn bowling in the Midwest.", status: "seasonal", hasOnlinePresence: true, tags: ["resort", "seasonal"] },
  // ===================== COLORADO =====================
  { id: "co-denver", name: "Washington Park Lawn Bowling Club", city: "Denver", state: "Colorado", stateCode: "CO", region: "west", address: "Washington Park, E. Mississippi Ave. & S. Franklin St., Denver, CO", website: "https://washingtonparklawnbowlingclub.com/", memberCount: 45, greens: 1, surfaceType: "natural_grass", division: "none", activities: ["Social Bowls", "Tournaments", "Open Days", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1924, description: "Colorado's ONLY lawn bowling club. Octagonal 1925 clubhouse.", status: "seasonal", hasOnlinePresence: true, socialMedia: { facebook: "WPLBC" }, tags: ["historic", "seasonal", "public-park", "beginner-friendly"] },
  // ===================== HAWAII =====================
  { id: "hi-honolulu", name: "Honolulu Lawn Bowls Club", city: "Honolulu", state: "Hawaii", stateCode: "HI", region: "west", address: "Ala Moana Beach Park, Honolulu, HI", website: "https://www.honolululawnbowlsclub.com/", memberCount: 50, greens: 1, surfaceType: "natural_grass", division: "none", activities: ["Social Bowls", "Tournaments", "Barefoot Bowls", "Coaching/Lessons"], facilities: ["Parking"], founded: 1935, description: "ONLY lawn bowling green in Hawaii. Built on 3 feet of crushed coral. First club to admit women.", status: "active", hasOnlinePresence: true, socialMedia: { facebook: "honolululawnbowlsclub" }, tags: ["year-round", "beachside", "barefoot-bowls", "beginner-friendly"] },
  // ===================== UTAH =====================
  { id: "ut-sunriver", name: "SunRiver Lawn Bowling Club", city: "St. George", state: "Utah", stateCode: "UT", region: "west", address: "4275 Country Club Dr., St. George, UT 84790", greens: 1, surfaceType: "synthetic", division: "south_central", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse", "Parking"], description: "Hosts Huntsman Senior Games lawn bowls event.", status: "active", hasOnlinePresence: false, tags: ["55+", "retirement-community", "year-round"] },
  // ===================== WASHINGTON =====================
  { id: "wa-jefferson-park", name: "Jefferson Park Lawn Bowling Club", city: "Seattle", state: "Washington", stateCode: "WA", region: "west", address: "4103 Beacon Ave. S., Seattle, WA", website: "https://seattlebowls.org/", greens: 2, surfaceType: "natural_grass", division: "northwest", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Open Days", "Coaching/Lessons"], facilities: ["Clubhouse", "Parking"], founded: 1945, description: "Year-round play. Clubhouse available for rental. Seattle Parks partnership.", status: "active", hasOnlinePresence: true, tags: ["public-park", "beginner-friendly", "year-round"] },
  { id: "wa-spokane", name: "Spokane Lawn Bowling Club", city: "Spokane", state: "Washington", stateCode: "WA", region: "west", address: "East Mission Park, Spokane, WA", website: "https://spokanelawnbowlingclub.weebly.com/", greens: 1, surfaceType: "natural_grass", division: "northwest", activities: ["Social Bowls", "Coaching/Lessons"], facilities: ["Parking"], description: "Lessons through Spokane Parks & Rec.", status: "seasonal", hasOnlinePresence: true, tags: ["public-park", "seasonal", "beginner-friendly"] },
  { id: "wa-tacoma", name: "Tacoma Lawn Bowling Club", city: "Tacoma", state: "Washington", stateCode: "WA", region: "west", address: "Wright Park, Tacoma, WA", website: "https://www.tacomabowls.org/", greens: 1, surfaceType: "natural_grass", division: "northwest", activities: ["Social Bowls", "Tournaments"], facilities: ["Parking"], founded: 1929, description: "Longtime Wright Park fixture.", status: "seasonal", hasOnlinePresence: true, tags: ["public-park", "seasonal"] },
  // ===================== OREGON =====================
  { id: "or-portland", name: "Portland Lawn Bowling Club", city: "Portland", state: "Oregon", stateCode: "OR", region: "west", address: "7535 SE 23rd Ave., Westmoreland Park, Portland, OR 97202", website: "https://www.portlandlawnbowling.com/", greens: 1, surfaceType: "natural_grass", division: "northwest", activities: ["Social Bowls", "League/Pennant", "Tournaments", "Open Days"], facilities: ["Clubhouse", "Parking"], founded: 1933, description: "Shares facilities with petanque and croquet clubs. Indoor short mat in winter.", status: "seasonal", hasOnlinePresence: true, tags: ["public-park", "seasonal", "beginner-friendly"] },
  { id: "or-king-city", name: "King City Lawn Bowling Club", city: "King City", state: "Oregon", stateCode: "OR", region: "west", address: "King City, OR", website: "http://kingcitylawnbowling.com/", greens: 1, surfaceType: "natural_grass", division: "northwest", activities: ["Social Bowls", "Tournaments"], facilities: ["Clubhouse", "Parking"], description: "Guests $10/game. Close to Portland.", status: "seasonal", hasOnlinePresence: true, tags: ["55+", "seasonal", "beginner-friendly"] },
];

// Helper functions
export function getClubById(id: string): ClubData | undefined {
  return CLUBS.find((c) => c.id === id);
}

export function getClubsByState(stateCode: string): ClubData[] {
  return CLUBS.filter((c) => c.stateCode === stateCode);
}

export function getClubsByRegion(region: USRegion): ClubData[] {
  return CLUBS.filter((c) => c.region === region);
}

export function getStatesWithClubs(): string[] {
  return [...new Set(CLUBS.map((c) => c.stateCode))].sort();
}

export function searchClubs(query: string): ClubData[] {
  const q = query.toLowerCase();
  return CLUBS.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.city.toLowerCase().includes(q) ||
      c.state.toLowerCase().includes(q) ||
      c.description?.toLowerCase().includes(q) ||
      c.tags.some((t) => t.includes(q))
  );
}

export function getClubStats() {
  const states = getStatesWithClubs();
  const regions = [...new Set(CLUBS.map((c) => c.region))];
  const totalMembers = CLUBS.reduce((sum, c) => sum + (c.memberCount ?? 0), 0);
  return {
    totalClubs: CLUBS.length,
    totalStates: states.length,
    totalRegions: regions.length,
    totalMembers,
    activeClubs: CLUBS.filter((c) => c.status === "active").length,
    seasonalClubs: CLUBS.filter((c) => c.status === "seasonal").length,
  };
}
