// Club directory data — Global lawn bowling clubs
// USA clubs seeded from Bowls USA divisions, UK from Bowls England/Scotland, Canada from Bowls Canada

export type USState = string;
export type ClubStatus = "active" | "seasonal" | "inactive" | "unverified" | "claimed";
export type SurfaceType = "natural_grass" | "synthetic" | "hybrid" | "unknown";
export type USRegion = "west" | "east" | "south" | "midwest";
export type BowlsUSADivision = string;
export type CountryCode = "US" | "GB" | "CA" | "AU" | "NZ" | "ZA";

export interface ClubContact {
  name: string;
  role: string;
  email?: string;
  phone?: string;
  linkedinUrl?: string;
  instagramUrl?: string;
  facebookUrl?: string;
  twitterUrl?: string;
}

export interface ClubData {
  id: string;
  name: string;
  city: string;
  stateCode: string;
  state: string;
  country?: CountryCode;
  countryCode?: CountryCode;
  province?: string;
  region?: string;
  address?: string;
  lat?: number;
  lng?: number;
  website?: string;
  phone?: string;
  email?: string;
  memberCount?: number;
  greens?: number;
  rinks?: number;
  surfaceType: SurfaceType;
  division?: string;
  activities: string[];
  facilities: string[];
  founded?: number;
  description?: string;
  status: ClubStatus;
  hasOnlinePresence: boolean;
  contacts?: ClubContact[];
  facebookUrl?: string;
  instagramUrl?: string;
  youtubeUrl?: string;
  twitterUrl?: string;
  logoUrl?: string;
  coverImageUrl?: string;
  tags: string[];
  claimedBy?: string;
  claimedAt?: string;
  venueId?: string;
  isFeatured?: boolean;
  metaTitle?: string;
  metaDescription?: string;
}

export const COUNTRIES: Record<CountryCode, { name: string; code: CountryCode; flag: string }> = {
  US: { name: "United States", code: "US", flag: "🇺🇸" },
  GB: { name: "United Kingdom", code: "GB", flag: "🇬🇧" },
  CA: { name: "Canada", code: "CA", flag: "🇨🇦" },
  AU: { name: "Australia", code: "AU", flag: "🇦🇺" },
  NZ: { name: "New Zealand", code: "NZ", flag: "🇳🇿" },
  ZA: { name: "South Africa", code: "ZA", flag: "🇿🇦" },
};

export const US_STATES: Record<string, { name: string; code: string; region: USRegion }> = {
  AL: { name: "Alabama", code: "AL", region: "south" },
  AK: { name: "Alaska", code: "AK", region: "west" },
  AZ: { name: "Arizona", code: "AZ", region: "west" },
  AR: { name: "Arkansas", code: "AR", region: "south" },
  CA: { name: "California", code: "CA", region: "west" },
  CO: { name: "Colorado", code: "CO", region: "west" },
  CT: { name: "Connecticut", code: "CT", region: "east" },
  DE: { name: "Delaware", code: "DE", region: "east" },
  FL: { name: "Florida", code: "FL", region: "south" },
  GA: { name: "Georgia", code: "GA", region: "south" },
  HI: { name: "Hawaii", code: "HI", region: "west" },
  ID: { name: "Idaho", code: "ID", region: "west" },
  IL: { name: "Illinois", code: "IL", region: "midwest" },
  IN: { name: "Indiana", code: "IN", region: "midwest" },
  IA: { name: "Iowa", code: "IA", region: "midwest" },
  KS: { name: "Kansas", code: "KS", region: "midwest" },
  KY: { name: "Kentucky", code: "KY", region: "south" },
  LA: { name: "Louisiana", code: "LA", region: "south" },
  ME: { name: "Maine", code: "ME", region: "east" },
  MD: { name: "Maryland", code: "MD", region: "east" },
  MA: { name: "Massachusetts", code: "MA", region: "east" },
  MI: { name: "Michigan", code: "MI", region: "midwest" },
  MN: { name: "Minnesota", code: "MN", region: "midwest" },
  MS: { name: "Mississippi", code: "MS", region: "south" },
  MO: { name: "Missouri", code: "MO", region: "midwest" },
  MT: { name: "Montana", code: "MT", region: "west" },
  NE: { name: "Nebraska", code: "NE", region: "midwest" },
  NV: { name: "Nevada", code: "NV", region: "west" },
  NH: { name: "New Hampshire", code: "NH", region: "east" },
  NJ: { name: "New Jersey", code: "NJ", region: "east" },
  NM: { name: "New Mexico", code: "NM", region: "west" },
  NY: { name: "New York", code: "NY", region: "east" },
  NC: { name: "North Carolina", code: "NC", region: "south" },
  ND: { name: "North Dakota", code: "ND", region: "midwest" },
  OH: { name: "Ohio", code: "OH", region: "midwest" },
  OK: { name: "Oklahoma", code: "OK", region: "south" },
  OR: { name: "Oregon", code: "OR", region: "west" },
  PA: { name: "Pennsylvania", code: "PA", region: "east" },
  RI: { name: "Rhode Island", code: "RI", region: "east" },
  SC: { name: "South Carolina", code: "SC", region: "south" },
  SD: { name: "South Dakota", code: "SD", region: "midwest" },
  TN: { name: "Tennessee", code: "TN", region: "south" },
  TX: { name: "Texas", code: "TX", region: "south" },
  UT: { name: "Utah", code: "UT", region: "west" },
  VT: { name: "Vermont", code: "VT", region: "east" },
  VA: { name: "Virginia", code: "VA", region: "east" },
  WA: { name: "Washington", code: "WA", region: "west" },
  WV: { name: "West Virginia", code: "WV", region: "east" },
  WI: { name: "Wisconsin", code: "WI", region: "midwest" },
  WY: { name: "Wyoming", code: "WY", region: "west" },
  DC: { name: "Washington DC", code: "DC", region: "east" },
};

export const REGION_LABELS: Record<string, { label: string }> = {
  west:    { label: "West" },
  east:    { label: "East" },
  south:   { label: "South" },
  midwest: { label: "Midwest" },
};

export const SURFACE_LABELS: Record<SurfaceType, string> = {
  natural_grass: "Natural Grass",
  synthetic: "Synthetic",
  hybrid: "Hybrid",
  unknown: "Unknown",
};

export const ACTIVITY_OPTIONS = [
  "Social Bowls",
  "Tournaments",
  "League Play",
  "Free Lessons",
  "Coaching",
  "Night Bowls",
  "Corporate Events",
  "Junior Bowls",
  "Open Days",
] as const;

export const CLUBS: ClubData[] = [
  // === ARIZONA (7) ===
  {
    id: "bell-lawn-bowls-club",
    name: "Bell Lawn Bowls Club",
    city: "Sun City",
    stateCode: "AZ",
    state: "Arizona",
    region: "west",
    address: "Bell Recreation Center, 16820 N. 99th Ave., Sun City, AZ 85351",
    lat: 33.6231,
    lng: -112.2796,
    website: "https://suncityaz.org/recreation/clubs/bell-lawn-bowls/",
    phone: "623-583-4432",
    email: "cblbc@gmail.com",
    greens: 2,
    rinks: 16,
    surfaceType: "synthetic",
    division: "South Central",
    activities: ["Social Bowls", "League Play", "Tournaments"],
    facilities: ["Clubhouse", "Kitchen", "Parking"],
    description: "Part of Sun City's five-club lawn bowling complex. Hosted the U.S. Open of Lawn Bowling. Recently renovated synthetic greens.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["retirement-community", "us-open-host", "synthetic"],
  },
  {
    id: "fairway-mountain-view-lawn-bowls",
    name: "Fairway/Mountain View Lawn Bowls Club",
    city: "Sun City",
    stateCode: "AZ",
    state: "Arizona",
    region: "west",
    address: "Fairway Recreation Center, 10600 W. Peoria Ave., Sun City, AZ",
    lat: 33.5806,
    lng: -112.2718,
    surfaceType: "synthetic",
    division: "South Central",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["Recreation Center"],
    description: "Combined club operating across two separate recreation centers in Sun City. Special aids available for those needing assistance.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["retirement-community", "accessible"],
  },
  {
    id: "johnson-lawn-bowls-club",
    name: "Johnson Lawn Bowls Club",
    city: "Sun City West",
    stateCode: "AZ",
    state: "Arizona",
    region: "west",
    address: "R.H. Johnson Recreation Center, 19803 R.H. Johnson Blvd., Sun City West, AZ",
    lat: 33.6629,
    lng: -112.3528,
    website: "https://lawnbowls.scwclubs.com/",
    greens: 4,
    rinks: 32,
    surfaceType: "synthetic",
    division: "South Central",
    activities: ["Social Bowls", "Tournaments", "Free Lessons", "League Play"],
    facilities: ["Recreation Center", "Parking"],
    description: "One of the largest lawn bowling facilities in the US with 4 greens. Has hosted international lawn bowling competitions.",
    status: "active",
    hasOnlinePresence: true,
    isFeatured: true,
    tags: ["retirement-community", "international-host", "large-facility"],
  },
  {
    id: "lakeview-lawn-bowls-club",
    name: "Lakeview Lawn Bowls Club",
    city: "Sun City",
    stateCode: "AZ",
    state: "Arizona",
    region: "west",
    address: "Lakeview Recreation Center, 10626 W. Thunderbird Blvd., Sun City, AZ",
    lat: 33.6033,
    lng: -112.2718,
    greens: 2,
    surfaceType: "synthetic",
    division: "South Central",
    activities: ["Social Bowls", "Tournaments", "Night Bowls"],
    facilities: ["Lighted Greens", "Recreation Center"],
    description: "Scenic lakeside setting with lighted greens for evening bowling. Has hosted U.S. Open events.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["retirement-community", "night-bowls", "lakeside"],
  },
  {
    id: "leisure-world-mesa-lawn-bowling",
    name: "Leisure World Lawn Bowling Club",
    city: "Mesa",
    stateCode: "AZ",
    state: "Arizona",
    region: "west",
    address: "Leisure World Community Resort, 908 S. Power Rd., Mesa, AZ",
    lat: 33.4086,
    lng: -111.6774,
    greens: 1,
    surfaceType: "unknown",
    division: "South Central",
    activities: ["Social Bowls"],
    facilities: ["Parking"],
    description: "Green prominently located at resort entrance. Daily bowling available year-round in a 55+ gated retirement community.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["retirement-community"],
  },
  {
    id: "oakmont-lawn-bowls-sun-city-az",
    name: "Oakmont Lawn Bowls Club",
    city: "Sun City",
    stateCode: "AZ",
    state: "Arizona",
    region: "west",
    address: "Oakmont Recreation Center, 10725 W. Oakmont Dr., Sun City, AZ",
    lat: 33.5954,
    lng: -112.2910,
    surfaceType: "synthetic",
    division: "South Central",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["Recreation Center"],
    description: "Original Sun City lawn bowling location. Reportedly established with a suggestion from Walt Disney to Del Webb. Has hosted the North American Challenge.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["retirement-community", "historic"],
  },
  {
    id: "paradise-rv-resort-lawn-bowls",
    name: "Paradise RV Resort Lawn Bowls Club",
    city: "Sun City",
    stateCode: "AZ",
    state: "Arizona",
    region: "west",
    address: "Paradise RV Resort, 10950 W. Union Hills Dr., Sun City, AZ 85373",
    lat: 33.6163,
    lng: -112.2849,
    phone: "623-977-0344",
    greens: 1,
    surfaceType: "unknown",
    division: "South Central",
    activities: ["Social Bowls"],
    facilities: ["Pool", "Shuffleboard", "Pickleball"],
    description: "RV resort setting catering to seasonal and snowbird visitors. Weekly classes available.",
    status: "seasonal",
    hasOnlinePresence: false,
    tags: ["rv-resort", "snowbird"],
  },

  // === CALIFORNIA - Northern (PIMD) ===
  {
    id: "berkeley-lawn-bowling-club",
    name: "Berkeley Lawn Bowling Club",
    city: "Berkeley",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "2270 Acton St., Berkeley, CA 94702",
    lat: 37.8690,
    lng: -122.2820,
    website: "https://berkeleylawnbowling.org/",
    phone: "510-841-2174",
    email: "berkeleylawnbowling@gmail.com",
    memberCount: 95,
    greens: 2,
    surfaceType: "natural_grass",
    division: "PIMD",
    activities: ["Social Bowls", "League Play", "Tournaments", "Free Lessons"],
    facilities: ["Clubhouse"],
    founded: 1928,
    description: "Diverse membership including retirees, grad students, writers, and golfers. Non-profit since 1963 with significant membership growth.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["diverse", "non-profit", "growing"],
  },
  {
    id: "del-mesa-carmel-lawn-bowling",
    name: "Del Mesa Carmel Lawn Bowling Club",
    city: "Carmel",
    stateCode: "CA",
    state: "California",
    region: "west",
    website: "http://dmclbc.org/",
    email: "DMCLawnBowling@gmail.com",
    memberCount: 55,
    greens: 1,
    surfaceType: "natural_grass",
    division: "PIMD",
    activities: ["Social Bowls"],
    facilities: ["Fitness Center"],
    description: "Only regulation green in Monterey County. Active since the late 1960s. Open to non-residents from surrounding Monterey Peninsula.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["retirement-community", "monterey"],
  },
  {
    id: "fresno-lawn-bowls-club",
    name: "Fresno Lawn Bowls Club",
    city: "Fresno",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "Holmes Park, Fresno, CA",
    lat: 36.7378,
    lng: -119.7871,
    website: "http://www.fresnolawnbowls.org/",
    phone: "559-224-2240",
    greens: 1,
    surfaceType: "natural_grass",
    division: "PIMD",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Park Setting"],
    description: "Only lawn bowling club in California's Central Valley. Operating 20+ years at same location in Holmes Park.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["central-valley", "public-park"],
  },
  {
    id: "oakland-lawn-bowling-club",
    name: "Oakland Lawn Bowling Club",
    city: "Oakland",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "660 Bellevue Ave., Lakeside Park, Oakland, CA 94610",
    lat: 37.8087,
    lng: -122.2531,
    website: "https://www.oaklandlawnbowlingclub.com/",
    phone: "510-625-9937",
    greens: 2,
    surfaceType: "natural_grass",
    division: "PIMD",
    activities: ["Social Bowls", "League Play", "Corporate Events"],
    facilities: ["Clubhouse", "Lake Merritt Views"],
    founded: 1903,
    description: "One of the oldest clubs in the West, founded 1903 by Scottish bowlers. Beautiful Lake Merritt location. Members handle all green maintenance.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["historic", "lake-merritt", "scottish-heritage"],
  },
  {
    id: "palo-alto-lawn-bowls-club",
    name: "Palo Alto Lawn Bowls Club",
    city: "Palo Alto",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "474 Embarcadero Rd., Palo Alto, CA",
    lat: 37.4530,
    lng: -122.1540,
    website: "https://www.palbc.org/",
    greens: 1,
    rinks: 8,
    surfaceType: "natural_grass",
    division: "PIMD",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse", "Kitchen", "Locker Rooms"],
    founded: 1933,
    description: "Established 1933 with comprehensive facilities including full kitchen and locker rooms. Visiting bowlers welcome.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["silicon-valley", "facilities"],
  },
  {
    id: "rossmoor-lawn-bowling-club",
    name: "Rossmoor Lawn Bowling Club",
    city: "Walnut Creek",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "Hillside Clubhouse, 3400 Lower Golden Rain Rd., Walnut Creek, CA 94595",
    lat: 37.8823,
    lng: -122.0628,
    website: "https://www.rlbc.net/",
    phone: "925-289-8011",
    greens: 3,
    rinks: 24,
    surfaceType: "natural_grass",
    division: "PIMD",
    activities: ["Social Bowls", "Tournaments", "Free Lessons", "Coaching"],
    facilities: ["Mat House", "Parking"],
    founded: 1967,
    description: "Three greens complex in Rossmoor 55+ community. Certification required before play. One of the largest facilities in the Bay Area.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["retirement-community", "large-facility", "certification"],
  },
  {
    id: "san-francisco-lawn-bowling-club",
    name: "San Francisco Lawn Bowling Club",
    city: "San Francisco",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "Bowling Green Dr., Golden Gate Park, San Francisco, CA",
    lat: 37.7694,
    lng: -122.4574,
    website: "https://www.sflbc.org/",
    memberCount: 130,
    greens: 3,
    surfaceType: "natural_grass",
    division: "PIMD",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["Historic Clubhouse", "Park Setting"],
    founded: 1901,
    description: "Oldest public lawn bowling club in America, founded 1901. The 1915 Edwardian clubhouse is SF City Landmark #181. Governor Jim Rolph was original treasurer.",
    status: "active",
    hasOnlinePresence: true,
    isFeatured: true,
    tags: ["historic", "golden-gate-park", "landmark", "oldest-public"],
  },
  {
    id: "san-jose-lawn-bowls-club",
    name: "San Jose Lawn Bowls Club",
    city: "San Jose",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "Willow Street Frank Bramhall Park, San Jose, CA",
    lat: 37.3230,
    lng: -121.8946,
    website: "https://sjlbc-home.org/",
    greens: 1,
    surfaceType: "synthetic",
    division: "PIMD",
    activities: ["Social Bowls", "Free Lessons", "Corporate Events", "Tournaments"],
    facilities: ["Park Setting"],
    description: "World-class championship synthetic green installed in 2017 city renovation.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["championship-green", "silicon-valley"],
  },
  {
    id: "santa-clara-lawn-bowls-club",
    name: "Santa Clara Lawn Bowls Club",
    city: "Santa Clara",
    stateCode: "CA",
    state: "California",
    region: "west",
    website: "https://www.santaclaralawnbowls.org/",
    phone: "408-204-0154",
    greens: 1,
    surfaceType: "natural_grass",
    division: "PIMD",
    activities: ["Social Bowls", "Tournaments", "Free Lessons", "Night Bowls"],
    facilities: ["Park Setting"],
    description: "Active evening bowling schedule in summer. Meets multiple days per week.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["silicon-valley", "evening-bowls"],
  },
  {
    id: "santa-cruz-lawn-bowls-club",
    name: "Santa Cruz Lawn Bowls Club",
    city: "Santa Cruz",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "137 Dakota Ave., San Lorenzo Park, Santa Cruz, CA 95060",
    lat: 36.9716,
    lng: -122.0264,
    website: "https://www.sclawnbowls.org/",
    phone: "831-469-4807",
    greens: 1,
    surfaceType: "synthetic",
    division: "PIMD",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Park Setting"],
    description: "World-class artificial green in San Lorenzo Park, near downtown Santa Cruz and the ocean.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["oceanside", "downtown"],
  },
  {
    id: "sunnyvale-lawn-bowls-club",
    name: "Sunnyvale Lawn Bowls Club",
    city: "Sunnyvale",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "Martin Murphy Jr. Historical Park, Sunnyvale, CA",
    lat: 37.3688,
    lng: -122.0363,
    website: "https://www.svlbc.org/",
    phone: "408-730-7356",
    greens: 1,
    surfaceType: "natural_grass",
    division: "PIMD",
    activities: ["Social Bowls", "Free Lessons", "Tournaments"],
    facilities: ["Historic Park"],
    description: "Located in a historic park setting. All ages and abilities welcome.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["silicon-valley", "historic-park"],
  },
  {
    id: "oakmont-lawn-bowling-santa-rosa",
    name: "Oakmont Lawn Bowling Club",
    city: "Santa Rosa",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "310 White Oak Dr., Santa Rosa, CA 95409",
    lat: 38.4190,
    lng: -122.5779,
    website: "https://www.oakmontlawnbowling.com/",
    phone: "707-539-1511",
    greens: 1,
    surfaceType: "synthetic",
    division: "PIMD",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Activity Center"],
    description: "Hosted the North American Challenge Lawn Bowls Tournament in 1998. Rebuilt synthetic green.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["retirement-community", "wine-country"],
  },

  // === CALIFORNIA - Southern (Southwest Division) ===
  {
    id: "beverly-hills-lawn-bowling-club",
    name: "Beverly Hills Lawn Bowling Club",
    city: "Beverly Hills",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "Roxbury Memorial Park, 471 S. Roxbury Dr., Beverly Hills, CA 90210",
    lat: 34.0596,
    lng: -118.3976,
    website: "https://bhlbc.com/",
    email: "info@bhlbc.com",
    phone: "323-405-1147",
    greens: 2,
    surfaceType: "natural_grass",
    division: "Southwest",
    activities: ["Social Bowls", "Free Lessons"],
    facilities: ["Community Center", "Locker Rooms"],
    founded: 1926,
    description: "Historical celebrity connections including Walt Disney as a member. New community center rebuilt 2013-2014.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["celebrity-history", "beverly-hills"],
  },
  {
    id: "cambria-lawn-bowls-club",
    name: "Cambria Lawn Bowls Club",
    city: "Cambria",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "Joslyn Recreation Center, 950 Main St., Cambria, CA 93428",
    lat: 35.5636,
    lng: -121.0828,
    email: "cambrialbc@gmail.com",
    greens: 1,
    surfaceType: "synthetic",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Recreation Center"],
    founded: 1968,
    description: "Northernmost club in the Southwest Division on the beautiful Central Coast. Refurbished synthetic turf in 2019.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/CambriaLawnBowlsClub",
    tags: ["central-coast", "small-town"],
  },
  {
    id: "coronado-lawn-bowling-club",
    name: "Coronado Lawn Bowling Club",
    city: "Coronado",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "1019 7th St., Coronado, CA",
    lat: 32.6857,
    lng: -117.1778,
    website: "https://coronadolawnbowling.com/",
    phone: "619-319-5509",
    greens: 1,
    rinks: 6,
    surfaceType: "synthetic",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "League Play", "Free Lessons"],
    facilities: ["Spreckels Center"],
    founded: 1935,
    description: "World-class artificial green dedicated March 2010. New John D. Spreckels Center opened 2017. Hosts SWD South League.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["san-diego", "island"],
  },
  {
    id: "holmby-park-lawn-bowling-club",
    name: "Holmby Park Lawn Bowling Club",
    city: "Los Angeles",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "646 Comstock Ave., Los Angeles, CA 90024",
    lat: 34.0622,
    lng: -118.4285,
    website: "https://www.losangeleslawnbowling.com/",
    phone: "424-425-5996",
    memberCount: 130,
    greens: 2,
    surfaceType: "natural_grass",
    division: "Southwest",
    activities: ["Social Bowls", "Free Lessons", "Tournaments", "Night Bowls"],
    facilities: ["Rose Gardens", "Parking"],
    founded: 1927,
    description: "International membership of 130 members from 17 countries. Gorgeous Holmby Hills setting next to LA Country Club. Dues unchanged since 2008 at $95/year.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["international", "holmby-hills", "affordable"],
  },
  {
    id: "laguna-beach-lawn-bowling-club",
    name: "Laguna Beach Lawn Bowling Club",
    city: "Laguna Beach",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "455 Cliff Dr., Heisler Park, Laguna Beach, CA",
    lat: 33.5470,
    lng: -117.7852,
    website: "https://lagunabeachlawnbowlingclub.com/",
    memberCount: 376,
    greens: 2,
    rinks: 16,
    surfaceType: "natural_grass",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["Heisler Park", "Ocean Views"],
    founded: 1931,
    description: "LARGEST lawn bowling club in the USA with 376 members. Ocean-view setting in Heisler Park. City declared 'Lawn Bowling Capital of the United States' in 1957. Home of 2024 National Champions.",
    status: "active",
    hasOnlinePresence: true,
    isFeatured: true,
    tags: ["largest-club", "ocean-views", "national-champions"],
  },
  {
    id: "laguna-woods-lawn-bowling-club",
    name: "Laguna Woods Lawn Bowling Club",
    city: "Laguna Woods",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "24112 Moulton Parkway, Laguna Woods, CA 92637",
    lat: 33.6098,
    lng: -117.7250,
    website: "https://www.lwlbc.org/",
    phone: "949-951-3027",
    greens: 2,
    surfaceType: "synthetic",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "Free Lessons", "Coaching"],
    facilities: ["Community Center"],
    description: "Hosted the North American Challenge (2019) and US Open (2023). Bowls 7 days a week. 3-session training requirement for new members.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["retirement-community", "us-open-host"],
  },
  {
    id: "long-beach-lawn-bowling-club",
    name: "Long Beach Lawn Bowling Club",
    city: "Long Beach",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "1109 Federation Dr., Long Beach, CA 90804",
    lat: 33.7907,
    lng: -118.1541,
    website: "https://longbeachlbc.com/",
    phone: "562-433-9063",
    memberCount: 100,
    greens: 3,
    surfaceType: "natural_grass",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "Free Lessons", "Night Bowls"],
    facilities: ["Clubhouse", "Recreation Park"],
    founded: 1928,
    description: "Home to 2 past National Champions and a Bowls USA Hall of Fame member. 100% Bowls USA membership. $200/year dues.",
    status: "active",
    hasOnlinePresence: true,
    isFeatured: true,
    tags: ["national-champions", "hall-of-fame"],
  },
  {
    id: "mackenzie-park-lawn-bowls-club",
    name: "MacKenzie Park Lawn Bowls Club",
    city: "Santa Barbara",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "MacKenzie Park, Los Positas Rd., Santa Barbara, CA",
    lat: 34.4320,
    lng: -119.6963,
    website: "https://mplbc.com/",
    phone: "805-563-2143",
    email: "mackenzieparklbc@gmail.com",
    greens: 2,
    rinks: 16,
    surfaceType: "natural_grass",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["Clubhouse", "Kitchen", "Lockers", "Parking"],
    description: "One of two lawn bowling clubs in Santa Barbara with excellent clubhouse facilities including a full kitchen.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["santa-barbara", "facilities"],
  },
  {
    id: "newport-harbor-lawn-bowling-club",
    name: "Newport Harbor Lawn Bowling Club",
    city: "Corona del Mar",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "1550 Crown Dr. North, Corona del Mar, CA 92625",
    lat: 33.5968,
    lng: -117.8694,
    website: "https://www.newportharborlbc.com/",
    phone: "949-640-1022",
    greens: 2,
    surfaceType: "natural_grass",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "Free Lessons", "Open Days"],
    facilities: ["Clubhouse"],
    description: "Described as one of the largest and most beautiful clubs in the US. 100% Bowls USA membership with comprehensive online instruction resources.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["newport-beach", "beautiful"],
  },
  {
    id: "pasadena-lawn-bowling-club",
    name: "Pasadena Lawn Bowling Club",
    city: "Pasadena",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "275 S. Raymond Ave., Central Park, Pasadena, CA",
    lat: 34.1416,
    lng: -118.1488,
    website: "https://www.plbcc.org/",
    greens: 2,
    surfaceType: "natural_grass",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["Clubhouse", "Central Park"],
    founded: 1921,
    description: "OLDEST continuously operating lawn bowling club in the USA. 'Birthplace of California Lawn Bowling.' Hosts Rose Lawn Bowl on New Year's Eve. Never closed during COVID.",
    status: "active",
    hasOnlinePresence: true,
    isFeatured: true,
    tags: ["oldest-club", "historic", "rose-lawn-bowl"],
  },
  {
    id: "redlands-lawn-bowling-club",
    name: "Redlands Lawn Bowling Club",
    city: "Redlands",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "Sylvan Park, 411 N. University St., Redlands, CA",
    lat: 34.0601,
    lng: -117.1825,
    website: "https://www.redlandslawnbowlingclub.com/",
    phone: "909-792-4874",
    memberCount: 45,
    greens: 2,
    surfaceType: "natural_grass",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "Night Bowls"],
    facilities: ["Historic Clubhouse"],
    founded: 1921,
    description: "Second oldest in SoCal. Mission Revival style clubhouse built 1926, designated historic resource 2015. 'Rock and Bowl' Saturday evenings with music.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["historic", "mission-revival", "rock-and-bowl"],
  },
  {
    id: "riverside-lawn-bowling-club",
    name: "Riverside Lawn Bowling Club",
    city: "Riverside",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "4020 Bowling Green Dr., Fairmount Park, Riverside, CA",
    lat: 33.9759,
    lng: -117.3867,
    website: "https://riversidelawnbowlingclub.godaddysites.com/",
    phone: "951-784-7602",
    greens: 2,
    surfaceType: "natural_grass",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["Fairmount Park", "Parking"],
    founded: 1926,
    description: "Celebrating 100th anniversary in 2026. Located in historic Fairmount Park. First month free for new members.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["centennial", "fairmount-park"],
  },
  {
    id: "san-diego-lawn-bowling-club",
    name: "San Diego Lawn Bowling Club",
    city: "San Diego",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "2125 Park Blvd., Balboa Park, San Diego, CA 92134",
    lat: 32.7316,
    lng: -117.1535,
    website: "https://sandiegolawnbowling.org/",
    phone: "619-238-5457",
    memberCount: 100,
    greens: 2,
    surfaceType: "natural_grass",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "Junior Bowls", "Free Lessons"],
    facilities: ["Balboa Park"],
    founded: 1932,
    description: "Iconic Balboa Park location. Produced numerous national and international champions. Youth membership starting age 12.",
    status: "active",
    hasOnlinePresence: true,
    isFeatured: true,
    instagramUrl: "https://instagram.com/sandiegolawnbowling",
    tags: ["balboa-park", "champions", "youth"],
  },
  {
    id: "santa-anita-bowling-green-club",
    name: "Santa Anita Bowling Green Club",
    city: "Arcadia",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "Arcadia County Park, 405 S. Santa Anita Ave., Arcadia, CA",
    lat: 34.1280,
    lng: -118.0365,
    website: "https://santaanitalawnbowling.com/",
    greens: 4,
    surfaceType: "natural_grass",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "Night Bowls"],
    facilities: ["Clubhouse", "Lighted Greens", "Parking"],
    description: "One of only 2 clubs in the USA with 4 greens. Night bowling on lighted greens. Near Metro Gold Line for transit access. Frequently hosts large SWD tournaments.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["large-facility", "night-bowls", "transit"],
  },
  {
    id: "santa-barbara-lawn-bowls-club",
    name: "Santa Barbara Lawn Bowls Club",
    city: "Santa Barbara",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "1216 De La Vina St., Santa Barbara, CA 93101",
    lat: 34.4239,
    lng: -119.7110,
    website: "https://www.santabarbaralbc.org/",
    email: "sblawnbowlsclub@gmail.com",
    phone: "805-574-0221",
    greens: 1,
    surfaceType: "hybrid",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "Free Lessons", "Corporate Events"],
    facilities: ["Douglas Park"],
    founded: 1937,
    description: "Non-profit co-sponsored by City Parks & Rec. Hybrid Bermuda grass on 18-inch sand bed. Available for corporate events.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["santa-barbara", "corporate-events"],
  },
  {
    id: "santa-monica-lawn-bowls-club",
    name: "Santa Monica Lawn Bowls Club",
    city: "Santa Monica",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "Douglas Park, Wilshire Blvd., Santa Monica, CA",
    lat: 34.0304,
    lng: -118.4669,
    memberCount: 75,
    greens: 1,
    surfaceType: "hybrid",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse", "Playground", "Tennis Courts"],
    founded: 1945,
    description: "Marcellus Joslyn donated site in 1948. Laser-leveled hybrid Bermuda green. Ages 9 to 90 welcome. $125/year dues.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["beach-community", "diverse-ages"],
  },
  {
    id: "santa-ana-lawn-bowling-club",
    name: "Santa Ana Lawn Bowling Club",
    city: "Santa Ana",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "510 E. Memory Lane, Santiago Park, Santa Ana, CA 92706",
    lat: 33.7580,
    lng: -117.8500,
    website: "https://www.santaanalawnbowling.com/",
    email: "parksandrecreation@santa-ana.org",
    greens: 2,
    surfaceType: "natural_grass",
    division: "Southwest",
    activities: ["Social Bowls", "Free Lessons"],
    facilities: ["Clubhouse", "Santiago Park"],
    founded: 1938,
    description: "Green built 1935-36 with WPA (Works Progress Administration) funding. New Deal-era historic connection. Continuously operating since 1938.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["historic", "wpa", "new-deal"],
  },
  {
    id: "sun-city-ca-lawn-bowls-club",
    name: "Sun City Lawn Bowls Club",
    city: "Menifee",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "26921 Sun City Blvd., Sun City, CA 92586",
    lat: 33.7081,
    lng: -117.1960,
    website: "https://www.suncitylawnbowls.com/",
    email: "suncitylawnbowls22@gmail.com",
    greens: 2,
    surfaceType: "natural_grass",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "Night Bowls"],
    facilities: ["Civic Association Campus", "Parking"],
    founded: 1963,
    description: "First games played in 1963. Second green built by members in 1969. Night bowling in summer. Del Webb retirement community.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["retirement-community", "night-bowls"],
  },
  {
    id: "hermosa-beach-lawn-bowling-club",
    name: "Hermosa Beach Lawn Bowling Club",
    city: "Hermosa Beach",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "861 Valley Dr., Hermosa Beach, CA",
    lat: 33.8617,
    lng: -118.3965,
    website: "https://hblbc.org/",
    phone: "310-372-9080",
    greens: 1,
    surfaceType: "unknown",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Beach Community Setting"],
    founded: 1936,
    description: "Founded 1936 by former Hermosa Beach Mayor John Clark. Beach-adjacent location near the strand.",
    status: "active",
    hasOnlinePresence: true,
    instagramUrl: "https://instagram.com/hermosalbc",
    tags: ["beach", "south-bay"],
  },
  {
    id: "oxnard-joslyn-lawn-bowls-club",
    name: "Oxnard-Joslyn Lawn Bowls Club",
    city: "Oxnard",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "350 N. C St., Wilson Park, Oxnard, CA 93030",
    lat: 34.2010,
    lng: -119.1803,
    website: "https://www.oxnardlbc.com/",
    phone: "805-385-8034",
    greens: 1,
    surfaceType: "synthetic",
    division: "Southwest",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["Senior Center", "Wilson Park"],
    description: "Part of the Joslyn Center network. Downtown location in Wilson Park.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["joslyn-center", "downtown"],
  },
  {
    id: "oaks-north-lawn-bowling-club",
    name: "Oaks North Lawn Bowling Club",
    city: "San Diego",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "12578 Oaks North Dr., San Diego, CA 92128",
    lat: 33.0270,
    lng: -117.0829,
    website: "https://www.oaksnorthcommunity.org/lawn-bowling/",
    phone: "858-487-4832",
    greens: 1,
    surfaceType: "synthetic",
    division: "Southwest",
    activities: ["Social Bowls", "League Play", "Tournaments"],
    facilities: ["Community Center"],
    founded: 1974,
    description: "Active since 1974. Second largest recreational group at community center. Hosts SWD Mixed Triples tournament.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["retirement-community", "rancho-bernardo"],
  },
  {
    id: "hemet-joslyn-lawn-bowls-club",
    name: "Hemet-Joslyn Lawn Bowls Club",
    city: "Hemet",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "Gibbel Park, 2625 W. Devonshire Ave., Hemet, CA 92543",
    lat: 33.7461,
    lng: -116.9985,
    email: "hemetlawnbowlsclub@gmail.com",
    phone: "951-652-0981",
    greens: 1,
    surfaceType: "synthetic",
    division: "Southwest",
    activities: ["Social Bowls", "League Play"],
    facilities: ["Park Setting", "Joslyn Center"],
    founded: 1976,
    description: "Established 1976. Welcomes Canadian snowbird visitors. Located in Gibbel Park near Joslyn Center.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["snowbird", "inland-empire"],
  },
  {
    id: "pomona-lawn-bowling-club",
    name: "Pomona Lawn Bowling Club",
    city: "Pomona",
    stateCode: "CA",
    state: "California",
    region: "west",
    address: "451 E. Arrow Highway, Pomona, CA 91767",
    lat: 34.0744,
    lng: -117.7438,
    website: "http://pomonalawnbowlingclub.com/",
    phone: "909-625-5532",
    greens: 1,
    surfaceType: "unknown",
    division: "Southwest",
    activities: ["Social Bowls"],
    facilities: ["City Park"],
    description: "Active for 80+ years. City-sponsored lawn bowling programming.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["inland-empire"],
  },

  // === COLORADO (1) ===
  {
    id: "washington-park-lawn-bowling-club",
    name: "Washington Park Lawn Bowling Club",
    city: "Denver",
    stateCode: "CO",
    state: "Colorado",
    region: "west",
    address: "Washington Park, E. Mississippi Ave. & S. Franklin St., Denver, CO",
    lat: 39.6977,
    lng: -104.9766,
    website: "https://washingtonparklawnbowlingclub.com/",
    memberCount: 45,
    greens: 1,
    surfaceType: "natural_grass",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["Octagonal Clubhouse", "Washington Park"],
    founded: 1924,
    description: "Colorado's ONLY lawn bowling club. Celebrated 100th anniversary in 2024. Octagonal clubhouse built in 1925. Coed since founding.",
    status: "active",
    hasOnlinePresence: true,
    isFeatured: true,
    tags: ["only-in-state", "centennial", "historic-clubhouse"],
  },

  // === HAWAII (1) ===
  {
    id: "honolulu-lawn-bowls-club",
    name: "Honolulu Lawn Bowls Club",
    city: "Honolulu",
    stateCode: "HI",
    state: "Hawaii",
    region: "west",
    address: "Ala Moana Beach Park, Honolulu, HI",
    lat: 21.2899,
    lng: -157.8505,
    website: "https://www.honolululawnbowlsclub.com/",
    email: "honolululawnbowlsclub@gmail.com",
    memberCount: 50,
    greens: 1,
    surfaceType: "natural_grass",
    activities: ["Social Bowls", "Tournaments", "Coaching"],
    facilities: ["Beach Park Setting"],
    description: "ONLY lawn bowling green in Hawaii. Constructed 1935-36 by Australian servicemen on 3 feet of crushed coral. First club to admit women. Hosts Aloha Barefoot Bowls Tournament.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/honolululawnbowlsclub",
    tags: ["only-in-state", "beachside", "historic", "aloha-tournament"],
  },

  // === OREGON (2) ===
  {
    id: "portland-lawn-bowling-club",
    name: "Portland Lawn Bowling Club",
    city: "Portland",
    stateCode: "OR",
    state: "Oregon",
    region: "west",
    address: "7535 SE 23rd Ave., Westmoreland Park, Portland, OR 97202",
    lat: 45.4735,
    lng: -122.6399,
    website: "https://www.portlandlawnbowling.com/",
    phone: "971-808-4825",
    greens: 1,
    surfaceType: "natural_grass",
    division: "Northwest",
    activities: ["Social Bowls", "League Play", "Tournaments", "Free Lessons", "Open Days"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1933,
    description: "Shares facilities with Portland Petanque Club and Croquet Club. Very active community outreach via Meetup and Groupon. Indoor short mat bowls in winter.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["portland", "community-outreach", "multi-sport"],
  },
  {
    id: "king-city-lawn-bowling-club",
    name: "King City Lawn Bowling Club",
    city: "King City",
    stateCode: "OR",
    state: "Oregon",
    region: "west",
    website: "http://kingcitylawnbowling.com/",
    greens: 1,
    surfaceType: "natural_grass",
    division: "Northwest",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Community Center"],
    description: "Accessible and affordable club near Portland. Guests can bowl for $10/game. Equipment available for all bowlers.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["portland-area", "affordable"],
  },

  // === UTAH (1) ===
  {
    id: "sunriver-lawn-bowling-club",
    name: "SunRiver Lawn Bowling Club",
    city: "St. George",
    stateCode: "UT",
    state: "Utah",
    region: "west",
    address: "SunRiver Community Center, 4275 Country Club Dr., St. George, UT 84790",
    lat: 37.0764,
    lng: -113.6009,
    greens: 1,
    surfaceType: "synthetic",
    division: "South Central",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Community Center", "Parking"],
    description: "Hosts lawn bowls event for Huntsman Senior Games annually. Located in 55+ SunRiver active adult community.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["retirement-community", "huntsman-games"],
  },

  // === WASHINGTON (3) ===
  {
    id: "jefferson-park-lawn-bowling-club",
    name: "Jefferson Park Lawn Bowling Club",
    city: "Seattle",
    stateCode: "WA",
    state: "Washington",
    region: "west",
    address: "4103 Beacon Ave. S., Seattle, WA",
    lat: 47.5713,
    lng: -122.3114,
    website: "https://seattlebowls.org/",
    greens: 2,
    surfaceType: "natural_grass",
    division: "Northwest",
    activities: ["Social Bowls", "League Play", "Tournaments"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1945,
    description: "Year-round play in Seattle. Men's, women's, and mixed leagues. Clubhouse available for rental. Seattle Parks & Recreation partnership.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["seattle", "year-round", "clubhouse-rental"],
  },
  {
    id: "spokane-lawn-bowling-club",
    name: "Spokane Lawn Bowling Club",
    city: "Spokane",
    stateCode: "WA",
    state: "Washington",
    region: "west",
    address: "East Mission Park, Spokane, WA",
    lat: 47.6594,
    lng: -117.3932,
    website: "https://spokanelawnbowlingclub.weebly.com/",
    phone: "509-434-4791",
    greens: 1,
    surfaceType: "natural_grass",
    division: "Northwest",
    activities: ["Social Bowls", "Free Lessons"],
    facilities: ["Park Setting"],
    description: "Seasonal play from late spring through October. Lessons available through Spokane Parks & Rec department. Member-maintained green.",
    status: "seasonal",
    hasOnlinePresence: true,
    tags: ["spokane", "parks-rec"],
  },
  {
    id: "tacoma-lawn-bowling-club",
    name: "Tacoma Lawn Bowling Club",
    city: "Tacoma",
    stateCode: "WA",
    state: "Washington",
    region: "west",
    address: "Wright Park, Tacoma, WA",
    lat: 47.2548,
    lng: -122.4432,
    website: "https://www.tacomabowls.org/",
    email: "tacomalawnbowlingclub@gmail.com",
    greens: 1,
    surfaceType: "natural_grass",
    division: "Northwest",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Wright Park"],
    founded: 1929,
    description: "Founded 1929 in Wright Park. Longtime community fixture leasing green from Parks Tacoma.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["tacoma", "wright-park"],
  },

  // === CONNECTICUT (3) ===
  {
    id: "fernleigh-lawn-bowling-club",
    name: "Fernleigh Lawn Bowling Club",
    city: "West Hartford",
    stateCode: "CT",
    state: "Connecticut",
    region: "east",
    address: "35 Lancaster Road, West Hartford, CT",
    lat: 41.7617,
    lng: -72.7411,
    website: "http://www.flbc.info/",
    memberCount: 60,
    greens: 1,
    rinks: 7,
    surfaceType: "natural_grass",
    division: "Northeast",
    activities: ["League Play", "Social Bowls"],
    facilities: ["Clubhouse", "Lighting"],
    founded: 1923,
    description: "One of the longest-running lawn bowling clubs in the Northeast. Evening play available under lights. Described as 'West Hartford's best-kept secret.'",
    status: "seasonal",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/FernleighLawnBowlingClub",
    tags: ["historic", "evening-play", "lit-greens"],
  },
  {
    id: "greenwich-lawn-bowling-association",
    name: "Greenwich Lawn Bowling Association",
    city: "Greenwich",
    stateCode: "CT",
    state: "Connecticut",
    region: "east",
    address: "Bruce Park, Greenwich, CT",
    lat: 41.0258,
    lng: -73.6278,
    greens: 1,
    surfaceType: "natural_grass",
    division: "Northeast",
    activities: ["Social Bowls", "Open Days"],
    facilities: ["Public Park"],
    founded: 1940,
    description: "Located in Greenwich's oldest public park (est. 1908). Green maintained by municipal parks department. Daily play at 1pm Mon-Sat.",
    status: "seasonal",
    hasOnlinePresence: false,
    tags: ["public-park", "municipal"],
  },
  {
    id: "thistle-lawn-bowling-club",
    name: "Thistle Lawn Bowling Club",
    city: "West Hartford",
    stateCode: "CT",
    state: "Connecticut",
    region: "east",
    address: "1561 Asylum Avenue, Elizabeth Park, West Hartford, CT 06117",
    lat: 41.7683,
    lng: -72.7364,
    website: "https://thistlelawnbowlinginfo.wordpress.com/",
    email: "ThistleLBC@gmail.com",
    greens: 2,
    surfaceType: "natural_grass",
    division: "Northeast",
    activities: ["League Play", "Social Bowls"],
    facilities: ["Clubhouse", "Elizabeth Park"],
    founded: 1913,
    description: "Oldest lawn bowling club in Connecticut (1913). Located in the historic Elizabeth Park. East green built 1916, West green expanded 1917.",
    status: "seasonal",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/ThistleLawnBowling",
    tags: ["oldest-in-state", "elizabeth-park", "historic"],
  },

  // === DELAWARE (1) ===
  {
    id: "dupont-country-club-lawn-bowling",
    name: "DuPont Country Club Lawn Bowling",
    city: "Wilmington",
    stateCode: "DE",
    state: "Delaware",
    region: "east",
    address: "DuPont Country Club, Rockland Road, Wilmington, DE",
    lat: 39.7761,
    lng: -75.5580,
    website: "https://www.dupontcountryclub.com/",
    phone: "(302) 654-4435",
    surfaceType: "natural_grass",
    division: "Northeast",
    activities: ["Social Bowls"],
    facilities: ["Country Club", "Golf", "Tennis", "Pool"],
    founded: 1956,
    description: "Lawn bowling facilities added 1956 to the historic DuPont Company employee club (est. 1920). Private membership. Current lawn bowling activity uncertain.",
    status: "unverified",
    hasOnlinePresence: true,
    tags: ["country-club", "private"],
  },

  // === MARYLAND (1) ===
  {
    id: "leisure-world-md-lawn-bowls",
    name: "Leisure World Lawn Bowls Club",
    city: "Silver Spring",
    stateCode: "MD",
    state: "Maryland",
    region: "east",
    address: "3700 Rossmoor Boulevard, Silver Spring, MD 20906",
    lat: 39.1015,
    lng: -77.0692,
    phone: "301-598-1300",
    email: "recreation@lwmc.com",
    greens: 1,
    surfaceType: "unknown",
    division: "Northeast",
    activities: ["Social Bowls"],
    facilities: ["Clubhouse", "Pool", "Shuffleboard"],
    description: "Part of Leisure World 55+ community on 610 acres with 80+ clubs. Lawn bowling is one of many recreational offerings.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["retirement-community", "large-community"],
  },

  // === NEW JERSEY (1) ===
  {
    id: "essex-county-lawn-bowling-club",
    name: "Essex County Lawn Bowling Club",
    city: "Bloomfield",
    stateCode: "NJ",
    state: "New Jersey",
    region: "east",
    address: "Watsessing Park, Bloomfield, NJ",
    lat: 40.7905,
    lng: -74.1893,
    website: "https://www.njbowls.com/",
    email: "njbowls1924@gmail.com",
    memberCount: 35,
    greens: 1,
    surfaceType: "synthetic",
    division: "Northeast",
    activities: ["Tournaments", "League Play", "Social Bowls"],
    facilities: ["Clubhouse"],
    founded: 1924,
    description: "Only synthetic surface lawn bowling club in Northern NJ. Faster play and longer season than natural grass. Celebrated centennial in 2024. World lawn bowling gold medalist Skip Arculli was notable member.",
    status: "seasonal",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/njbowls",
    tags: ["centennial", "synthetic", "gold-medalist"],
  },

  // === NEW YORK (2) ===
  {
    id: "new-york-lawn-bowling-club",
    name: "New York Lawn Bowling Club",
    city: "New York",
    stateCode: "NY",
    state: "New York",
    region: "east",
    address: "Central Park, West 69th Street, New York, NY",
    lat: 40.7726,
    lng: -73.9748,
    website: "https://www.nybowls.com/",
    phone: "(212) 920-4352",
    greens: 2,
    surfaceType: "natural_grass",
    division: "Northeast",
    activities: ["Social Bowls", "Free Lessons", "Open Days"],
    facilities: ["Central Park Clubhouse"],
    founded: 1926,
    description: "The premier lawn bowling club in the Eastern US. Iconic Central Park location. Free community outreach programs. Featured on CBS New York. Nearly 100 years of continuous operation.",
    status: "seasonal",
    hasOnlinePresence: true,
    isFeatured: true,
    facebookUrl: "https://facebook.com/newyorklbc",
    instagramUrl: "https://instagram.com/nybowls",
    tags: ["central-park", "iconic", "community-outreach"],
  },
  {
    id: "ausable-lawn-bowling-club",
    name: "Ausable Lawn Bowling Club",
    city: "St. Huberts",
    stateCode: "NY",
    state: "New York",
    region: "east",
    address: "137 Ausable Road, St. Huberts, NY 12943",
    lat: 44.1601,
    lng: -73.7634,
    phone: "(518) 576-4411",
    website: "https://www.ausableclub.org/",
    greens: 1,
    surfaceType: "natural_grass",
    division: "Northeast",
    activities: ["Social Bowls", "Coaching"],
    facilities: ["Private Club", "Golf", "Tennis", "Pool"],
    founded: 1887,
    description: "Ultra-exclusive Adirondack private club dating to 1887. Equipment available in the Lawn Bowls Hut. Summer clinics for all ages. Flat, rubber-soled shoes required.",
    status: "seasonal",
    hasOnlinePresence: true,
    tags: ["private-club", "adirondacks", "exclusive"],
  },

  // === PENNSYLVANIA (3) ===
  {
    id: "frick-park-lawn-bowling-club",
    name: "Frick Park Lawn Bowling Club",
    city: "Pittsburgh",
    stateCode: "PA",
    state: "Pennsylvania",
    region: "east",
    address: "7300 Reynolds Street, Pittsburgh, PA 15208",
    lat: 40.4327,
    lng: -79.9082,
    website: "https://www.lawnbowlingpittsburgh.org/",
    email: "info@lawnbowlingpittsburgh.org",
    memberCount: 86,
    greens: 2,
    surfaceType: "natural_grass",
    division: "Northeast",
    activities: ["League Play", "Social Bowls", "Free Lessons", "Tournaments"],
    facilities: ["Park Setting"],
    founded: 1938,
    description: "Best-run club in the Eastern US. Only public lawn bowling greens in PA. Winter indoor short mat program. University partnerships with CMU and Pitt. Free Thursday Community Bowls nights. Online registration/payment.",
    status: "active",
    hasOnlinePresence: true,
    isFeatured: true,
    instagramUrl: "https://instagram.com/frickparklawnbowlingclub",
    tags: ["best-run", "public", "university-partnerships", "winter-program"],
  },
  {
    id: "buck-hill-falls-lawn-bowling",
    name: "Buck Hill Falls Lawn Bowling Association",
    city: "Buck Hill Falls",
    stateCode: "PA",
    state: "Pennsylvania",
    region: "east",
    address: "Buck Hill Falls community, Barrett Township, PA",
    lat: 41.1725,
    lng: -75.2685,
    website: "https://www.buckhillfalls.com/public/community/lawn-bowling",
    greens: 2,
    rinks: 4,
    surfaceType: "natural_grass",
    division: "Northeast",
    activities: ["Tournaments", "Free Lessons", "Social Bowls"],
    facilities: ["Golf Community", "Resort Amenities"],
    founded: 1931,
    description: "Has hosted National Finals multiple times. Historical celebrity bowlers including Walt Disney and William 'Bill' Hay. Green dedicated as Wilson Green in 1945.",
    status: "seasonal",
    hasOnlinePresence: true,
    tags: ["national-finals-host", "poconos", "celebrity-history"],
  },
  {
    id: "skytop-lawn-bowling-club",
    name: "Skytop Lawn Bowling Club",
    city: "Skytop",
    stateCode: "PA",
    state: "Pennsylvania",
    region: "east",
    address: "Skytop Lodge, Route 390, Skytop, PA",
    lat: 41.2081,
    lng: -75.2995,
    website: "https://www.skytop.com/activity/lawn-bowling/",
    greens: 1,
    surfaceType: "natural_grass",
    division: "Northeast",
    activities: ["Social Bowls", "Free Lessons"],
    facilities: ["Luxury Resort"],
    description: "Luxury Pocono Mountains resort. Complimentary daily classes spring through fall. Open to all resort guests, no membership required.",
    status: "seasonal",
    hasOnlinePresence: true,
    instagramUrl: "https://instagram.com/skytoplodge",
    tags: ["luxury-resort", "poconos", "complimentary"],
  },

  // === VIRGINIA (1) ===
  {
    id: "chesapeake-bay-lawn-bowls",
    name: "Chesapeake Bay Lawn Bowls",
    city: "Hartfield",
    stateCode: "VA",
    state: "Virginia",
    region: "east",
    address: "1834 Twiggs Ferry Road, Hartfield, VA 23071",
    lat: 37.5572,
    lng: -76.4697,
    website: "https://www.cblawnbowls.com/",
    phone: "(804) 694-9771",
    greens: 1,
    surfaceType: "natural_grass",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["Croquet Club Shared"],
    description: "Year-round play. FREE lawn bowling on Tuesdays. Successor to the historic Williamsburg Inn LBC. Shared facility with Chesapeake Bay Croquet Club.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["year-round", "free-tuesdays", "croquet"],
  },

  // === FLORIDA (12) ===
  {
    id: "clearwater-lawn-bowls-club",
    name: "Clearwater Lawn Bowls Club",
    city: "Clearwater",
    stateCode: "FL",
    state: "Florida",
    region: "south",
    address: "1040 Calumet Street, Clearwater, FL 33755",
    lat: 27.9802,
    lng: -82.7977,
    website: "https://clearwaterlawnbowlingclub.org/",
    phone: "(727) 641-9144",
    memberCount: 100,
    greens: 1,
    rinks: 22,
    surfaceType: "synthetic",
    division: "Southeast",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["Clubhouse", "Kitchen", "Locker Rooms", "Event Rental"],
    founded: 1924,
    description: "Largest number of rinks (22) of any club in the Southern US. Celebrated 100th anniversary in 2024. First three visits free for new bowlers. Historically one of the largest clubs in the US.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/ClearwaterLawnBowlingClub",
    tags: ["centennial", "largest-rinks-south", "har-tru"],
  },
  {
    id: "mount-dora-lawn-bowling-club",
    name: "Mount Dora Lawn Bowling Club",
    city: "Mount Dora",
    stateCode: "FL",
    state: "Florida",
    region: "south",
    address: "125 N Edgerton Court, Mount Dora, FL 32757",
    lat: 28.8006,
    lng: -81.6445,
    website: "https://www.mountdoralbc.com/",
    phone: "(352) 383-2294",
    email: "mntdoralbc@aol.com",
    memberCount: 240,
    greens: 1,
    rinks: 14,
    surfaceType: "synthetic",
    division: "Southeast",
    activities: ["Social Bowls", "Tournaments", "Free Lessons", "Night Bowls"],
    facilities: ["Clubhouse", "Night Lighting", "Lake Views", "Parking"],
    description: "One of the largest clubs in the entire US with 240+ members. 14 rinks with night lighting. Stunning Lake Dora views. Robust social calendar beyond bowling. Hosts SED Open tournaments.",
    status: "active",
    hasOnlinePresence: true,
    isFeatured: true,
    facebookUrl: "https://facebook.com/MTDoraLawnBowling",
    tags: ["largest-clubs", "night-bowls", "lake-views", "social"],
  },
  {
    id: "st-petersburg-lawn-bowling-club",
    name: "St. Petersburg Lawn Bowling Club",
    city: "St. Petersburg",
    stateCode: "FL",
    state: "Florida",
    region: "south",
    address: "536 4th Avenue N, St. Petersburg, FL 33701",
    lat: 27.7756,
    lng: -82.6361,
    phone: "(727) 347-2770",
    email: "stpetelawnbowls@gmail.com",
    greens: 2,
    rinks: 13,
    surfaceType: "natural_grass",
    division: "Southeast",
    activities: ["Social Bowls"],
    facilities: ["Historic Clubhouse", "Testing Facility"],
    founded: 1916,
    description: "Oldest formally organized lawn bowling club in Florida (est. 1916), 10th oldest in the US. Clubhouse on the National Register of Historic Places (1980). Official bowls testing facility on site. International membership.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/stpetelawnbowling",
    tags: ["national-register", "oldest-in-florida", "historic", "testing-facility"],
  },
  {
    id: "sun-city-center-lawn-bowling-club",
    name: "Sun City Center Lawn Bowling Club",
    city: "Sun City Center",
    stateCode: "FL",
    state: "Florida",
    region: "south",
    address: "1009 N. Pebble Beach Boulevard, Sun City Center, FL 33573",
    lat: 27.7164,
    lng: -82.3508,
    website: "https://www.suncitycenterlbc.com/",
    phone: "(813) 938-3176",
    email: "sccbowl@gmail.com",
    greens: 3,
    surfaceType: "unknown",
    division: "Southeast",
    activities: ["Social Bowls", "Tournaments", "Free Lessons", "Night Bowls"],
    facilities: ["Clubhouse", "Night Lighting", "Croquet"],
    founded: 1962,
    description: "Hosted US National Championships (2023). Evening bowling under lights. Multiple sub-clubs (Suncoasters ladies, Pebble Beach men). Founded by Del Webb. Online lesson registration.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/groups/2089445384418998",
    tags: ["national-championships-host", "night-bowls", "del-webb"],
  },
  {
    id: "sarasota-lawn-bowling-club",
    name: "Sarasota Lawn Bowling Club",
    city: "Sarasota",
    stateCode: "FL",
    state: "Florida",
    region: "south",
    address: "951 Circus Boulevard, Sarasota, FL 34232",
    lat: 27.3341,
    lng: -82.5164,
    website: "https://www.sarasotalawnbowlingclub.com/",
    email: "info@sarasotalawnbowling.com",
    greens: 1,
    surfaceType: "unknown",
    division: "Southeast",
    activities: ["Social Bowls", "Tournaments", "Free Lessons", "Coaching"],
    facilities: ["Clubhouse", "Parking"],
    description: "Also offers croquet. Hosts certified coach training programs. Tiered membership system (monthly, junior, day). Open to public during posted hours.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["croquet", "coach-training", "public"],
  },
  {
    id: "delray-beach-lawn-bowling-club",
    name: "Delray Beach Lawn Bowling Club",
    city: "Delray Beach",
    stateCode: "FL",
    state: "Florida",
    region: "south",
    address: "Veterans Park, Atlantic Ave, Delray Beach, FL",
    lat: 26.4610,
    lng: -80.0721,
    greens: 1,
    rinks: 6,
    surfaceType: "synthetic",
    division: "Southeast",
    activities: ["Social Bowls", "Free Lessons"],
    facilities: ["Veterans Park Clubhouse"],
    founded: 1962,
    description: "Less than one hour north of Miami. Welcomes local, state, national, and international guests. Club bowls and coaching provided.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["south-florida", "international-guests"],
  },
  {
    id: "lakeland-lawn-bowling-club",
    name: "Lakeland Lawn Bowling Club",
    city: "Lakeland",
    stateCode: "FL",
    state: "Florida",
    region: "south",
    address: "Lake Parker Park, 820 E. Robson Street, Lakeland, FL 33805",
    lat: 28.0515,
    lng: -81.9256,
    greens: 1,
    rinks: 8,
    surfaceType: "synthetic",
    division: "Southeast",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Park Setting", "Shuffleboard", "Pickleball"],
    founded: 1923,
    description: "One of the oldest clubs in Florida (est. 1923). Pro carpet surface described as 'very fast.' City-owned park facility.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/people/Lakeland-Lawn-Bowling-Club/100054508418442",
    tags: ["centenarian", "fast-green"],
  },
  {
    id: "maple-leaf-lawn-bowling-club",
    name: "Maple Leaf Lawn Bowling Club",
    city: "Port Charlotte",
    stateCode: "FL",
    state: "Florida",
    region: "south",
    address: "2100 Kings Highway, Port Charlotte, FL 33980",
    lat: 26.9908,
    lng: -82.0892,
    website: "https://www.lawnbowlingml.com/",
    phone: "(941) 627-6917",
    memberCount: 100,
    greens: 1,
    rinks: 8,
    surfaceType: "unknown",
    division: "Southeast",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Country Club", "Catering"],
    founded: 1987,
    description: "Self-described 'Home of International Lawn Bowling in SW Florida.' Full on-site catering for visiting clubs. Members from USA, Canada, and UK.",
    status: "seasonal",
    hasOnlinePresence: true,
    tags: ["international", "sw-florida", "catering"],
  },
  {
    id: "the-villages-lawn-bowls-club",
    name: "The Villages Lawn Bowls Club",
    city: "The Villages",
    stateCode: "FL",
    state: "Florida",
    region: "south",
    address: "1228 Rio Grande Ave., The Villages, FL 32162",
    lat: 28.8922,
    lng: -81.9812,
    website: "http://www.thevillageslbc.org/",
    greens: 3,
    rinks: 7,
    surfaceType: "natural_grass",
    division: "Southeast",
    activities: ["Social Bowls", "League Play", "Tournaments", "Free Lessons"],
    facilities: ["Multiple Locations", "Recreation Centers"],
    founded: 2014,
    description: "Relatively new club in one of America's largest retirement communities (130,000+ residents). 3 separate greens across different locations. Growing steadily.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["the-villages", "growing", "multiple-locations"],
  },
  {
    id: "kings-point-west-lawn-bowling-club",
    name: "Kings Point (West) Lawn Bowling Club",
    city: "Sun City Center",
    stateCode: "FL",
    state: "Florida",
    region: "south",
    address: "2526 Lancaster Drive, Sun City Center, FL 33573",
    lat: 27.7023,
    lng: -82.3672,
    website: "https://sites.google.com/view/kingspointwestlawnbowlingclub/",
    greens: 1,
    surfaceType: "unknown",
    division: "Southeast",
    activities: ["Social Bowls", "Free Lessons"],
    facilities: ["Community Center", "Parking"],
    description: "Part of Kings Point community within Sun City Center. Free lessons with no obligation to join. Ages 55-90.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/KingsPointWestLawnBowlingClub",
    tags: ["retirement-community", "sun-city-center"],
  },

  // === NORTH CAROLINA (2) ===
  {
    id: "asheville-lawn-bowling-club",
    name: "Asheville Lawn Bowling Club",
    city: "Asheville",
    stateCode: "NC",
    state: "North Carolina",
    region: "south",
    address: "220 Amboy Road, Carrier Park, Asheville, NC 28806",
    lat: 35.5650,
    lng: -82.5849,
    website: "https://www.ashevillelawnbowls.com/",
    greens: 1,
    surfaceType: "synthetic",
    division: "Southeast",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["Carrier Park", "River Views"],
    description: "Claims premier artificial green in the USA. Thursday bowling plus brewery visits. Only non-retirement-community lawn bowling club in the Southern US.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["brewery-nights", "younger-demographic", "river-views"],
  },
  {
    id: "pinehurst-lawn-bowls-club",
    name: "Pinehurst Lawn Bowls Club",
    city: "Pinehurst",
    stateCode: "NC",
    state: "North Carolina",
    region: "south",
    address: "80 Carolina Vista Drive, Pinehurst, NC 28374",
    lat: 35.1946,
    lng: -79.4713,
    website: "https://www.pinehurst.com/activities/lawn-sports/",
    phone: "(860) 857-3334",
    email: "bowls@pinehurst.com",
    greens: 2,
    surfaceType: "natural_grass",
    division: "Southeast",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["World-Class Resort", "Golf", "Tennis", "Croquet"],
    founded: 1920,
    description: "Part of world-famous Pinehurst Resort. Has hosted US Championships and North American Challenge. Open to resort guests for $20/person.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["world-class-resort", "national-host", "golf-resort"],
  },

  // === ARKANSAS (1) ===
  {
    id: "village-green-bowls-club",
    name: "Village Green Bowls Club",
    city: "Hot Springs Village",
    stateCode: "AR",
    state: "Arkansas",
    region: "south",
    address: "200 DeSoto Park Lane, Hot Springs Village, AR 71909",
    lat: 34.6662,
    lng: -93.0002,
    website: "https://www.village-green-bowls-club.com/",
    phone: "(361) 813-0260",
    email: "villagegreenbowlsclub@gmail.com",
    greens: 1,
    surfaceType: "natural_grass",
    activities: ["Social Bowls", "Tournaments", "League Play"],
    facilities: ["Clubhouse", "Bocce Courts"],
    founded: 1978,
    description: "Only lawn bowling club in Arkansas. Robust tournament schedule with themed events (Chili Bowl, Spring Bowl, Liberty Bowl, Halloween Bowl). In a gated 55+ retirement community.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["only-in-state", "themed-tournaments", "retirement-community"],
  },

  // === TENNESSEE (1) ===
  {
    id: "fogg-street-lawn-club",
    name: "Fogg Street Lawn Club",
    city: "Nashville",
    stateCode: "TN",
    state: "Tennessee",
    region: "south",
    address: "648 Fogg Street, Nashville, TN",
    lat: 36.1535,
    lng: -86.7720,
    website: "https://www.foggstreet.com/",
    phone: "(615) 678-6200",
    email: "info@foggstreet.com",
    greens: 1,
    rinks: 8,
    surfaceType: "natural_grass",
    founded: 2024,
    activities: ["Social Bowls", "Corporate Events"],
    facilities: ["Rooftop", "Restaurant", "Bar", "Downtown Views"],
    description: "Nashville's first rooftop British lawn bowling experience. Commercial bar/restaurant with complimentary bowling with F&B purchase. Winter conversion to Bavarian Ice Stock curling.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["rooftop", "commercial-venue", "downtown-nashville", "restaurant"],
  },

  // === ILLINOIS (1) ===
  {
    id: "lakeside-lawn-bowling-club",
    name: "Lakeside Lawn Bowling Club",
    city: "Chicago",
    stateCode: "IL",
    state: "Illinois",
    region: "midwest",
    address: "Jackson Park, 5800 South Lake Shore Drive, Chicago, IL",
    lat: 41.7722,
    lng: -87.5819,
    website: "https://www.lawnbowlingchicago.com/",
    phone: "(773) 610-8569",
    email: "info@lawnbowlingchicago.com",
    greens: 2,
    surfaceType: "natural_grass",
    division: "Central",
    activities: ["Social Bowls", "Free Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1927,
    description: "One of Chicago's oldest recreational clubs (est. 1927). Located in historic Jackson Park, 1893 World's Columbian Exposition site. Adjacent to Museum of Science and Industry. Afternoon tea tradition.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["jackson-park", "historic", "museum-adjacent"],
  },

  // === INDIANA (1) ===
  {
    id: "fort-wayne-lawn-bowls",
    name: "Fort Wayne Lawn Bowls",
    city: "Fort Wayne",
    stateCode: "IN",
    state: "Indiana",
    region: "midwest",
    address: "3837 N. Wells Street, Fort Wayne, IN 46808",
    lat: 41.0980,
    lng: -85.1397,
    website: "https://fortwaynelawnbowls.com/",
    greens: 1,
    surfaceType: "natural_grass",
    activities: ["Social Bowls", "League Play", "Free Lessons", "Corporate Events"],
    facilities: ["Curling Club Shared"],
    founded: 2025,
    description: "First lawn bowling facility in Indiana. Innovative dual-sport model with curling club (lawn bowls April-September, curling September-April). AWS Foundation grant supported. Opening spring 2026.",
    status: "unverified",
    hasOnlinePresence: true,
    tags: ["new-club", "dual-sport", "curling", "accessible"],
  },

  // === MINNESOTA (4) ===
  {
    id: "brits-pub-lawn-bowling",
    name: "Brit's Pub Lawn Bowling",
    city: "Minneapolis",
    stateCode: "MN",
    state: "Minnesota",
    region: "midwest",
    address: "1110 Nicollet Mall, Minneapolis, MN 55403",
    lat: 44.9721,
    lng: -93.2752,
    website: "https://britspub.com/minneapolis-brit-s-pub-lawn-bowling",
    phone: "(612) 332-3908",
    email: "manager@britspub.com",
    greens: 1,
    rinks: 4,
    surfaceType: "natural_grass",
    division: "Central",
    activities: ["Social Bowls", "League Play", "Corporate Events"],
    facilities: ["Rooftop", "British Pub", "Bar Service"],
    founded: 1998,
    description: "Iconic rooftop lawn bowling green in downtown Minneapolis. 10-year league waitlist indicates extraordinary demand. $12/person/hour for open bowling. One of the most well-known lawn bowling venues in the US.",
    status: "seasonal",
    hasOnlinePresence: true,
    tags: ["rooftop", "british-pub", "iconic", "10-year-waitlist"],
  },
  {
    id: "brookview-golf-lawn-bowling",
    name: "Brookview Golf & Lawn Bowling",
    city: "Golden Valley",
    stateCode: "MN",
    state: "Minnesota",
    region: "midwest",
    address: "200 Brookview Parkway, Golden Valley, MN 55426",
    lat: 44.9865,
    lng: -93.3638,
    website: "https://www.brookviewgolf.com/lawn-bowling",
    phone: "(763) 512-2300",
    greens: 1,
    rinks: 8,
    surfaceType: "natural_grass",
    division: "Central",
    activities: ["Social Bowls", "Corporate Events"],
    facilities: ["Golf Course", "Fire Pit", "Lighting"],
    description: "Largest lawn bowling green in Minnesota with 8 rinks. Municipal facility with fire pit and lighting for evening events. $25-30/hour per rink.",
    status: "seasonal",
    hasOnlinePresence: true,
    tags: ["municipal", "largest-green-mn", "golf-complex"],
  },
  {
    id: "centennial-lakes-lawn-bowling",
    name: "Centennial Lakes Park Lawn Bowling",
    city: "Edina",
    stateCode: "MN",
    state: "Minnesota",
    region: "midwest",
    address: "7499 France Avenue South, Edina, MN 55435",
    lat: 44.8767,
    lng: -93.3340,
    website: "https://www.edinamn.gov/2145/Activities-Events",
    phone: "(952) 833-9580",
    email: "centenniallakes@EdinaMN.gov",
    surfaceType: "natural_grass",
    division: "Central",
    activities: ["Social Bowls", "Tournaments", "League Play"],
    facilities: ["Urban Park", "Clubhouse", "Lake Views"],
    description: "Championship-caliber bentgrass greens described as 'some of the finest in the Midwest.' Beautiful 24-acre urban park setting. $20/hour per rink.",
    status: "seasonal",
    hasOnlinePresence: true,
    tags: ["championship-greens", "urban-park", "affordable"],
  },
  {
    id: "maddens-gull-lake-lawn-bowling",
    name: "Madden's on Gull Lake Lawn Bowling",
    city: "Brainerd",
    stateCode: "MN",
    state: "Minnesota",
    region: "midwest",
    address: "11266 Pine Beach Peninsula, Brainerd, MN 56401",
    lat: 46.3947,
    lng: -94.3370,
    website: "https://www.maddens.com/recreation/",
    greens: 1,
    surfaceType: "natural_grass",
    activities: ["Social Bowls", "League Play"],
    facilities: ["Resort", "Golf", "Tennis", "Lake Views"],
    description: "Only resort-based lawn bowling venue in the Midwest. USCA-sanctioned croquet lawns on same quality bentgrass surface. League open to non-resort guests.",
    status: "seasonal",
    hasOnlinePresence: true,
    tags: ["resort", "vacation-destination", "brainerd-lakes"],
  },

  // === OHIO (2) ===
  {
    id: "cincinnati-lawn-bowling-club",
    name: "Cincinnati Lawn Bowling Club",
    city: "Cincinnati",
    stateCode: "OH",
    state: "Ohio",
    region: "midwest",
    address: "3811 Newtown Road, Cincinnati, OH 45244",
    lat: 39.1239,
    lng: -84.3421,
    website: "https://www.cincinnatilawnbowlingclub.org/",
    phone: "(513) 378-6068",
    email: "info@lawnbowling.org",
    greens: 1,
    surfaceType: "natural_grass",
    division: "Central",
    activities: ["Social Bowls", "Tournaments", "Free Lessons"],
    facilities: ["Golf Center", "Parking"],
    founded: 1922,
    description: "Only lawn bowling venue within approximately 250 miles. Green praised by international visitors. Innovative trial membership ($65/2 months). Partnership with Great Parks of Hamilton County.",
    status: "seasonal",
    hasOnlinePresence: true,
    tags: ["only-in-region", "trial-membership", "centenarian"],
  },
  {
    id: "lorain-lakeview-park-lawn-bowling",
    name: "Lorain Lakeview Park Lawn Bowling",
    city: "Lorain",
    stateCode: "OH",
    state: "Ohio",
    region: "midwest",
    address: "1800 W. Erie Avenue, Lorain, OH 44052",
    lat: 41.4656,
    lng: -82.1852,
    website: "https://www.loraincountymetroparks.com/lakeview-park",
    phone: "(440) 245-1193",
    surfaceType: "natural_grass",
    division: "Central",
    activities: ["League Play", "Social Bowls"],
    facilities: ["Lakeside Park", "Beach", "Rose Garden"],
    description: "20-acre lakeside recreational park with beach, rose garden, and lighthouse views. Weekly lawn bowling league play.",
    status: "seasonal",
    hasOnlinePresence: false,
    tags: ["lakeside", "lighthouse-views", "public-park"],
  },

  // === WISCONSIN (1) ===
  {
    id: "milwaukee-lake-park-lawn-bowls-club",
    name: "Milwaukee Lake Park Lawn Bowls Club",
    city: "Milwaukee",
    stateCode: "WI",
    state: "Wisconsin",
    region: "midwest",
    address: "3131 East Newberry Boulevard, Milwaukee, WI 53211",
    lat: 43.0807,
    lng: -87.8781,
    website: "https://milwaukeelawnbowls.com/",
    greens: 2,
    surfaceType: "natural_grass",
    division: "Central",
    activities: ["League Play", "Tournaments", "Social Bowls", "Free Lessons", "Coaching", "Open Days"],
    facilities: ["Clubhouse", "Lake Park", "Parking"],
    founded: 1920,
    description: "Over 100 years of lawn bowling tradition in Frederick Law Olmsted-designed Lake Park. Bowls USA '100% member club.' Hosted 1980 National Open Tournament. Member portal/app available.",
    status: "seasonal",
    hasOnlinePresence: true,
    isFeatured: true,
    facebookUrl: "https://facebook.com/MKELawnBowling",
    tags: ["centenarian", "olmsted-park", "member-portal", "national-host"],
  },
];

// Lazy-loaded global clubs — import these files when available
let _allClubs: ClubData[] | null = null;

export function getAllClubs(): ClubData[] {
  if (_allClubs) return _allClubs;
  // Start with US clubs, enrich with contacts, add global
  const usClubs = CLUBS.map((c) => ({ ...c, country: "US" as CountryCode, countryCode: "US" as CountryCode }));

  // Enrich US clubs with contact data
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const contacts = require("./clubs-contacts-usa");
    if (contacts?.USA_CLUB_CONTACTS) {
      for (const club of usClubs) {
        const clubContacts = contacts.USA_CLUB_CONTACTS[club.id];
        if (clubContacts?.length) club.contacts = clubContacts;
      }
    }
    if (contacts?.USA_CLUB_SOCIALS) {
      for (const club of usClubs) {
        const socials = contacts.USA_CLUB_SOCIALS[club.id];
        if (socials) {
          if (socials.facebookUrl && !club.facebookUrl) club.facebookUrl = socials.facebookUrl;
          if (socials.instagramUrl && !club.instagramUrl) club.instagramUrl = socials.instagramUrl;
          if (socials.twitterUrl && !club.twitterUrl) club.twitterUrl = socials.twitterUrl;
        }
      }
    }
  } catch { /* USA contacts not yet available */ }

  const all: ClubData[] = [...usClubs];

  // Add UK clubs
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const uk = require("./clubs-data-uk");
    if (uk?.UK_CLUBS) all.push(...uk.UK_CLUBS);
  } catch { /* UK data not yet available */ }

  // Add Canada clubs
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const ca = require("./clubs-data-canada");
    if (ca?.CANADA_CLUBS) all.push(...ca.CANADA_CLUBS);
  } catch { /* Canada data not yet available */ }

  _allClubs = all;
  return all;
}

export function getClubById(id: string): ClubData | undefined {
  return getAllClubs().find((c) => c.id === id);
}

export function getClubsByState(stateCode: string): ClubData[] {
  return getAllClubs().filter((c) => c.stateCode === stateCode);
}

export function getClubsByCountry(countryCode: CountryCode): ClubData[] {
  return getAllClubs().filter((c) => (c.country ?? c.countryCode ?? "US") === countryCode);
}

export function getClubsByRegion(region: string): ClubData[] {
  return getAllClubs().filter((c) => c.region === region);
}

export function getStatesWithClubs(): string[] {
  return [...new Set(getAllClubs().map((c) => c.stateCode))].sort();
}

export function getCountriesWithClubs(): CountryCode[] {
  return [...new Set(getAllClubs().map((c) => (c.country ?? c.countryCode ?? "US") as CountryCode))].sort();
}

export function getClubsWithCoordinates(): ClubData[] {
  return getAllClubs().filter((c) => c.lat != null && c.lng != null);
}

export function searchClubs(query: string): ClubData[] {
  const q = query.toLowerCase();
  return getAllClubs().filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.city.toLowerCase().includes(q) ||
      c.state.toLowerCase().includes(q) ||
      c.description?.toLowerCase().includes(q) ||
      c.tags.some((t) => t.includes(q)) ||
      c.region?.toLowerCase().includes(q) ||
      c.province?.toLowerCase().includes(q) ||
      c.contacts?.some((ct) => ct.name.toLowerCase().includes(q))
  );
}

export function getClubStats() {
  const all = getAllClubs();
  const states = [...new Set(all.map((c) => c.stateCode))];
  const countries = getCountriesWithClubs();
  const regions = [...new Set(all.filter((c) => c.region).map((c) => c.region))];
  const totalMembers = all.reduce((sum, c) => sum + (c.memberCount ?? 0), 0);
  return {
    totalClubs: all.length,
    totalStates: states.length,
    totalCountries: countries.length,
    totalRegions: regions.length,
    totalMembers,
    activeClubs: all.filter((c) => c.status === "active").length,
    seasonalClubs: all.filter((c) => c.status === "seasonal").length,
  };
}

/** Calculate the distance in miles between two lat/lng points using the Haversine formula. */
export function haversineDistance(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 3958.8; // Earth's radius in miles
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLng / 2) *
      Math.sin(dLng / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

/** Return the nearest clubs to a given lat/lng, sorted by distance ascending. */
export function getNearestClubs(
  lat: number,
  lng: number,
  count: number,
  excludeId?: string
): (ClubData & { distance: number })[] {
  return getAllClubs()
    .filter((c) => c.lat != null && c.lng != null && c.id !== excludeId)
    .map((c) => ({
      ...c,
      distance: haversineDistance(lat, lng, c.lat!, c.lng!),
    }))
    .sort((a, b) => a.distance - b.distance)
    .slice(0, count);
}
