// Club directory data — UK lawn bowls clubs
// Extracted from market research: England & Scotland
// Source: .planning/research/GLOBAL_UK_BOWLS.md

import type { ClubData, ClubStatus, SurfaceType } from "./clubs-data";

export interface ClubContact {
  name: string;
  role: string;
  email?: string;
  phone?: string;
  linkedinUrl?: string;
  instagramUrl?: string;
  facebookUrl?: string;
  twitterUrl?: string;
}

export interface UKClubData extends ClubData {
  country: "GB";
  countryCode: "GB";
  province: string; // county or region name
  contacts: ClubContact[];
}

export type UKRegion = "south_east" | "south_west" | "london" | "midlands" | "north_east" | "north_west" | "east" | "scotland";

export const UK_COUNTIES: Record<string, { name: string; region: UKRegion }> = {
  WAR: { name: "Warwickshire", region: "midlands" },
  HAM: { name: "Hampshire", region: "south_east" },
  DEV: { name: "Devon", region: "south_west" },
  NTY: { name: "North Tyneside", region: "north_east" },
  DOR: { name: "Dorset", region: "south_west" },
  LIN: { name: "Lincolnshire", region: "east" },
  NOT: { name: "Nottinghamshire", region: "midlands" },
  NFK: { name: "Norfolk", region: "east" },
  WSX: { name: "West Sussex", region: "south_east" },
  GLN: { name: "Greater London", region: "london" },
  SRY: { name: "Surrey", region: "south_east" },
  SOM: { name: "Somerset", region: "south_west" },
  WMD: { name: "West Midlands", region: "midlands" },
  TWR: { name: "Tyne and Wear", region: "north_east" },
  DUR: { name: "County Durham", region: "north_east" },
  BKM: { name: "Buckinghamshire", region: "south_east" },
  SYK: { name: "South Yorkshire", region: "north_east" },
  ESS: { name: "Essex", region: "east" },
  NHA: { name: "Northamptonshire", region: "midlands" },
  BRS: { name: "Bristol", region: "south_west" },
  GLA: { name: "Glasgow", region: "scotland" },
  EDN: { name: "Edinburgh", region: "scotland" },
  ABD: { name: "Aberdeenshire", region: "scotland" },
  DND: { name: "Dundee", region: "scotland" },
  AYR: { name: "Ayrshire", region: "scotland" },
  PER: { name: "Perthshire", region: "scotland" },
};

export const UK_CLUBS: UKClubData[] = [
  // ─── ENGLAND — Top 35 Clubs ───────────────────────────────────────────

  {
    id: "royal-leamington-spa-bowling-club",
    name: "Royal Leamington Spa Bowling Club",
    city: "Royal Leamington Spa",
    stateCode: "WAR",
    state: "Warwickshire",
    country: "GB",
    countryCode: "GB",
    province: "Warwickshire",
    region: "midlands",
    address: "Victoria Park, Archery Road, Royal Leamington Spa, CV31 3PT",
    lat: 52.2819,
    lng: -1.5362,
    website: "https://www.royalleamingtonspabc.org.uk/",
    phone: "01926 744916",
    email: undefined,
    memberCount: 200,
    greens: 2,
    rinks: 8,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "national_finals", "coaching"],
    facilities: ["clubhouse", "bar", "changing_rooms", "car_park"],
    founded: 1913,
    description:
      "Hosts Bowls England National Finals annually and the Aviva National Championships. Premier venue in English bowls. Women's fours national champions 2024.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["national_finals_venue", "historic", "competitive", "premier_venue"],
    contacts: [
      {
        name: "David Wigman",
        role: "Contact",
        phone: "01926 744916",
      },
    ],
  },

  {
    id: "southampton-old-bowling-green",
    name: "Southampton (Old) Bowling Green",
    city: "Southampton",
    stateCode: "HAM",
    state: "Hampshire",
    country: "GB",
    countryCode: "GB",
    province: "Hampshire",
    region: "south_east",
    address: "Lower Canal Walk, Platform Road, Southampton",
    lat: 50.8985,
    lng: -1.4049,
    website: "https://www.sobg.co.uk/",
    phone: undefined,
    email: "info@sobg.co.uk",
    memberCount: 100,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "historic_events"],
    facilities: ["clubhouse", "bar"],
    founded: 1299,
    description:
      'Claims to be the oldest surviving bowling green in the world (since 1299). Annual "Knighthood of the Green" competition since 1776 — possibly the oldest bowls competition in the world.',
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["oldest_green", "historic", "heritage", "knighthood_of_the_green"],
    contacts: [],
  },

  {
    id: "plymouth-sir-francis-drake-bowling-club",
    name: "Plymouth Sir Francis Drake Bowling Club",
    city: "Plymouth",
    stateCode: "DEV",
    state: "Devon",
    country: "GB",
    countryCode: "GB",
    province: "Devon",
    region: "south_west",
    address: "Plymouth, Devon",
    lat: 50.3755,
    lng: -4.1427,
    website: "https://plymouthsfdbc.com/",
    phone: undefined,
    email: undefined,
    memberCount: 125,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: 1907,
    description:
      "Named after Sir Francis Drake's legendary game on Plymouth Hoe in 1588. Originally founded on the Hoe; moved to current location in 1922.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["historic", "sir_francis_drake", "devon"],
    contacts: [],
  },

  {
    id: "crawford-park-bowling-club",
    name: "Crawford Park Bowling Club",
    city: "Monkseaton",
    stateCode: "NTY",
    state: "North Tyneside",
    country: "GB",
    countryCode: "GB",
    province: "North Tyneside",
    region: "north_east",
    address: "Monkseaton, North Tyneside",
    lat: 55.0405,
    lng: -1.4630,
    website: "https://crawfordparkbc.weebly.com/",
    phone: undefined,
    email: undefined,
    memberCount: 80,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "coaching", "family_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description:
      "Bowls England Club of the Year 2025. Recognized for welcoming atmosphere, strong community spirit, inclusivity, and attracting more women, families, and new players. Membership nearly doubled recently.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["club_of_the_year_2025", "inclusive", "growing", "family_friendly"],
    contacts: [],
  },

  {
    id: "dolphin-indoor-bowling-club",
    name: "Dolphin Indoor Bowling Club",
    city: "Poole",
    stateCode: "DOR",
    state: "Dorset",
    country: "GB",
    countryCode: "GB",
    province: "Dorset",
    region: "south_west",
    address: "Poole, Dorset",
    lat: 50.7190,
    lng: -1.9813,
    website: "https://www.dolphinibc.com/",
    phone: undefined,
    email: undefined,
    memberCount: 1000,
    greens: 1,
    rinks: 8,
    surfaceType: "synthetic",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "indoor_bowls"],
    facilities: ["clubhouse", "bar", "indoor_rinks", "changing_rooms", "car_park"],
    founded: undefined,
    description:
      "One of the largest indoor bowls clubs in England by membership, with approximately 1,000 members.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["indoor", "large_membership", "dorset"],
    contacts: [],
  },

  {
    id: "lincoln-indoor-bowls-club",
    name: "Lincoln Indoor Bowls Club",
    city: "Lincoln",
    stateCode: "LIN",
    state: "Lincolnshire",
    country: "GB",
    countryCode: "GB",
    province: "Lincolnshire",
    region: "east",
    address: "Lincoln, Lincolnshire",
    lat: 53.2307,
    lng: -0.5406,
    website: "https://www.lincolnibc.co.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 1400,
    greens: 1,
    rinks: 8,
    surfaceType: "synthetic",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "indoor_bowls"],
    facilities: ["clubhouse", "bar", "indoor_rinks", "changing_rooms", "car_park"],
    founded: undefined,
    description:
      "Historically one of the largest indoor bowls memberships in England, with up to 1,400 members at peak.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["indoor", "largest_membership", "lincolnshire"],
    contacts: [],
  },

  {
    id: "nottingham-indoor-bowls-club",
    name: "Nottingham Indoor Bowls Club",
    city: "Nottingham",
    stateCode: "NOT",
    state: "Nottinghamshire",
    country: "GB",
    countryCode: "GB",
    province: "Nottinghamshire",
    region: "midlands",
    address: "Nottingham, Nottinghamshire",
    lat: 52.9548,
    lng: -1.1581,
    website: "https://nottinghamindoorbowlsclub.co.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 500,
    greens: 1,
    rinks: 8,
    surfaceType: "synthetic",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "indoor_bowls", "national_championships"],
    facilities: ["clubhouse", "bar", "indoor_rinks", "changing_rooms", "car_park"],
    founded: 1981,
    description:
      "Hosts the EIBA National Championships annually. Premier indoor bowls venue in England.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["indoor", "national_championships", "eiba", "premier_venue"],
    contacts: [],
  },

  {
    id: "norfolk-bowling-club",
    name: "Norfolk Bowling Club",
    city: "Norwich",
    stateCode: "NFK",
    state: "Norfolk",
    country: "GB",
    countryCode: "GB",
    province: "Norfolk",
    region: "east",
    address: "Norwich, Norfolk",
    lat: 52.6309,
    lng: 1.2974,
    website: "https://norfolkbc.org.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 200,
    greens: 2,
    rinks: 7,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "indoor_bowls", "outdoor_bowls"],
    facilities: ["clubhouse", "bar", "indoor_rinks", "outdoor_greens"],
    founded: undefined,
    description:
      "Two outdoor greens and seven indoor rinks. Year-round play available.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["indoor_outdoor", "year_round", "norfolk"],
    contacts: [],
  },

  {
    id: "worthing-pavilion-bowling-club",
    name: "Worthing Pavilion Bowling Club",
    city: "Worthing",
    stateCode: "WSX",
    state: "West Sussex",
    country: "GB",
    countryCode: "GB",
    province: "West Sussex",
    region: "south_east",
    address: "78 Pavilion Road, Worthing, West Sussex, BN14 7EQ",
    lat: 50.8194,
    lng: -0.3785,
    website: "https://www.worthingpavilionbowlingclub.org.uk/",
    phone: "01903 820079",
    email: undefined,
    memberCount: 120,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "indoor_bowls", "outdoor_bowls"],
    facilities: ["clubhouse", "bar", "indoor_rinks", "outdoor_greens"],
    founded: undefined,
    description:
      "The only bowls club in Worthing with both indoor and outdoor rinks.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["indoor_outdoor", "west_sussex", "worthing"],
    contacts: [],
  },

  {
    id: "brentham-club-bowls-section",
    name: "Brentham Club (Bowls Section)",
    city: "Ealing",
    stateCode: "GLN",
    state: "Greater London",
    country: "GB",
    countryCode: "GB",
    province: "Greater London",
    region: "london",
    address: "Ealing, West London",
    lat: 51.5213,
    lng: -0.3065,
    website: "https://www.brenthamclub.co.uk/lawnbowls-club-ealing",
    phone: undefined,
    email: undefined,
    memberCount: 80,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse", "bar", "multi_sport"],
    founded: undefined,
    description:
      "Claims best lawn bowls green in Ealing/West London. Multi-sport club with strong heritage.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["london", "multi_sport", "heritage", "ealing"],
    contacts: [],
  },

  {
    id: "north-sheen-bowling-club",
    name: "North Sheen Bowling Club",
    city: "Richmond",
    stateCode: "SRY",
    state: "Surrey",
    country: "GB",
    countryCode: "GB",
    province: "Surrey",
    region: "south_east",
    address: "Richmond, Surrey",
    lat: 51.4672,
    lng: -0.2871,
    website: "https://www.northsheenbowlingclub.co.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 100,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description:
      "Leading club in Surrey. 2014 London & Southern Counties Challenge Shield winner. Multiple Surrey champions.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["surrey", "competitive", "shield_winner"],
    contacts: [],
  },

  {
    id: "paddington-sports-club-bowls",
    name: "Paddington Sports Club (Bowls)",
    city: "Paddington",
    stateCode: "GLN",
    state: "Greater London",
    country: "GB",
    countryCode: "GB",
    province: "Greater London",
    region: "london",
    address: "Paddington, London",
    lat: 51.5154,
    lng: -0.1755,
    website: "https://www.psclondon.com/bowls",
    phone: undefined,
    email: undefined,
    memberCount: 60,
    greens: 1,
    rinks: 4,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "social_bowls", "mixed_bowls"],
    facilities: ["clubhouse", "multi_sport"],
    founded: undefined,
    description:
      "Mixed club in central London. Good entry point for urban bowlers.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["london", "central_london", "mixed", "urban"],
    contacts: [],
  },

  {
    id: "southwark-sports-lawn-bowls-club",
    name: "Southwark Sports Lawn Bowls Club",
    city: "Dulwich",
    stateCode: "GLN",
    state: "Greater London",
    country: "GB",
    countryCode: "GB",
    province: "Greater London",
    region: "london",
    address: "Dulwich, London",
    lat: 51.4450,
    lng: -0.0750,
    website: "https://southwarksportsbowlsclub.co.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 60,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "social_bowls", "roll_ups"],
    facilities: ["clubhouse"],
    founded: undefined,
    description:
      "Active London club hosting regular social roll-ups.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["london", "dulwich", "social"],
    contacts: [],
  },

  {
    id: "parliament-hill-bowls-club",
    name: "Parliament Hill Bowls Club",
    city: "Hampstead Heath",
    stateCode: "GLN",
    state: "Greater London",
    country: "GB",
    countryCode: "GB",
    province: "Greater London",
    region: "london",
    address: "Hampstead Heath, London",
    lat: 51.5560,
    lng: -0.1500,
    website: "https://www.parliamenthillbowlsclub.co.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 70,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "social_bowls", "coaching"],
    facilities: ["clubhouse"],
    founded: undefined,
    description:
      "Located on iconic Hampstead Heath. Appeals to all ages and skill levels.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["london", "hampstead_heath", "scenic", "all_ages"],
    contacts: [],
  },

  {
    id: "burgess-hill-bowls-club",
    name: "Burgess Hill Bowls Club",
    city: "Burgess Hill",
    stateCode: "WSX",
    state: "West Sussex",
    country: "GB",
    countryCode: "GB",
    province: "West Sussex",
    region: "south_east",
    address: "Burgess Hill, West Sussex",
    lat: 50.9537,
    lng: -0.1276,
    website: "https://www.burgesshillbowlsclub.com/",
    phone: undefined,
    email: undefined,
    memberCount: 150,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse", "bar"],
    founded: undefined,
    description:
      "6-rink green, fully stocked bar, regular social events.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["west_sussex", "social", "bar"],
    contacts: [],
  },

  {
    id: "esher-bowls-club",
    name: "Esher Bowls Club",
    city: "Esher",
    stateCode: "SRY",
    state: "Surrey",
    country: "GB",
    countryCode: "GB",
    province: "Surrey",
    region: "south_east",
    address: "Esher, Surrey",
    lat: 51.3694,
    lng: -0.3650,
    website: "https://www.esherbowlsclub.co.uk/",
    phone: "07732 115854",
    email: "info.esherbowlsclub@gmail.com",
    memberCount: 80,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Active bowls club in Esher, Surrey.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["surrey", "esher"],
    contacts: [
      {
        name: "Secretary",
        role: "Secretary",
        phone: "07732 115854",
        email: "info.esherbowlsclub@gmail.com",
      },
    ],
  },

  {
    id: "mid-surrey-bowling-club",
    name: "Mid Surrey Bowling Club",
    city: "Surrey",
    stateCode: "SRY",
    state: "Surrey",
    country: "GB",
    countryCode: "GB",
    province: "Surrey",
    region: "south_east",
    address: "Surrey / West London",
    lat: 51.4400,
    lng: -0.2700,
    website: "http://www.midsurreybowls.co.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 80,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description:
      "One of the best greens in the West London area.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["surrey", "west_london", "quality_green"],
    contacts: [],
  },

  {
    id: "lindfield-bowls-club",
    name: "Lindfield Bowls Club",
    city: "Lindfield",
    stateCode: "WSX",
    state: "West Sussex",
    country: "GB",
    countryCode: "GB",
    province: "West Sussex",
    region: "south_east",
    address: "Lindfield, West Sussex",
    lat: 51.0105,
    lng: -0.0896,
    website: "https://www.lindfieldbowlsclub.co.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 100,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse", "bar", "changing_rooms"],
    founded: undefined,
    description:
      "Competes in five leagues. Six-rink bowling green, fully-stocked bar, three changing rooms.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["west_sussex", "five_leagues", "bar"],
    contacts: [],
  },

  {
    id: "clevedon-bowling-club",
    name: "Clevedon Bowling Club",
    city: "Clevedon",
    stateCode: "SOM",
    state: "Somerset",
    country: "GB",
    countryCode: "GB",
    province: "Somerset",
    region: "south_west",
    address: "Chapel Hill, Clevedon, BS21 7LL",
    lat: 51.4384,
    lng: -2.8544,
    website: "https://www.clevedonbowlingclub.co.uk/",
    phone: "01275 872828",
    email: "secretary@clevedonbowlingclub.co.uk",
    memberCount: 80,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Active bowling club in Clevedon, Somerset.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["somerset", "clevedon"],
    contacts: [
      {
        name: "Naomi Stride",
        role: "Secretary",
        email: "secretary@clevedonbowlingclub.co.uk",
        phone: "01275 872828",
      },
    ],
  },

  {
    id: "taunton-bowling-club",
    name: "Taunton Bowling Club",
    city: "Taunton",
    stateCode: "SOM",
    state: "Somerset",
    country: "GB",
    countryCode: "GB",
    province: "Somerset",
    region: "south_west",
    address: "Vivary Park, Taunton",
    lat: 51.0145,
    lng: -3.1075,
    website: "https://www.tauntonbowlingclub.co.uk/",
    phone: "01823 253899",
    email: "dmytbc@tiscali.co.uk",
    memberCount: 100,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Bowling club located in Vivary Park, Taunton, Somerset.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["somerset", "taunton", "park_setting"],
    contacts: [],
  },

  {
    id: "city-of-birmingham-indoor-bowls-club",
    name: "City of Birmingham Indoor Bowls Club",
    city: "Birmingham",
    stateCode: "WMD",
    state: "West Midlands",
    country: "GB",
    countryCode: "GB",
    province: "West Midlands",
    region: "midlands",
    address: "Billesley Common, Yardley Wood Road, Birmingham, B13 0HN",
    lat: 52.4316,
    lng: -1.8600,
    website: "https://cityofbirminghamindoorbowlsclub.com/",
    phone: "0121 444 8325",
    email: "info@cityofbirminghamindoorbowlsclub.com",
    memberCount: 300,
    greens: 1,
    rinks: 6,
    surfaceType: "synthetic",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "indoor_bowls"],
    facilities: ["clubhouse", "bar", "indoor_rinks", "changing_rooms", "car_park"],
    founded: undefined,
    description:
      "6 indoor rinks. Major urban indoor bowls centre in Birmingham.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["indoor", "birmingham", "urban", "west_midlands"],
    contacts: [],
  },

  {
    id: "erdington-court-indoor-bowls-club",
    name: "Erdington Court Indoor Bowls Club",
    city: "Erdington",
    stateCode: "WMD",
    state: "West Midlands",
    country: "GB",
    countryCode: "GB",
    province: "West Midlands",
    region: "midlands",
    address: "Bowling Green Close, Erdington, Birmingham, B23 5QU",
    lat: 52.5227,
    lng: -1.8381,
    website: "https://erdingtoncourtbowlsclub.org.uk/",
    phone: "0121 308 2508",
    email: "erdcourtbc@btconnect.com",
    memberCount: 200,
    greens: 1,
    rinks: 6,
    surfaceType: "synthetic",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "indoor_bowls"],
    facilities: ["clubhouse", "indoor_rinks", "changing_rooms", "car_park"],
    founded: undefined,
    description: "Indoor bowls club in Erdington, Birmingham.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["indoor", "birmingham", "erdington"],
    contacts: [],
  },

  {
    id: "gosforth-bowling-club",
    name: "Gosforth Bowling Club",
    city: "Newcastle upon Tyne",
    stateCode: "TWR",
    state: "Tyne and Wear",
    country: "GB",
    countryCode: "GB",
    province: "Tyne and Wear",
    region: "north_east",
    address: "Gosforth, Newcastle upon Tyne",
    lat: 55.0006,
    lng: -1.6145,
    website: "https://www.gosforthbowlingclub.org/",
    phone: undefined,
    email: undefined,
    memberCount: 100,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Prominent North East bowls club in Gosforth, Newcastle upon Tyne.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["north_east", "newcastle", "gosforth"],
    contacts: [],
  },

  {
    id: "chester-le-street-bowling-club",
    name: "Chester-le-Street Bowling Club",
    city: "Chester-le-Street",
    stateCode: "DUR",
    state: "County Durham",
    country: "GB",
    countryCode: "GB",
    province: "County Durham",
    region: "north_east",
    address: "Riverside Park, Chester-le-Street, County Durham",
    lat: 54.8579,
    lng: -1.5726,
    website: "https://www.clsbowling.club/",
    phone: undefined,
    email: undefined,
    memberCount: 80,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description:
      "Located in Riverside Park with backdrop of Lumley Castle. Scenic setting by River Wear.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["county_durham", "scenic", "riverside", "lumley_castle"],
    contacts: [],
  },

  {
    id: "amersham-bowls-club",
    name: "Amersham Bowls Club",
    city: "Amersham",
    stateCode: "BKM",
    state: "Buckinghamshire",
    country: "GB",
    countryCode: "GB",
    province: "Buckinghamshire",
    region: "south_east",
    address: "Amersham, Buckinghamshire",
    lat: 51.6740,
    lng: -0.6073,
    website: "https://www.amershambowlsclub.org.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 80,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Bowls club in Amersham, Buckinghamshire.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["buckinghamshire", "amersham"],
    contacts: [],
  },

  {
    id: "holsworthy-bowling-club",
    name: "Holsworthy Bowling Club",
    city: "Holsworthy",
    stateCode: "DEV",
    state: "Devon",
    country: "GB",
    countryCode: "GB",
    province: "Devon",
    region: "south_west",
    address: "Holsworthy, Devon",
    lat: 50.8115,
    lng: -4.3533,
    website: "https://www.holsworthybowlingclub.co.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 60,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "short_mat_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description:
      "Six outdoor rinks plus two short mats for winter. Affiliated to Bowls Devon and Bowls England.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["devon", "short_mat", "winter_play"],
    contacts: [],
  },

  {
    id: "east-dorset-indoor-bowls-club",
    name: "East Dorset Indoor Bowls Club",
    city: "Wimborne",
    stateCode: "DOR",
    state: "Dorset",
    country: "GB",
    countryCode: "GB",
    province: "Dorset",
    region: "south_west",
    address: "Wimborne, Dorset",
    lat: 50.7972,
    lng: -1.9862,
    website: "https://eastdorsetibc.org.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 300,
    greens: 1,
    rinks: 6,
    surfaceType: "synthetic",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "indoor_bowls"],
    facilities: ["clubhouse", "indoor_rinks", "car_park"],
    founded: undefined,
    description: "Major indoor bowls facility in Dorset.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["indoor", "dorset", "wimborne"],
    contacts: [],
  },

  {
    id: "bristol-indoor-bowls-club",
    name: "Bristol Indoor Bowls Club",
    city: "Bristol",
    stateCode: "BRS",
    state: "Bristol",
    country: "GB",
    countryCode: "GB",
    province: "Bristol",
    region: "south_west",
    address: "Bristol",
    lat: 51.4545,
    lng: -2.5879,
    website: "https://www.bristolindoorbowls.org.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 400,
    greens: 1,
    rinks: 8,
    surfaceType: "synthetic",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "indoor_bowls"],
    facilities: ["clubhouse", "bar", "indoor_rinks", "changing_rooms", "car_park"],
    founded: undefined,
    description: "Major city indoor bowls centre in Bristol.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["indoor", "bristol", "city_centre"],
    contacts: [],
  },

  {
    id: "hallamshire-proprietary-bowling-club",
    name: "Hallamshire Proprietary Bowling Club",
    city: "Sheffield",
    stateCode: "SYK",
    state: "South Yorkshire",
    country: "GB",
    countryCode: "GB",
    province: "South Yorkshire",
    region: "north_east",
    address: "Sheffield, South Yorkshire",
    lat: 53.3811,
    lng: -1.4701,
    website: undefined,
    phone: undefined,
    email: undefined,
    memberCount: 60,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["crown_green_bowls", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: 1863,
    description:
      "Oldest crown green bowls club in Sheffield. Members-only.",
    status: "active",
    hasOnlinePresence: false,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["crown_green", "historic", "sheffield", "members_only"],
    contacts: [],
  },

  {
    id: "worthing-bowls-club",
    name: "Worthing Bowls Club",
    city: "Worthing",
    stateCode: "WSX",
    state: "West Sussex",
    country: "GB",
    countryCode: "GB",
    province: "West Sussex",
    region: "south_east",
    address: "Worthing, West Sussex",
    lat: 50.8135,
    lng: -0.3724,
    website: "https://worthingbowlsclub.com/",
    phone: undefined,
    email: undefined,
    memberCount: 100,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Bowling club in Worthing, West Sussex.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["west_sussex", "worthing"],
    contacts: [],
  },

  {
    id: "ilford-district-indoor-bowls-club",
    name: "Ilford & District Indoor Bowls Club",
    city: "Ilford",
    stateCode: "ESS",
    state: "Essex",
    country: "GB",
    countryCode: "GB",
    province: "Essex",
    region: "east",
    address: "Ilford, Essex",
    lat: 51.5590,
    lng: 0.0741,
    website: "https://iibc.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 300,
    greens: 1,
    rinks: 6,
    surfaceType: "synthetic",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "indoor_bowls"],
    facilities: ["clubhouse", "indoor_rinks"],
    founded: undefined,
    description: "Indoor bowls club in Ilford, Essex.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["indoor", "essex", "ilford"],
    contacts: [],
  },

  {
    id: "clevedon-promenade-bowls-club",
    name: "Clevedon Promenade Bowls Club",
    city: "Clevedon",
    stateCode: "SOM",
    state: "Somerset",
    country: "GB",
    countryCode: "GB",
    province: "Somerset",
    region: "south_west",
    address: "Clevedon, Somerset",
    lat: 51.4398,
    lng: -2.8560,
    website: "https://www.clevedonprom.org.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 80,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Bowling club on the promenade in Clevedon, Somerset.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["somerset", "clevedon", "promenade", "seaside"],
    contacts: [],
  },

  {
    id: "kings-bowling-club",
    name: "Kings Bowling Club",
    city: "Torquay",
    stateCode: "DEV",
    state: "Devon",
    country: "GB",
    countryCode: "GB",
    province: "Devon",
    region: "south_west",
    address: "Torquay, Devon",
    lat: 50.4619,
    lng: -3.5253,
    website: "http://www.kingsbowling.org.uk/",
    phone: "01803 369494",
    email: "Kingsbc.secretary@gmail.com",
    memberCount: 80,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Bowling club in Torquay, Devon.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["devon", "torquay", "seaside"],
    contacts: [
      {
        name: "Ian Baker",
        role: "Secretary",
        email: "Kingsbc.secretary@gmail.com",
        phone: "01803 369494",
      },
    ],
  },

  {
    id: "bradway-bowling-snooker-club",
    name: "Bradway Bowling & Snooker Club",
    city: "Sheffield",
    stateCode: "SYK",
    state: "South Yorkshire",
    country: "GB",
    countryCode: "GB",
    province: "South Yorkshire",
    region: "north_east",
    address: "Sheffield, South Yorkshire",
    lat: 53.3281,
    lng: -1.5230,
    website: "https://bradwaybowling.org.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 60,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["crown_green_bowls", "snooker", "social"],
    facilities: ["clubhouse", "snooker_room"],
    founded: undefined,
    description:
      "Crown green bowling and snooker in southwest Sheffield.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["crown_green", "snooker", "sheffield", "multi_sport"],
    contacts: [],
  },

  {
    id: "abington-bowling-club",
    name: "Abington Bowling Club",
    city: "Northampton",
    stateCode: "NHA",
    state: "Northamptonshire",
    country: "GB",
    countryCode: "GB",
    province: "Northamptonshire",
    region: "midlands",
    address: "Northampton, Northamptonshire",
    lat: 52.2445,
    lng: -0.8770,
    website: "https://www.abingtonbowling.com/",
    phone: undefined,
    email: undefined,
    memberCount: 80,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Bowling club in Northampton, Northamptonshire.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["northamptonshire", "northampton"],
    contacts: [],
  },

  // ─── SCOTLAND — Top 15 Clubs ──────────────────────────────────────────

  {
    id: "kelvingrove-lawn-bowls-tennis-centre",
    name: "Kelvingrove Lawn Bowls & Tennis Centre",
    city: "Glasgow",
    stateCode: "GLA",
    state: "Glasgow",
    country: "GB",
    countryCode: "GB",
    province: "Glasgow",
    region: "scotland",
    address: "Kelvingrove Park, Glasgow",
    lat: 55.8688,
    lng: -4.2882,
    website: "https://www.glasgowlife.org.uk/sport/venues/kelvingrove-lawn-bowls-and-tennis-centre",
    phone: undefined,
    email: undefined,
    memberCount: 200,
    greens: 2,
    rinks: 8,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "coaching", "public_access"],
    facilities: ["clubhouse", "changing_rooms", "car_park", "public_facility"],
    founded: undefined,
    description:
      "Hosted 2014 Commonwealth Games bowls. Located in Kelvingrove Park, next to Kelvingrove Art Gallery. Premier public bowls facility in Scotland.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "glasgow", "commonwealth_games", "public", "premier_venue"],
    contacts: [],
  },

  {
    id: "edinburgh-west-end-bowling-club",
    name: "Edinburgh West End Bowling Club",
    city: "Edinburgh",
    stateCode: "EDN",
    state: "Edinburgh",
    country: "GB",
    countryCode: "GB",
    province: "Edinburgh",
    region: "scotland",
    address: "Edinburgh, Scotland",
    lat: 55.9461,
    lng: -3.2150,
    website: undefined,
    phone: undefined,
    email: undefined,
    memberCount: 80,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "coaching"],
    facilities: ["clubhouse", "bar", "lounge"],
    founded: 1864,
    description:
      "One of the oldest clubs in Scotland. Provides training for new members. Lounge area and bar facilities.",
    status: "active",
    hasOnlinePresence: false,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "edinburgh", "historic", "coaching"],
    contacts: [],
  },

  {
    id: "victoria-park-bowling-club-glasgow",
    name: "Victoria Park Bowling Club",
    city: "Glasgow",
    stateCode: "GLA",
    state: "Glasgow",
    country: "GB",
    countryCode: "GB",
    province: "Glasgow",
    region: "scotland",
    address: "Victoria Park, Glasgow",
    lat: 55.8793,
    lng: -4.3340,
    website: "https://www.victoriaparkbowlingclubglasgow.com/",
    phone: undefined,
    email: undefined,
    memberCount: 80,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: 1903,
    description:
      "Historic Glasgow club with strong community presence. Founded in 1903.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "glasgow", "historic", "community"],
    contacts: [],
  },

  {
    id: "willow-bank-bowling-club",
    name: "Willow Bank Bowling Club",
    city: "Glasgow",
    stateCode: "GLA",
    state: "Glasgow",
    country: "GB",
    countryCode: "GB",
    province: "Glasgow",
    region: "scotland",
    address: "Glasgow, Scotland",
    lat: 55.8642,
    lng: -4.2518,
    website: undefined,
    phone: undefined,
    email: undefined,
    memberCount: 60,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description:
      "Glasgow's oldest bowling club. Offers reduced membership for first-year new bowlers.",
    status: "active",
    hasOnlinePresence: false,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "glasgow", "oldest_in_glasgow", "beginner_friendly"],
    contacts: [],
  },

  {
    id: "cathcart-bowling-club",
    name: "Cathcart Bowling Club",
    city: "Glasgow",
    stateCode: "GLA",
    state: "Glasgow",
    country: "GB",
    countryCode: "GB",
    province: "Glasgow",
    region: "scotland",
    address: "Cathcart & Merrylee, Glasgow",
    lat: 55.8187,
    lng: -4.2795,
    website: "https://cathcartbowlingclub.co.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 60,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Bowling club in Cathcart & Merrylee area of Glasgow.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "glasgow", "cathcart"],
    contacts: [],
  },

  {
    id: "aberdeen-indoor-bowling-club",
    name: "Aberdeen Indoor Bowling Club",
    city: "Aberdeen",
    stateCode: "ABD",
    state: "Aberdeenshire",
    country: "GB",
    countryCode: "GB",
    province: "Aberdeenshire",
    region: "scotland",
    address: "Aberdeen, Scotland",
    lat: 57.1497,
    lng: -2.0943,
    website: "https://www.aberdeenindoor.com/",
    phone: undefined,
    email: undefined,
    memberCount: 1000,
    greens: 1,
    rinks: 8,
    surfaceType: "synthetic",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "indoor_bowls"],
    facilities: ["clubhouse", "bar", "indoor_rinks", "changing_rooms", "car_park"],
    founded: undefined,
    description:
      "Claims to be the largest indoor bowling club in Europe.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "aberdeen", "indoor", "largest_in_europe"],
    contacts: [],
  },

  {
    id: "dundee-indoor-bowling-club",
    name: "Dundee Indoor Bowling Club",
    city: "Dundee",
    stateCode: "DND",
    state: "Dundee",
    country: "GB",
    countryCode: "GB",
    province: "Dundee",
    region: "scotland",
    address: "15 Miln Street, Dundee, DD1 5BZ",
    lat: 56.4620,
    lng: -2.9707,
    website: "http://www.dundeeindoorbowling.co.uk/",
    phone: "01382 225232",
    email: undefined,
    memberCount: 300,
    greens: 1,
    rinks: 6,
    surfaceType: "synthetic",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "indoor_bowls"],
    facilities: ["clubhouse", "indoor_rinks"],
    founded: undefined,
    description: "Indoor bowling club in Dundee, Scotland.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "dundee", "indoor"],
    contacts: [
      {
        name: "Mrs Lynda McMullan",
        role: "Manager",
        phone: "01382 225232",
      },
    ],
  },

  {
    id: "whiteinch-indoor-bowling-club",
    name: "Whiteinch Indoor Bowling Club",
    city: "Glasgow",
    stateCode: "GLA",
    state: "Glasgow",
    country: "GB",
    countryCode: "GB",
    province: "Glasgow",
    region: "scotland",
    address: "30 Ferryden Street, Whiteinch, Glasgow, G14 0SW",
    lat: 55.8726,
    lng: -4.3390,
    website: "https://whiteinchibc.co.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 200,
    greens: 1,
    rinks: 6,
    surfaceType: "synthetic",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls", "indoor_bowls"],
    facilities: ["clubhouse", "indoor_rinks"],
    founded: undefined,
    description: "Indoor bowling club in Whiteinch, Glasgow.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "glasgow", "indoor", "whiteinch"],
    contacts: [],
  },

  {
    id: "burnbank-bowling-club",
    name: "Burnbank Bowling Club",
    city: "Glasgow",
    stateCode: "GLA",
    state: "Glasgow",
    country: "GB",
    countryCode: "GB",
    province: "Glasgow",
    region: "scotland",
    address: "Glasgow, Scotland",
    lat: 55.8580,
    lng: -4.2710,
    website: undefined,
    phone: undefined,
    email: undefined,
    memberCount: 50,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description:
      "One of the oldest bowling clubs in Glasgow. Located just west of the city centre.",
    status: "active",
    hasOnlinePresence: false,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "glasgow", "historic"],
    contacts: [],
  },

  {
    id: "mosspark-bowling-club",
    name: "Mosspark Bowling Club",
    city: "Glasgow",
    stateCode: "GLA",
    state: "Glasgow",
    country: "GB",
    countryCode: "GB",
    province: "Glasgow",
    region: "scotland",
    address: "Mosspark, Glasgow",
    lat: 55.8350,
    lng: -4.3350,
    website: undefined,
    phone: undefined,
    email: undefined,
    memberCount: 50,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Bowling club in Mosspark, South West Glasgow.",
    status: "active",
    hasOnlinePresence: false,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "glasgow", "mosspark"],
    contacts: [],
  },

  {
    id: "mount-vernon-bowling-club",
    name: "Mount Vernon Bowling Club",
    city: "Glasgow",
    stateCode: "GLA",
    state: "Glasgow",
    country: "GB",
    countryCode: "GB",
    province: "Glasgow",
    region: "scotland",
    address: "Mount Vernon, Glasgow",
    lat: 55.8400,
    lng: -4.1470,
    website: undefined,
    phone: undefined,
    email: undefined,
    memberCount: 50,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Bowling club in Glasgow's East End.",
    status: "active",
    hasOnlinePresence: false,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "glasgow", "east_end"],
    contacts: [],
  },

  {
    id: "croftfoot-bowling-club",
    name: "Croftfoot Bowling Club",
    city: "Glasgow",
    stateCode: "GLA",
    state: "Glasgow",
    country: "GB",
    countryCode: "GB",
    province: "Glasgow",
    region: "scotland",
    address: "Croftfoot, Glasgow",
    lat: 55.8150,
    lng: -4.2400,
    website: undefined,
    phone: undefined,
    email: undefined,
    memberCount: 50,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Bowling club in Glasgow's Southside.",
    status: "active",
    hasOnlinePresence: false,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "glasgow", "southside"],
    contacts: [],
  },

  {
    id: "inverurie-bowling-club",
    name: "Inverurie Bowling Club",
    city: "Inverurie",
    stateCode: "ABD",
    state: "Aberdeenshire",
    country: "GB",
    countryCode: "GB",
    province: "Aberdeenshire",
    region: "scotland",
    address: "Inverurie, Aberdeenshire",
    lat: 57.2866,
    lng: -2.3732,
    website: "https://www.inveruriebowlingclub.com/",
    phone: undefined,
    email: undefined,
    memberCount: 60,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Bowling club in Inverurie, Aberdeenshire.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "aberdeenshire", "inverurie"],
    contacts: [],
  },

  {
    id: "prestwick-howie-bowling-club",
    name: "Prestwick Howie Bowling Club",
    city: "Prestwick",
    stateCode: "AYR",
    state: "Ayrshire",
    country: "GB",
    countryCode: "GB",
    province: "Ayrshire",
    region: "scotland",
    address: "Prestwick, Ayrshire",
    lat: 55.4957,
    lng: -4.6127,
    website: "https://prestwickhowiebowlingclub.co.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 60,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "competitions", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Bowling club in Prestwick, Ayrshire.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "ayrshire", "prestwick"],
    contacts: [],
  },

  {
    id: "glencarse-bowling-club",
    name: "Glencarse Bowling Club",
    city: "Glencarse",
    stateCode: "PER",
    state: "Perthshire",
    country: "GB",
    countryCode: "GB",
    province: "Perthshire",
    region: "scotland",
    address: "Glencarse, Perthshire",
    lat: 56.3893,
    lng: -3.2685,
    website: "https://glencarsebowlingclub.co.uk/",
    phone: undefined,
    email: undefined,
    memberCount: 50,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    division: undefined,
    activities: ["leagues", "social_bowls"],
    facilities: ["clubhouse"],
    founded: undefined,
    description: "Bowling club in Glencarse, Perthshire.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: undefined,
    instagramUrl: undefined,
    tags: ["scotland", "perthshire", "glencarse"],
    contacts: [],
  },
];

// Region labels for display
export const UK_REGION_LABELS: Record<UKRegion, string> = {
  south_east: "South East England",
  south_west: "South West England",
  london: "London",
  midlands: "Midlands",
  north_east: "North East England",
  north_west: "North West England",
  east: "East England",
  scotland: "Scotland",
};
