// Canadian lawn bowling club data
// Extracted from .planning/research/GLOBAL_CANADA_BOWLS.md
// 30 top clubs (15 BC, 15 Ontario) + governing body contacts

import type { ClubData, ClubContact, CountryCode } from "./clubs-data";

// ---------------------------------------------------------------------------
// Province lookup
// ---------------------------------------------------------------------------
export type CARegion = "west" | "prairies" | "central" | "atlantic";

export const CA_PROVINCES: Record<
  string,
  { name: string; code: string; region: CARegion }
> = {
  BC: { name: "British Columbia", code: "BC", region: "west" },
  AB: { name: "Alberta", code: "AB", region: "prairies" },
  SK: { name: "Saskatchewan", code: "SK", region: "prairies" },
  MB: { name: "Manitoba", code: "MB", region: "prairies" },
  ON: { name: "Ontario", code: "ON", region: "central" },
  QC: { name: "Quebec", code: "QC", region: "central" },
  NB: { name: "New Brunswick", code: "NB", region: "atlantic" },
  NS: { name: "Nova Scotia", code: "NS", region: "atlantic" },
  PE: { name: "Prince Edward Island", code: "PE", region: "atlantic" },
  NL: { name: "Newfoundland and Labrador", code: "NL", region: "atlantic" },
};

// ---------------------------------------------------------------------------
// Governing Bodies
// ---------------------------------------------------------------------------
export interface GoverningBody {
  name: string;
  abbreviation?: string;
  level: "national" | "provincial" | "sub-provincial";
  province?: string;
  website?: string;
  email?: string;
  phone?: string;
  tollFree?: string;
  address?: string;
  facebookUrl?: string;
  contacts: ClubContact[];
  clubCount?: number;
  memberCount?: number;
  notes?: string;
}

export const CANADA_GOVERNING_BODIES: GoverningBody[] = [
  // ── National ──────────────────────────────────────────────────────────
  {
    name: "Bowls Canada Boulingrin",
    abbreviation: "BCB",
    level: "national",
    website: "https://bowlscanada.com",
    email: "office@bowlscanada.com",
    phone: "613-244-0021",
    tollFree: "1-800-567-2695",
    address: "2451 Riverside Drive, c/o House of Sport, Ottawa, Ontario K1H 7X7",
    clubCount: 270,
    memberCount: 18000,
    contacts: [
      { name: "Britany Gordon", role: "Chief Executive Officer", email: "britany@bowlscanada.com" },
      { name: "Samantha Burelle", role: "Program Manager", email: "samantha@bowlscanada.com" },
      { name: "William Mulcahy", role: "Technical Manager", email: "william@bowlscanada.com" },
      { name: "Derek Dillon", role: "Head Coach", email: "derek@bowlscanada.com" },
      { name: "Bridget Masterson", role: "Events/Marketing Intern", email: "bridget@bowlscanada.com" },
      { name: "Anne Mathewson", role: "Board Chair", email: "anne.mathewson@bowlscanada.com" },
      { name: "Dennis Verge", role: "Treasurer", email: "dennis.verge@bowlscanada.com" },
      { name: "Derek McKie", role: "Secretary", email: "derek.mckie@bowlscanada.com" },
      { name: "Laura Seed", role: "Director", email: "laura.seed@bowlscanada.com" },
      { name: "Phillip Francis", role: "Director", email: "phillip.francis@bowlscanada.com" },
      { name: "Jane Blaine", role: "Director", email: "jane.blaine@bowlscanada.com" },
    ],
  },

  // ── Provincial: British Columbia ──────────────────────────────────────
  {
    name: "Bowls British Columbia",
    abbreviation: "Bowls BC",
    level: "provincial",
    province: "British Columbia",
    website: "http://bowlsbc.com",
    clubCount: 49,
    contacts: [
      { name: "Harry Carruthers", role: "President", email: "president@bowlsbc.com", phone: "604-985-2241" },
      { name: "Sharon Cowie", role: "Vice President", email: "vice.president@bowlsbc.com", phone: "604-565-0199" },
      { name: "Vicki Parton", role: "Secretary", phone: "604-908-4048" },
      { name: "Lynn Chwartacki", role: "Director of Admin", email: "lynn.chwartacki@bowlsbc.com", phone: "250-752-0851" },
    ],
    notes: "49 clubs across 6 districts. Sub-associations: Vancouver & District Bowls Association (V&DBA, 22 clubs, 2,300+ bowlers), Bowls South Island (11 clubs).",
  },

  // ── Provincial: Ontario ───────────────────────────────────────────────
  {
    name: "Ontario Lawn Bowls Association",
    abbreviation: "OLBA",
    level: "provincial",
    province: "Ontario",
    website: "https://www.olba.ca",
    clubCount: 115,
    contacts: [
      { name: "Kevin Goheen", role: "Executive Director" },
    ],
    notes: "Largest province by club count. 115+ clubs across 16 districts.",
  },

  // ── Provincial: Alberta ───────────────────────────────────────────────
  {
    name: "Bowls Alberta",
    level: "provincial",
    province: "Alberta",
    website: "https://www.bowlsalberta.com",
    email: "bowlsalberta@gmail.com",
    clubCount: 11,
    contacts: [
      { name: "Claire Day", role: "President" },
      { name: "Josh Cameron", role: "Vice President" },
      { name: "Joy White", role: "Secretary" },
      { name: "Scott Kramble", role: "Executive Director" },
    ],
    notes: "Youth Development Program launched 2021.",
  },

  // ── Provincial: Saskatchewan ──────────────────────────────────────────
  {
    name: "Bowls Saskatchewan",
    level: "provincial",
    province: "Saskatchewan",
    website: "https://bowlssask.ca",
    clubCount: 7,
    contacts: [
      { name: "Doug Normand", role: "President" },
    ],
  },

  // ── Provincial: Manitoba ──────────────────────────────────────────────
  {
    name: "Bowls Manitoba",
    level: "provincial",
    province: "Manitoba",
    website: "https://bowlsmb.wordpress.com",
    address: "1212 Dakota Street, Winnipeg, MB",
    clubCount: 8,
    contacts: [],
  },

  // ── Provincial: Quebec ────────────────────────────────────────────────
  {
    name: "Quebec Lawn Bowling Federation",
    level: "provincial",
    province: "Quebec",
    clubCount: 5,
    contacts: [],
    notes: "Clubs concentrated in Montreal West Island. Also known as Federation de Boulingrin du Quebec.",
  },

  // ── Provincial: Nova Scotia ───────────────────────────────────────────
  {
    name: "Lawn Bowls Nova Scotia",
    level: "provincial",
    province: "Nova Scotia",
    website: "https://www.lawnbowlsnovascotia.com",
    facebookUrl: "https://facebook.com/LawnBowlsNS",
    clubCount: 6,
    contacts: [],
  },

  // ── Provincial: New Brunswick ─────────────────────────────────────────
  {
    name: "Bowls New Brunswick",
    level: "provincial",
    province: "New Brunswick",
    clubCount: 3,
    contacts: [],
  },

  // ── Provincial: Newfoundland & Labrador ───────────────────────────────
  {
    name: "Bowls Newfoundland and Labrador",
    level: "provincial",
    province: "Newfoundland and Labrador",
    clubCount: 1,
    contacts: [],
    notes: "1 club: Peter Pan LBC, St. John's.",
  },

  // ── Provincial: Prince Edward Island ──────────────────────────────────
  {
    name: "Bowls Prince Edward Island",
    level: "provincial",
    province: "Prince Edward Island",
    clubCount: 1,
    contacts: [],
    notes: "1 club: Sherwood LBC, Charlottetown.",
  },

  // ── Sub-provincial: V&DBA ─────────────────────────────────────────────
  {
    name: "Vancouver & District Bowls Association",
    abbreviation: "V&DBA",
    level: "sub-provincial",
    province: "British Columbia",
    clubCount: 22,
    memberCount: 2300,
    contacts: [],
    notes: "22 clubs and 2,300+ bowlers in greater Vancouver area.",
  },

  // ── Sub-provincial: Bowls South Island ────────────────────────────────
  {
    name: "Bowls South Island",
    level: "sub-provincial",
    province: "British Columbia",
    clubCount: 11,
    contacts: [],
    notes: "11 clubs on southern Vancouver Island.",
  },
];

// ---------------------------------------------------------------------------
// Top 30 Clubs
// ---------------------------------------------------------------------------
export const CANADA_CLUBS: ClubData[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // BRITISH COLUMBIA — Top 15
  // ═══════════════════════════════════════════════════════════════════════

  {
    id: "stanley-park-lawn-bowling-club",
    name: "Stanley Park Lawn Bowling Club",
    city: "Vancouver",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "2099 Beach Avenue, Vancouver, BC V6G 1Z4",
    lat: 49.2827,
    lng: -123.1350,
    website: "https://www.splbc.com",
    phone: "(604) 683-0910",
    memberCount: 350,
    greens: 2,
    rinks: 16,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues", "tournaments", "learn-to-bowl"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    founded: 1917,
    description:
      "Canada's largest lawn bowling club with approximately 350 members. Founded in 1917, Stanley Park LBC pays $1/year rent to the City of Vancouver. Located on a heritage site near English Bay, the club has experienced massive recent growth driven by younger demographics and LGBTQ+ community engagement.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["heritage", "largest-in-canada", "youth-friendly", "lgbtq-inclusive", "urban", "flagship"],
    contacts: [],
  },

  {
    id: "pacific-indoor-bowls-club",
    name: "Pacific Indoor Bowls Club",
    city: "Vancouver",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "4588 Clancy Loranger Way, Vancouver, BC V5Y 4B6",
    lat: 49.2428,
    lng: -123.1028,
    website: "https://www.pacificindoor.com",
    phone: "(604) 874-2817",
    memberCount: 200,
    surfaceType: "synthetic",
    activities: ["lawn-bowls", "indoor-bowls", "leagues", "coaching", "tournaments", "social-events"],
    facilities: ["indoor-greens", "clubhouse", "parking", "washrooms"],
    founded: 1938,
    description:
      "Year-round indoor facility at the Millennium Sport Centre, founded in 1938. World-class venue that has never had fewer than 200 members. Hosts the Canadian Indoor Singles Championships. Offers leagues, coaching, competitive and social play.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/PacificIndoor",
    tags: ["indoor", "year-round", "world-class", "coaching", "competitive"],
    contacts: [],
  },

  {
    id: "kerrisdale-lawn-bowling-club",
    name: "Kerrisdale Lawn Bowling Club",
    city: "Vancouver",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "5870 Elm Street, Vancouver, BC V6N 2A7",
    lat: 49.2325,
    lng: -123.1560,
    website: "https://www.krlbc.com",
    phone: "(604) 261-1116",
    email: "kerrisdalelbc@gmail.com",
    memberCount: 125,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Established Vancouver lawn bowling club in the Kerrisdale neighbourhood with an active Facebook presence.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["urban", "community"],
    contacts: [],
  },

  {
    id: "vancouver-lawn-bowling-club",
    name: "Vancouver Lawn Bowling Club",
    city: "Vancouver",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "411-2101 McMullen Avenue, Vancouver, BC V6L 3B4",
    lat: 49.2500,
    lng: -123.1000,
    website: "https://www.vanlawnbowling.ca",
    phone: "(604) 879-8916",
    memberCount: 100,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    founded: 1912,
    description: "Founded in 1912, the oldest lawn bowling club in Vancouver. A historic institution in the city's sporting landscape.",
    status: "active",
    hasOnlinePresence: true,
    instagramUrl: "https://instagram.com/vancouverlawnbowling",
    tags: ["heritage", "oldest-in-vancouver", "historic"],
    contacts: [],
  },

  {
    id: "dunbar-lawn-bowling-club",
    name: "Dunbar Lawn Bowling Club",
    city: "Vancouver",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "3850 W 31 Avenue, Vancouver, BC V6S 1Y3",
    lat: 49.2430,
    lng: -123.1870,
    website: "https://www.dunbarlawnbowling.com",
    phone: "(604) 228-8428",
    email: "dunbarbowling@gmail.com",
    memberCount: 100,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "croquet", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Vancouver lawn bowling club in the Dunbar neighbourhood. Also offers croquet alongside bowls.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["croquet", "multi-sport", "community"],
    contacts: [],
  },

  {
    id: "granville-park-lawn-bowling-club",
    name: "Granville Park Lawn Bowling Club",
    city: "Vancouver",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "3025 Fir Street, Vancouver, BC V6J 3C5",
    lat: 49.2617,
    lng: -123.1400,
    website: "https://www.gplbc.com",
    phone: "(604) 731-8422",
    email: "granvilleparklbclub@gmail.com",
    memberCount: 90,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Community lawn bowling club in Vancouver's South Granville neighbourhood.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["community", "urban"],
    contacts: [],
  },

  {
    id: "north-vancouver-lawn-bowling-club",
    name: "North Vancouver Lawn Bowling Club",
    city: "North Vancouver",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "249 East 24th Street, North Vancouver, BC V7L 0H9",
    lat: 49.3200,
    lng: -123.0700,
    website: "https://www.nvlbc.com",
    phone: "(604) 985-2321",
    memberCount: 80,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Active lawn bowling club on the North Shore with a growing social media presence.",
    status: "active",
    hasOnlinePresence: true,
    instagramUrl: "https://instagram.com/nvlbc.insta",
    tags: ["community", "north-shore"],
    contacts: [],
  },

  {
    id: "burnside-lawn-bowling-club",
    name: "Burnside Lawn Bowling Club",
    city: "Victoria",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "274 Hampton Road, Victoria, BC V8Z 1H1",
    lat: 48.4520,
    lng: -123.3620,
    website: "https://www.burnsidelbc.ca",
    phone: "(250) 381-5743",
    memberCount: 100,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "tournaments", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "One of the largest lawn bowling clubs on Vancouver Island. Active tournament host.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/technoglent",
    tags: ["vancouver-island", "tournament-host", "competitive"],
    contacts: [],
  },

  {
    id: "oak-bay-lawn-bowling-club",
    name: "Oak Bay Lawn Bowling Club",
    city: "Victoria",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "2190 Harlow Drive, Victoria, BC V8R 3J1",
    lat: 48.4424,
    lng: -123.3178,
    website: "https://bowlsoakbay.ca",
    phone: "(250) 592-1823",
    memberCount: 80,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Victoria-area club and member of the Bowls South Island association (11 clubs).",
    status: "active",
    hasOnlinePresence: true,
    tags: ["vancouver-island", "bowls-south-island"],
    contacts: [],
  },

  {
    id: "victoria-bowls-and-croquet-club",
    name: "Victoria Bowls and Croquet Club",
    city: "Victoria",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "100 Cook St, Victoria, BC V8V 4Z8",
    lat: 48.4137,
    lng: -123.3620,
    website: "https://www.victorialbc.com",
    phone: "(250) 383-5851",
    memberCount: 80,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "croquet", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Historic Victoria club offering both lawn bowls and croquet.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["historic", "croquet", "multi-sport", "vancouver-island"],
    contacts: [],
  },

  {
    id: "west-vancouver-lawn-bowling-club",
    name: "West Vancouver Lawn Bowling Club",
    city: "West Vancouver",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "650-20th Street, West Vancouver, BC V7V 3Y4",
    lat: 49.3270,
    lng: -123.1600,
    website: "https://www.westvanlbc.ca",
    phone: "(604) 922-0411",
    memberCount: 70,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Community lawn bowling club in West Vancouver.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["community", "north-shore"],
    contacts: [],
  },

  {
    id: "mann-park-lawn-bowling-club",
    name: "Mann Park Lawn Bowling Club",
    city: "White Rock",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "14560 North Bluff Rd, White Rock, BC V4B 3C9",
    lat: 49.0230,
    lng: -122.7970,
    website: "https://mannparklbc.org",
    phone: "(604) 531-0833",
    memberCount: 70,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Lawn bowling club located in White Rock, south of Vancouver.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["community", "suburban"],
    contacts: [],
  },

  {
    id: "kelowna-lawn-bowling-club",
    name: "Kelowna Lawn Bowling Club",
    city: "Kelowna",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "1600 Abbott Street, Kelowna, BC V1Y 9N8",
    lat: 49.8863,
    lng: -119.4966,
    website: "https://kelownalawnbowlingclub.com",
    phone: "(250) 317-9505",
    memberCount: 65,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Okanagan-region lawn bowling club in Kelowna.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["okanagan", "community"],
    contacts: [],
  },

  {
    id: "canadian-pacific-lawn-bowling-club",
    name: "Canadian Pacific Lawn Bowling Club",
    city: "Victoria",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "720 Belleville Street, Victoria, BC V8W 1A3",
    lat: 48.4194,
    lng: -123.3709,
    website: "https://downtownlawnbowling.ca",
    phone: "(250) 385-3577",
    memberCount: 65,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Downtown Victoria lawn bowling club near the Inner Harbour. Prime tourist-area location.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["downtown", "tourist-area", "vancouver-island"],
    contacts: [],
  },

  {
    id: "coquitlam-lawn-bowling-club",
    name: "Coquitlam Lawn Bowling Club",
    city: "Coquitlam",
    stateCode: "BC",
    state: "British Columbia",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "British Columbia",
    region: "west",
    address: "1655 Winslow Ave., Coquitlam, BC V3J 0E7",
    lat: 49.2762,
    lng: -122.7900,
    website: "https://coquitlamlawnbowls.club",
    phone: "(604) 931-6711",
    memberCount: 60,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Community lawn bowling club in the Tri-Cities area east of Vancouver.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["community", "tri-cities", "suburban"],
    contacts: [],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // ONTARIO — Top 15
  // ═══════════════════════════════════════════════════════════════════════

  {
    id: "kew-beach-lawn-bowling-club",
    name: "Kew Beach Lawn Bowling Club",
    city: "Toronto",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "12 Lee Avenue, Toronto, ON M4E 2N9",
    lat: 43.6710,
    lng: -79.2940,
    website: "https://kewbeachlbc.ca",
    phone: "(416) 694-4371",
    memberCount: 125,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues", "tournaments"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "One of Toronto's most popular lawn bowling clubs with a prime beachfront location in The Beaches neighbourhood.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["beachfront", "popular", "urban", "toronto"],
    contacts: [],
  },

  {
    id: "lawrence-park-lawn-bowling-croquet-club",
    name: "Lawrence Park Lawn Bowling & Croquet Club",
    city: "Toronto",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "61 Alexander Muir Rd E, Toronto, ON M4N 0A3",
    lat: 43.7230,
    lng: -79.4050,
    website: "https://lawrenceparkclub.ca",
    phone: "(647) 988-4734",
    memberCount: 100,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "croquet", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "The only lawn bowling green sharing field with croquet in the Toronto area. Situated in the scenic Alexander Muir Gardens Ravine.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["croquet", "multi-sport", "ravine-setting", "toronto"],
    contacts: [],
  },

  {
    id: "leaside-lawn-bowling-club",
    name: "Leaside Lawn Bowling Club",
    city: "Toronto",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "1900 Hanna Road, Toronto, ON M4G 4G8",
    lat: 43.7070,
    lng: -79.3610,
    website: "https://www.leasidebowls.ca",
    phone: "(416) 483-1418",
    memberCount: 90,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Active Toronto lawn bowling club in the Leaside neighbourhood with a strong Facebook presence.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["community", "urban", "toronto"],
    contacts: [],
  },

  {
    id: "balmy-beach-club-bowls",
    name: "Balmy Beach Club (Bowls)",
    city: "Toronto",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "360 Lake Front, Toronto, ON M4E 1A7",
    lat: 43.6680,
    lng: -79.2870,
    website: "https://balmybeachlawnbowling.com",
    phone: "(416) 694-4170",
    memberCount: 90,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms", "multi-sport-complex"],
    description: "Part of the historic Balmy Beach Club complex on Toronto's waterfront. The Bowls section is one of several sports offered at this multi-sport facility.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["historic", "multi-sport", "waterfront", "toronto"],
    contacts: [],
  },

  {
    id: "burlington-lawn-bowling-club",
    name: "Burlington Lawn Bowling Club",
    city: "Burlington",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "2275 New Street, Burlington, ON L7R 1J4",
    lat: 43.3255,
    lng: -79.7990,
    website: "https://burlingtonlbc.org",
    phone: "(905) 333-5622",
    memberCount: 90,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Well-established lawn bowling club in Burlington, Ontario.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["community", "suburban", "golden-horseshoe"],
    contacts: [],
  },

  {
    id: "oakville-lawn-bowling-club",
    name: "Oakville Lawn Bowling Club",
    city: "Oakville",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "111 King Street, Oakville, ON L6J 2Y3",
    lat: 43.4500,
    lng: -79.6800,
    website: "https://oakvillelawnbowling.ca",
    phone: "(905) 466-6242",
    memberCount: 80,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Oakville lawn bowling club in the heart of the town.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["community", "suburban", "golden-horseshoe"],
    contacts: [],
  },

  {
    id: "nepean-lawn-bowling-club",
    name: "Nepean Lawn Bowling Club",
    city: "Nepean",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "1701 Woodroffe Avenue, Nepean Sportsplex, Nepean, ON K2G 1W2",
    lat: 45.3470,
    lng: -75.7340,
    website: "https://nepeanlawnbowls.com",
    phone: "(613) 604-4373",
    memberCount: 80,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues", "tournaments", "para-bowls"],
    facilities: ["clubhouse", "greens", "parking", "washrooms", "wheelchair-accessible"],
    description: "Wheelchair accessible lawn bowling club in Ottawa's Nepean area. Host of the 2025 Canadian Para Bowls Championships.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["accessible", "para-bowls", "championship-host", "ottawa"],
    contacts: [],
  },

  {
    id: "highland-park-lawn-bowling-club",
    name: "Highland Park Lawn Bowling Club",
    city: "Ottawa",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "439 Golden Avenue At Byron, Ottawa, ON K2A 3L9",
    lat: 45.3830,
    lng: -75.7420,
    website: "https://highlandparklawnbowling.ca",
    phone: "(613) 722-9231",
    memberCount: 70,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Community lawn bowling club in Ottawa's Westboro area.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["community", "ottawa"],
    contacts: [],
  },

  {
    id: "elmdale-lawn-bowling-club",
    name: "Elmdale Lawn Bowling Club",
    city: "Ottawa",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "MacFarlane Avenue, Ottawa, ON K1Y 2P5",
    lat: 45.3978,
    lng: -75.7236,
    website: "https://elmdalelawnbowling.com",
    phone: "(613) 722-2205",
    memberCount: 70,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Ottawa lawn bowling club in the Hintonburg neighbourhood.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["community", "ottawa"],
    contacts: [],
  },

  {
    id: "guelph-lawn-bowling-club",
    name: "Guelph Lawn Bowling Club",
    city: "Guelph",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "114 Gordon Street, Guelph, ON N1H 4H6",
    lat: 43.5448,
    lng: -80.2482,
    website: "https://guelphlawnbowling.com",
    phone: "(519) 824-0166",
    memberCount: 70,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Community lawn bowling club in the university city of Guelph.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["community", "university-city"],
    contacts: [],
  },

  {
    id: "brampton-lawn-bowling-club",
    name: "Brampton Lawn Bowling Club",
    city: "Brampton",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "8910 McLaughlin Road, Brampton, ON L6Y 5T1",
    lat: 43.7315,
    lng: -79.7624,
    website: "https://bramptonlawnbowling.ca",
    phone: "(905) 453-8587",
    memberCount: 70,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Suburban lawn bowling club in Brampton, part of the Greater Toronto Area.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["community", "suburban", "gta"],
    contacts: [],
  },

  {
    id: "niagara-on-the-lake-lawn-bowling-club",
    name: "Niagara-on-the-Lake Lawn Bowling Club",
    city: "Niagara-on-the-Lake",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "14 Anderson Lane, Niagara-on-the-Lake, ON L0S 1J0",
    lat: 43.2553,
    lng: -79.0715,
    website: "https://notlbowls.ca",
    phone: "(289) 696-4160",
    memberCount: 70,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues", "tournaments"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Lawn bowling club in the picturesque tourist town of Niagara-on-the-Lake. Attracts visiting bowlers from the tourism trade.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["tourist-area", "wine-country", "niagara"],
    contacts: [],
  },

  {
    id: "collingwood-lawn-bowling-club",
    name: "Collingwood Lawn Bowling Club",
    city: "Collingwood",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "45 Paterson Street, Collingwood, ON L9Y 4N8",
    lat: 44.5004,
    lng: -80.2169,
    website: "https://collingwoodlawnbowlingclub.com",
    phone: "(705) 445-8292",
    memberCount: 60,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Lawn bowling club in Collingwood, a popular four-season recreation town on Georgian Bay.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["community", "georgian-bay", "recreation-town"],
    contacts: [],
  },

  {
    id: "markham-lawn-bowling-club",
    name: "Markham Lawn Bowling Club",
    city: "Markham",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "28 Franklin Street, Markham, ON L3P 2S8",
    lat: 43.8761,
    lng: -79.2636,
    website: "https://markhamlawnbowling.com",
    phone: "(905) 294-2078",
    memberCount: 60,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "social-events", "leagues"],
    facilities: ["clubhouse", "greens", "parking", "washrooms"],
    description: "Community lawn bowling club in historic Markham Village, part of the Greater Toronto Area.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["community", "historic-village", "gta"],
    contacts: [],
  },

  {
    id: "royal-canadian-yacht-club-bowls",
    name: "Royal Canadian Yacht Club (Bowls)",
    city: "Toronto",
    stateCode: "ON",
    state: "Ontario",
    country: "CA" as CountryCode,
    countryCode: "CA" as CountryCode,
    province: "Ontario",
    region: "central",
    address: "141 St. George Street / R.C.Y.C. Toronto Island, Toronto, ON M5R 2L8",
    lat: 43.6300,
    lng: -79.3770,
    website: "https://rcyc.ca",
    phone: "(416) 967-7245",
    memberCount: 65,
    surfaceType: "natural_grass",
    activities: ["lawn-bowls", "yachting", "social-events", "dining"],
    facilities: ["clubhouse", "greens", "marina", "dining", "bar", "island-facility"],
    description: "Premium private club on Toronto Island where lawn bowls is one of many sporting amenities alongside yachting, tennis, and more.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["private-club", "premium", "yacht-club", "toronto-island", "multi-sport"],
    contacts: [],
  },
];
