// Club directory data — Australian lawn bowls clubs

export type AUState = "NSW" | "VIC" | "QLD" | "SA" | "WA" | "TAS" | "NT" | "ACT";
export type ClubStatus = "active" | "seasonal" | "inactive" | "unverified" | "claimed";
export type SurfaceType = "natural_grass" | "synthetic" | "hybrid" | "unknown";

// Backward compat exports
export type USRegion = string;
export type BowlsUSADivision = string;

export interface ClubData {
  id: string;
  name: string;
  city: string;
  stateCode: AUState;
  state: string;
  region?: string;
  address?: string;
  lat?: number;
  lng?: number;
  website?: string;
  phone?: string;
  email?: string;
  memberCount?: number;
  greens?: number;
  rinks?: number;
  surfaceType: SurfaceType;
  division?: string;
  activities: string[];
  facilities: string[];
  founded?: number;
  description?: string;
  status: ClubStatus;
  hasOnlinePresence: boolean;
  facebookUrl?: string;
  instagramUrl?: string;
  youtubeUrl?: string;
  logoUrl?: string;
  coverImageUrl?: string;
  tags: string[];
  claimedBy?: string;
  claimedAt?: string;
  venueId?: string;
  isFeatured?: boolean;
  metaTitle?: string;
  metaDescription?: string;
  socialMedia?: {
    facebook?: string;
    instagram?: string;
    youtube?: string;
  };
}

export const AU_STATES: Record<AUState, { name: string; code: AUState; region: string }> = {
  NSW: { name: "New South Wales", code: "NSW", region: "east" },
  VIC: { name: "Victoria", code: "VIC", region: "south" },
  QLD: { name: "Queensland", code: "QLD", region: "north" },
  SA:  { name: "South Australia", code: "SA", region: "south" },
  WA:  { name: "Western Australia", code: "WA", region: "west" },
  TAS: { name: "Tasmania", code: "TAS", region: "south" },
  NT:  { name: "Northern Territory", code: "NT", region: "north" },
  ACT: { name: "Australian Capital Territory", code: "ACT", region: "east" },
};

export const US_STATES = AU_STATES as Record<string, { name: string; code: string; region: string }>;

export const REGION_LABELS: Record<string, { label: string; emoji: string }> = {
  east:    { label: "East",    emoji: "🌊" },
  south:   { label: "South",   emoji: "☀️" },
  north:   { label: "North",   emoji: "❄️" },
  west:    { label: "West",    emoji: "🏔️" },
};

export const SURFACE_LABELS: Record<SurfaceType, string> = {
  natural_grass: "Natural Grass",
  synthetic: "Synthetic",
  hybrid: "Hybrid",
  unknown: "Unknown",
};

export const ACTIVITY_OPTIONS = [
  "Pennant/Competition",
  "Social Bowls",
  "Barefoot Bowls",
  "Coaching",
  "Corporate Events",
  "Night Bowls",
  "Junior Bowls",
  "Tournaments",
  "Open Days",
] as const;

export const CLUBS: ClubData[] = [
  // === NEW SOUTH WALES (25) ===
  {
    id: "nsw-city-of-sydney",
    name: "City of Sydney Bowls Club",
    city: "Sydney",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Sydney Metro",
    address: "7 Playfair St, The Rocks NSW 2000",
    lat: -33.8592,
    lng: 151.2081,
    website: "https://www.cityofsydneybowls.com.au",
    phone: "(02) 9252 2485",
    email: "info@cityofsydneybowls.com.au",
    memberCount: 340,
    greens: 2,
    rinks: 14,
    surfaceType: "synthetic",
    division: "Zone 10",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Night Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Pro Shop", "Disabled Access"],
    founded: 1908,
    description: "Located in the heart of The Rocks with stunning harbour views. One of Sydney's premier bowling clubs offering world-class synthetic greens and year-round play.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/cityofsydneybowls",
    instagramUrl: "https://instagram.com/cityofsydneybowls",
    socialMedia: { facebook: "cityofsydneybowls", instagram: "cityofsydneybowls" },
    tags: ["harbour-views", "corporate-events", "barefoot-bowls", "premier", "synthetic"],
    isFeatured: true,
    metaTitle: "City of Sydney Bowls Club - Harbour Views Lawn Bowls",
    metaDescription: "Play lawn bowls with stunning Sydney Harbour views at The Rocks. Corporate events, barefoot bowls, and pennant competition.",
  },
  {
    id: "nsw-mosman",
    name: "Mosman Bowling Club",
    city: "Mosman",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Sydney Metro",
    address: "95 Avenue Rd, Mosman NSW 2088",
    lat: -33.8271,
    lng: 151.2419,
    website: "https://www.mosmanbowlingclub.com.au",
    phone: "(02) 9969 4211",
    email: "info@mosmanbowlingclub.com.au",
    memberCount: 280,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Disabled Access"],
    founded: 1924,
    description: "A premier North Shore bowling club with beautiful natural grass greens and harbour-fringe setting.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/mosmanbowlingclub",
    socialMedia: { facebook: "mosmanbowlingclub" },
    tags: ["north-shore", "natural-grass", "harbour-fringe", "pennant"],
    metaTitle: "Mosman Bowling Club - North Shore Lawn Bowls",
    metaDescription: "Premier North Shore bowling club in Mosman with natural grass greens and pennant competition.",
  },
  {
    id: "nsw-coogee",
    name: "Coogee Bowling Club",
    city: "Coogee",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Sydney Metro",
    address: "Bunya Parade, Coogee NSW 2034",
    lat: -33.9192,
    lng: 151.2550,
    website: "https://www.coogeebowlo.com.au",
    phone: "(02) 9665 2155",
    email: "info@coogeebowlo.com.au",
    memberCount: 220,
    greens: 1,
    rinks: 8,
    surfaceType: "synthetic",
    activities: ["Social Bowls", "Barefoot Bowls", "Corporate Events", "Night Bowls", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Disabled Access"],
    founded: 1928,
    description: "Iconic eastern suburbs bowls club known for its vibrant barefoot bowls scene and ocean views. A Sydney institution.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/coogeebowlo",
    instagramUrl: "https://instagram.com/coogeebowlo",
    socialMedia: { facebook: "coogeebowlo", instagram: "coogeebowlo" },
    tags: ["ocean-views", "barefoot-bowls", "nightlife", "eastern-suburbs"],
    isFeatured: true,
    metaTitle: "Coogee Bowling Club - Barefoot Bowls by the Beach",
    metaDescription: "Iconic Coogee bowls club with ocean views, barefoot bowls, night bowls and corporate events near Coogee Beach.",
  },
  {
    id: "nsw-alexandria-erskineville",
    name: "Alexandria-Erskineville Bowling Club",
    city: "Erskineville",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Sydney Metro",
    address: "59 Fox Ave, Erskineville NSW 2043",
    lat: -33.9010,
    lng: 151.1856,
    phone: "(02) 9565 1436",
    memberCount: 120,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1920,
    description: "Community-focused inner-west bowling club with a relaxed atmosphere and strong local following.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/alexerskobowlo",
    socialMedia: { facebook: "alexerskobowlo" },
    tags: ["inner-west", "community", "relaxed"],
  },
  {
    id: "nsw-manly",
    name: "Manly Bowling Club",
    city: "Manly",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Northern Beaches",
    address: "2 West Promenade, Manly NSW 2095",
    lat: -33.7978,
    lng: 151.2840,
    website: "https://www.manlybowlingclub.com.au",
    phone: "(02) 9977 2926",
    email: "info@manlybowlingclub.com.au",
    memberCount: 180,
    greens: 1,
    rinks: 8,
    surfaceType: "synthetic",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Disabled Access"],
    founded: 1932,
    description: "Beachside bowling club on Manly's west promenade with views across the harbour. Popular barefoot bowls destination.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/manlybowlingclub",
    socialMedia: { facebook: "manlybowlingclub" },
    tags: ["beachside", "harbour-views", "barefoot-bowls", "northern-beaches"],
  },
  {
    id: "nsw-randwick",
    name: "Randwick Bowling Club",
    city: "Randwick",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Sydney Metro",
    address: "68 Alison Rd, Randwick NSW 2031",
    lat: -33.9125,
    lng: 151.2422,
    website: "https://www.randwickbowling.com.au",
    phone: "(02) 9399 2833",
    memberCount: 190,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking", "Disabled Access"],
    founded: 1906,
    description: "One of Sydney's oldest bowling clubs with two well-maintained natural grass greens and strong pennant programs.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["historic", "pennant", "natural-grass", "eastern-suburbs"],
  },
  {
    id: "nsw-neutral-bay",
    name: "Neutral Bay Club",
    city: "Neutral Bay",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Sydney Metro",
    address: "1-3 Yeo St, Neutral Bay NSW 2089",
    lat: -33.8368,
    lng: 151.2198,
    website: "https://www.neutralbayclub.com.au",
    phone: "(02) 9953 1286",
    email: "bowls@neutralbayclub.com.au",
    memberCount: 250,
    greens: 2,
    rinks: 10,
    surfaceType: "synthetic",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching", "Night Bowls"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Pro Shop", "Disabled Access"],
    founded: 1915,
    description: "Premium lower North Shore bowling club with modern synthetic greens and a vibrant social calendar.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/neutralbayclub",
    socialMedia: { facebook: "neutralbayclub" },
    tags: ["north-shore", "synthetic", "premium", "night-bowls"],
  },
  {
    id: "nsw-newcastle-city",
    name: "Newcastle City Bowling Club",
    city: "Newcastle",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Hunter",
    address: "King Edward Park, Newcastle NSW 2300",
    lat: -32.9300,
    lng: 151.7800,
    website: "https://www.newcastlecitybowls.com.au",
    phone: "(02) 4929 3240",
    email: "info@newcastlecitybowls.com.au",
    memberCount: 200,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking", "Disabled Access"],
    founded: 1892,
    description: "Historic Newcastle bowling club overlooking the harbour. One of the Hunter region's most prestigious clubs.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["historic", "harbour-views", "hunter-region", "pennant"],
  },
  {
    id: "nsw-wollongong",
    name: "Wollongong City Bowling Club",
    city: "Wollongong",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Illawarra",
    address: "4 Pioneer Rd, Wollongong NSW 2500",
    lat: -34.4278,
    lng: 150.8931,
    website: "https://www.wollongongbowlingclub.com.au",
    phone: "(02) 4228 4666",
    memberCount: 170,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Disabled Access"],
    founded: 1911,
    description: "The Illawarra's leading bowling club with panoramic escarpment views and two lush natural grass greens.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["illawarra", "escarpment-views", "pennant"],
  },
  {
    id: "nsw-port-macquarie",
    name: "Port Macquarie Bowling Club",
    city: "Port Macquarie",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Mid North Coast",
    address: "1 Owen St, Port Macquarie NSW 2444",
    lat: -31.4333,
    lng: 152.9000,
    phone: "(02) 6583 1133",
    memberCount: 160,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking", "Disabled Access"],
    founded: 1935,
    description: "Popular mid-north coast bowling club with strong social and pennant programs in a picturesque coastal setting.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["mid-north-coast", "coastal", "pennant"],
  },
  {
    id: "nsw-tamworth",
    name: "Tamworth City Bowling Club",
    city: "Tamworth",
    stateCode: "NSW",
    state: "New South Wales",
    region: "New England",
    address: "Kable Ave, Tamworth NSW 2340",
    lat: -31.0833,
    lng: 150.9167,
    phone: "(02) 6766 2549",
    memberCount: 130,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1924,
    description: "Country bowling club in the heart of Tamworth with a strong pennant program and welcoming social scene.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["country", "new-england", "pennant"],
  },
  {
    id: "nsw-bathurst",
    name: "Bathurst City Bowling Club",
    city: "Bathurst",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Central West",
    address: "31 William St, Bathurst NSW 2795",
    lat: -33.4167,
    lng: 149.5833,
    phone: "(02) 6331 1499",
    memberCount: 110,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1900,
    description: "Historic Central West bowling club with over a century of bowling tradition.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["historic", "central-west", "country"],
  },
  {
    id: "nsw-orange",
    name: "Orange City Bowling Club",
    city: "Orange",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Central West",
    address: "149 Moulder St, Orange NSW 2800",
    lat: -33.2833,
    lng: 149.1000,
    phone: "(02) 6362 3588",
    memberCount: 120,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking"],
    founded: 1919,
    description: "The premier bowling club of the Orange region with excellent facilities and a thriving social and competitive scene.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["central-west", "country", "bistro"],
  },
  {
    id: "nsw-lismore",
    name: "Lismore Workers Bowling Club",
    city: "Lismore",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Northern Rivers",
    address: "Keen St, Lismore NSW 2480",
    lat: -28.8117,
    lng: 153.2750,
    phone: "(02) 6621 2481",
    memberCount: 140,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Disabled Access"],
    founded: 1945,
    description: "Community-focused club in the Northern Rivers region with modern facilities and two well-maintained greens.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["northern-rivers", "workers-club", "community"],
  },
  {
    id: "nsw-coffs-harbour",
    name: "Coffs Harbour Bowling Club",
    city: "Coffs Harbour",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Mid North Coast",
    address: "Orlando St, Coffs Harbour NSW 2450",
    lat: -30.2964,
    lng: 153.1139,
    phone: "(02) 6652 3244",
    memberCount: 150,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking", "Disabled Access"],
    founded: 1938,
    description: "Thriving mid-north coast bowling club with excellent greens and a warm, welcoming atmosphere.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["mid-north-coast", "coastal", "pennant"],
  },
  {
    id: "nsw-penrith",
    name: "Penrith Bowling Club",
    city: "Penrith",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Western Sydney",
    address: "3-5 Woodriff St, Penrith NSW 2750",
    lat: -33.7511,
    lng: 150.6942,
    phone: "(02) 4731 1461",
    memberCount: 200,
    greens: 2,
    rinks: 14,
    surfaceType: "synthetic",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Night Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Disabled Access"],
    founded: 1925,
    description: "Western Sydney's largest bowling club with modern synthetic greens lit for night play.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/penrithbowling",
    socialMedia: { facebook: "penrithbowling" },
    tags: ["western-sydney", "night-bowls", "synthetic", "large-club"],
  },
  {
    id: "nsw-cronulla",
    name: "Cronulla Bowling & Recreation Club",
    city: "Cronulla",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Sutherland Shire",
    address: "12 Purley Pl, Cronulla NSW 2230",
    lat: -34.0540,
    lng: 151.1519,
    phone: "(02) 9523 6232",
    memberCount: 180,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Disabled Access"],
    founded: 1935,
    description: "Shire favourite steps from Cronulla beach. Two immaculate greens, bustling bistro, and great barefoot bowls.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["beachside", "shire", "barefoot-bowls", "bistro"],
  },
  {
    id: "nsw-warilla",
    name: "Warilla Bowling & Recreation Club",
    city: "Warilla",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Illawarra",
    address: "Princes Hwy, Warilla NSW 2528",
    lat: -34.5540,
    lng: 150.8556,
    phone: "(02) 4296 1600",
    email: "info@warillabowls.com.au",
    website: "https://www.warillabowls.com.au",
    memberCount: 300,
    greens: 3,
    rinks: 18,
    surfaceType: "synthetic",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching", "Tournaments", "Junior Bowls"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Pro Shop", "Disabled Access"],
    founded: 1960,
    description: "One of the largest bowling clubs in the Illawarra with three synthetic greens and a reputation for hosting major regional tournaments.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/warillabowls",
    socialMedia: { facebook: "warillabowls" },
    tags: ["illawarra", "large-club", "tournaments", "synthetic"],
    isFeatured: true,
  },
  {
    id: "nsw-wagga-wagga",
    name: "Wagga RSL Bowling Club",
    city: "Wagga Wagga",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Riverina",
    address: "Dobbs St, Wagga Wagga NSW 2650",
    lat: -35.1189,
    lng: 147.3533,
    phone: "(02) 6921 3624",
    memberCount: 140,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar", "Parking", "Disabled Access"],
    founded: 1946,
    description: "Riverina's top bowling club with strong RSL roots and an active competition program.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["riverina", "rsl", "country", "pennant"],
  },
  {
    id: "nsw-dubbo",
    name: "Dubbo City Bowling Club",
    city: "Dubbo",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Central West",
    address: "Bultje St, Dubbo NSW 2830",
    lat: -32.2431,
    lng: 148.6017,
    phone: "(02) 6882 4411",
    memberCount: 110,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1930,
    description: "Central West bowling hub with well-maintained greens and a strong community following.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["central-west", "country"],
  },
  {
    id: "nsw-tweed-heads",
    name: "Tweed Heads Bowls Club",
    city: "Tweed Heads",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Tweed",
    address: "Florence St, Tweed Heads NSW 2485",
    lat: -28.1756,
    lng: 153.5433,
    phone: "(07) 5536 3800",
    email: "info@tweedheadsbowls.com.au",
    website: "https://www.tweedheadsbowls.com.au",
    memberCount: 260,
    greens: 3,
    rinks: 18,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Pro Shop", "Disabled Access"],
    founded: 1940,
    description: "Major bowls destination on the NSW-QLD border. Three outstanding greens and a full-service club.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/tweedheadsbowls",
    socialMedia: { facebook: "tweedheadsbowls" },
    tags: ["border-town", "large-club", "tournaments", "bistro"],
    isFeatured: true,
  },
  {
    id: "nsw-forster",
    name: "Forster Bowling Club",
    city: "Forster",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Great Lakes",
    address: "Strand St, Forster NSW 2428",
    lat: -32.1806,
    lng: 152.5167,
    phone: "(02) 6554 6155",
    memberCount: 130,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking"],
    founded: 1955,
    description: "Beautiful lakeside bowling club on the mid-north coast. Popular with retirees and holidaymakers.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["lakeside", "coastal", "mid-north-coast"],
  },
  {
    id: "nsw-albury",
    name: "Albury City Bowling Club",
    city: "Albury",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Murray",
    address: "530 Smollett St, Albury NSW 2640",
    lat: -36.0737,
    lng: 146.9135,
    phone: "(02) 6021 2822",
    memberCount: 120,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1910,
    description: "Border city bowling club with a strong competitive tradition. Gateway to the Murray River region.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["border-town", "murray", "pennant"],
  },
  {
    id: "nsw-broken-hill",
    name: "Broken Hill Bowling Club",
    city: "Broken Hill",
    stateCode: "NSW",
    state: "New South Wales",
    region: "Far West",
    address: "270 Crystal St, Broken Hill NSW 2880",
    lat: -31.9522,
    lng: 141.4581,
    phone: "(08) 8087 2701",
    memberCount: 70,
    greens: 1,
    rinks: 8,
    surfaceType: "natural_grass",
    activities: ["Social Bowls", "Pennant/Competition", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1915,
    description: "Outback bowling club in the heart of the Silver City. A welcoming oasis for locals and visitors to the far west.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["outback", "far-west", "historic"],
  },
  // === VICTORIA (22) ===
  {
    id: "vic-royal-park",
    name: "Royal Park Bowling Club",
    city: "Melbourne",
    stateCode: "VIC",
    state: "Victoria",
    region: "Melbourne Metro",
    address: "Royal Park, Parkville VIC 3052",
    lat: -37.7833,
    lng: 144.9500,
    website: "https://www.royalparkbowls.com.au",
    phone: "(03) 9387 1288",
    email: "info@royalparkbowls.com.au",
    memberCount: 260,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching", "Corporate Events"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking", "Disabled Access"],
    founded: 1904,
    description: "Historic inner-Melbourne bowling club in beautiful Royal Park. Two natural grass greens surrounded by parkland.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/royalparkbowls",
    socialMedia: { facebook: "royalparkbowls" },
    tags: ["historic", "parkland", "inner-city", "natural-grass"],
    isFeatured: true,
    metaTitle: "Royal Park Bowling Club - Inner Melbourne Lawn Bowls",
    metaDescription: "Historic bowling club in Royal Park, Parkville. Natural grass greens, pennant competition, barefoot bowls and coaching.",
  },
  {
    id: "vic-hawthorn",
    name: "Hawthorn Bowling Club",
    city: "Hawthorn",
    stateCode: "VIC",
    state: "Victoria",
    region: "Melbourne Metro",
    address: "4 Victoria Rd, Hawthorn VIC 3122",
    lat: -37.8220,
    lng: 145.0333,
    website: "https://www.hawthornbowlingclub.com.au",
    phone: "(03) 9818 2842",
    memberCount: 200,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1908,
    description: "Long-standing inner-east bowling club with a proud pennant history and active social bowls program.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["inner-east", "pennant", "historic"],
  },
  {
    id: "vic-st-kilda",
    name: "St Kilda Bowling Club",
    city: "St Kilda",
    stateCode: "VIC",
    state: "Victoria",
    region: "Melbourne Metro",
    address: "66 Fitzroy St, St Kilda VIC 3182",
    lat: -37.8617,
    lng: 144.9767,
    website: "https://www.stkildabowlingclub.com.au",
    phone: "(03) 9525 3173",
    email: "info@stkildabowlingclub.com.au",
    memberCount: 160,
    greens: 1,
    rinks: 8,
    surfaceType: "synthetic",
    activities: ["Social Bowls", "Barefoot Bowls", "Corporate Events", "Night Bowls", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Disabled Access"],
    founded: 1910,
    description: "Vibrant bayside club on Fitzroy Street known for its buzzing barefoot bowls scene, night bowls, and eclectic atmosphere.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/stkildabowlo",
    instagramUrl: "https://instagram.com/stkildabowlo",
    socialMedia: { facebook: "stkildabowlo", instagram: "stkildabowlo" },
    tags: ["bayside", "barefoot-bowls", "nightlife", "eclectic"],
    isFeatured: true,
  },
  {
    id: "vic-fitzroy",
    name: "Fitzroy Victoria Bowling & Sports Club",
    city: "Fitzroy",
    stateCode: "VIC",
    state: "Victoria",
    region: "Melbourne Metro",
    address: "578 Brunswick St, Fitzroy North VIC 3068",
    lat: -37.7856,
    lng: 144.9842,
    phone: "(03) 9481 3137",
    memberCount: 130,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    activities: ["Social Bowls", "Barefoot Bowls", "Corporate Events", "Night Bowls"],
    facilities: ["Clubhouse", "Bar", "Disabled Access"],
    founded: 1888,
    description: "Inner-city institution in the heart of Fitzroy. One of Melbourne's oldest clubs with a relaxed, community-driven vibe.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/fitzroyvicbowls",
    socialMedia: { facebook: "fitzroyvicbowls" },
    tags: ["inner-city", "historic", "community", "barefoot-bowls"],
  },
  {
    id: "vic-brighton",
    name: "Brighton Bowling Club",
    city: "Brighton",
    stateCode: "VIC",
    state: "Victoria",
    region: "Bayside",
    address: "48 South Rd, Brighton VIC 3186",
    lat: -37.9089,
    lng: 144.9928,
    website: "https://www.brightonbowls.com.au",
    phone: "(03) 9592 5530",
    memberCount: 220,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking", "Disabled Access"],
    founded: 1912,
    description: "Premier Bayside bowling club with beautifully maintained greens and a strong pennant reputation.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["bayside", "premier", "pennant", "natural-grass"],
  },
  {
    id: "vic-kew",
    name: "Kew Bowling Club",
    city: "Kew",
    stateCode: "VIC",
    state: "Victoria",
    region: "Melbourne Metro",
    address: "5 Parkhill Rd, Kew VIC 3101",
    lat: -37.8017,
    lng: 145.0342,
    phone: "(03) 9853 6166",
    memberCount: 180,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1907,
    description: "Established inner-east club with two well-kept greens and a close-knit bowling community.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["inner-east", "pennant", "community"],
  },
  {
    id: "vic-williamstown",
    name: "Williamstown Bowling Club",
    city: "Williamstown",
    stateCode: "VIC",
    state: "Victoria",
    region: "Melbourne Metro",
    address: "36 Cecil St, Williamstown VIC 3016",
    lat: -37.8625,
    lng: 144.9000,
    phone: "(03) 9397 1714",
    memberCount: 140,
    greens: 1,
    rinks: 8,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1885,
    description: "One of Victoria's oldest bowling clubs in historic Williamstown with a charming harbourside setting.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["historic", "harbourside", "williamstown"],
  },
  {
    id: "vic-elsternwick",
    name: "Elsternwick Park Bowling Club",
    city: "Elsternwick",
    stateCode: "VIC",
    state: "Victoria",
    region: "Melbourne Metro",
    address: "Elsternwick Park, Elsternwick VIC 3185",
    lat: -37.8831,
    lng: 144.9894,
    phone: "(03) 9528 1748",
    memberCount: 100,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1934,
    description: "Friendly suburban club set in leafy Elsternwick Park. Welcoming to new bowlers with coaching available.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["suburban", "parkland", "beginner-friendly"],
  },
  {
    id: "vic-geelong",
    name: "Geelong Bowling Club",
    city: "Geelong",
    stateCode: "VIC",
    state: "Victoria",
    region: "Geelong",
    address: "2 Myers St, Geelong VIC 3220",
    lat: -38.1500,
    lng: 144.3667,
    website: "https://www.geelongbowlingclub.com.au",
    phone: "(03) 5221 5799",
    email: "info@geelongbowlingclub.com.au",
    memberCount: 230,
    greens: 3,
    rinks: 18,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching", "Tournaments", "Junior Bowls"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Pro Shop", "Disabled Access"],
    founded: 1861,
    description: "Victoria's oldest bowling club and one of the oldest in Australia. Three pristine greens and a proud tradition.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/geelongbowls",
    socialMedia: { facebook: "geelongbowls" },
    tags: ["historic", "oldest-in-victoria", "large-club", "tournaments"],
    isFeatured: true,
  },
  {
    id: "vic-ballarat",
    name: "Ballarat Bowling Club",
    city: "Ballarat",
    stateCode: "VIC",
    state: "Victoria",
    region: "Goldfields",
    address: "716 Sturt St, Ballarat Central VIC 3350",
    lat: -37.5667,
    lng: 143.8667,
    phone: "(03) 5331 2553",
    memberCount: 160,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1875,
    description: "One of country Victoria's premier bowling clubs with a rich goldfields heritage.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["goldfields", "country", "historic", "pennant"],
  },
  {
    id: "vic-bendigo",
    name: "Bendigo Bowling Club",
    city: "Bendigo",
    stateCode: "VIC",
    state: "Victoria",
    region: "Goldfields",
    address: "56 Edwards Rd, Bendigo VIC 3550",
    lat: -36.7583,
    lng: 144.2833,
    phone: "(03) 5443 4897",
    email: "info@bendigobowls.com.au",
    memberCount: 170,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments", "Junior Bowls"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking", "Disabled Access"],
    founded: 1870,
    description: "Historic Bendigo club with two superb natural grass greens and active junior development.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["goldfields", "country", "historic", "juniors"],
  },
  {
    id: "vic-shepparton",
    name: "Shepparton Bowling Club",
    city: "Shepparton",
    stateCode: "VIC",
    state: "Victoria",
    region: "Goulburn Valley",
    address: "45 Archer St, Shepparton VIC 3630",
    lat: -36.3833,
    lng: 145.4000,
    phone: "(03) 5821 3233",
    memberCount: 130,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1920,
    description: "Friendly Goulburn Valley club with well-maintained greens and a welcoming atmosphere.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["goulburn-valley", "country", "beginner-friendly"],
  },
  {
    id: "vic-mildura",
    name: "Mildura Bowling Club",
    city: "Mildura",
    stateCode: "VIC",
    state: "Victoria",
    region: "Sunraysia",
    address: "46 Deakin Ave, Mildura VIC 3500",
    lat: -34.1833,
    lng: 142.1500,
    phone: "(03) 5023 0441",
    memberCount: 120,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1922,
    description: "Sun-drenched Sunraysia club on the banks of the Murray. Year-round bowling in one of Australia's warmest regions.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["sunraysia", "murray-river", "year-round"],
  },
  {
    id: "vic-warrnambool",
    name: "Warrnambool Bowling Club",
    city: "Warrnambool",
    stateCode: "VIC",
    state: "Victoria",
    region: "Western District",
    address: "78 Timor St, Warrnambool VIC 3280",
    lat: -38.3833,
    lng: 142.4833,
    phone: "(03) 5562 2124",
    memberCount: 110,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1890,
    description: "Welcoming Western District club with a proud bowling history stretching back to the 1890s.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["western-district", "country", "historic"],
  },
  {
    id: "vic-mornington",
    name: "Mornington Bowling Club",
    city: "Mornington",
    stateCode: "VIC",
    state: "Victoria",
    region: "Mornington Peninsula",
    address: "2 Barkly St, Mornington VIC 3931",
    lat: -38.2194,
    lng: 145.0375,
    phone: "(03) 5975 2767",
    memberCount: 190,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking", "Disabled Access"],
    founded: 1927,
    description: "Popular Mornington Peninsula club with two well-maintained greens near the beach and winery region.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/morningtonbowls",
    socialMedia: { facebook: "morningtonbowls" },
    tags: ["peninsula", "coastal", "barefoot-bowls", "bistro"],
  },
  {
    id: "vic-traralgon",
    name: "Traralgon Bowling Club",
    city: "Traralgon",
    stateCode: "VIC",
    state: "Victoria",
    region: "Gippsland",
    address: "18 Breed St, Traralgon VIC 3844",
    lat: -38.1956,
    lng: 146.5333,
    phone: "(03) 5174 6363",
    memberCount: 140,
    greens: 2,
    rinks: 12,
    surfaceType: "synthetic",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking"],
    founded: 1925,
    description: "Gippsland's leading bowling club with modern synthetic greens ensuring year-round play.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["gippsland", "synthetic", "country"],
  },
  {
    id: "vic-frankston",
    name: "Frankston Bowling Club",
    city: "Frankston",
    stateCode: "VIC",
    state: "Victoria",
    region: "Melbourne Metro",
    address: "4 William St, Frankston VIC 3199",
    lat: -38.1431,
    lng: 145.1264,
    phone: "(03) 9783 2788",
    memberCount: 170,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking", "Disabled Access"],
    founded: 1921,
    description: "Active bayside club near Frankston centre. Strong pennant sides and popular social bowls.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["bayside", "pennant", "social"],
  },
  {
    id: "vic-sandringham",
    name: "Sandringham Bowls Club",
    city: "Sandringham",
    stateCode: "VIC",
    state: "Victoria",
    region: "Bayside",
    address: "2 Royal Ave, Sandringham VIC 3191",
    lat: -37.9517,
    lng: 145.0097,
    phone: "(03) 9598 2454",
    memberCount: 190,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1913,
    description: "Well-established Bayside club with a strong competitive reputation and beautifully presented greens.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["bayside", "pennant", "competitive"],
  },
  {
    id: "vic-ringwood",
    name: "Ringwood Bowling Club",
    city: "Ringwood",
    stateCode: "VIC",
    state: "Victoria",
    region: "Melbourne Metro",
    address: "5 Loughnan Rd, Ringwood VIC 3134",
    lat: -37.8158,
    lng: 145.2286,
    phone: "(03) 9870 1714",
    memberCount: 150,
    greens: 2,
    rinks: 10,
    surfaceType: "synthetic",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching", "Night Bowls"],
    facilities: ["Clubhouse", "Bar", "Parking", "Disabled Access"],
    founded: 1930,
    description: "Eastern suburbs club with modern synthetic greens and night-bowling capability.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["eastern-suburbs", "synthetic", "night-bowls"],
  },
  {
    id: "vic-wodonga",
    name: "Wodonga Bowling Club",
    city: "Wodonga",
    stateCode: "VIC",
    state: "Victoria",
    region: "North East",
    address: "6 Stanley St, Wodonga VIC 3690",
    lat: -36.1186,
    lng: 146.8856,
    phone: "(02) 6024 1542",
    memberCount: 100,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1928,
    description: "North-east Victoria club near the Murray River. A welcoming community club with solid programs.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["north-east", "border-town", "country"],
  },
  // === QUEENSLAND (16) ===
  {
    id: "qld-broadbeach",
    name: "Broadbeach Bowls Club",
    city: "Broadbeach",
    stateCode: "QLD",
    state: "Queensland",
    region: "Gold Coast",
    address: "100 Surf Parade, Broadbeach QLD 4218",
    lat: -28.0283,
    lng: 153.4317,
    website: "https://www.broadbeachbowls.com.au",
    phone: "(07) 5592 1500",
    email: "info@broadbeachbowls.com.au",
    memberCount: 320,
    greens: 3,
    rinks: 18,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Night Bowls", "Coaching", "Tournaments", "Junior Bowls"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Pro Shop", "Disabled Access"],
    founded: 1958,
    description: "Gold Coast's premier bowling destination. Three world-class greens, a buzzing social scene, and host of national tournaments.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/broadbeachbowls",
    instagramUrl: "https://instagram.com/broadbeachbowls",
    socialMedia: { facebook: "broadbeachbowls", instagram: "broadbeachbowls" },
    tags: ["gold-coast", "premier", "tournaments", "barefoot-bowls", "large-club"],
    isFeatured: true,
    metaTitle: "Broadbeach Bowls Club - Gold Coast Premier Lawn Bowls",
    metaDescription: "Gold Coast's top bowling club with 3 greens, barefoot bowls, tournaments, and world-class facilities.",
  },
  {
    id: "qld-mermaid-beach",
    name: "Mermaid Beach Bowls Club",
    city: "Mermaid Beach",
    stateCode: "QLD",
    state: "Queensland",
    region: "Gold Coast",
    address: "2559 Gold Coast Hwy, Mermaid Beach QLD 4218",
    lat: -28.0444,
    lng: 153.4333,
    phone: "(07) 5575 1255",
    memberCount: 180,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking"],
    founded: 1962,
    description: "Relaxed Gold Coast club with two greens just off the highway. Great mix of competitive and social bowling.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["gold-coast", "beachside", "social"],
  },
  {
    id: "qld-southport",
    name: "Southport Bowling Club",
    city: "Southport",
    stateCode: "QLD",
    state: "Queensland",
    region: "Gold Coast",
    address: "Marine Pde, Southport QLD 4215",
    lat: -27.9667,
    lng: 153.4000,
    phone: "(07) 5532 1986",
    memberCount: 200,
    greens: 2,
    rinks: 14,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Disabled Access"],
    founded: 1946,
    description: "Waterfront bowling club on the Broadwater. Two lush greens with stunning water views and a popular bistro.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["gold-coast", "waterfront", "broadwater-views"],
  },
  {
    id: "qld-brisbane-city",
    name: "City Bowls Club Brisbane",
    city: "Brisbane",
    stateCode: "QLD",
    state: "Queensland",
    region: "Brisbane Metro",
    address: "20 Wickham Tce, Spring Hill QLD 4000",
    lat: -27.4633,
    lng: 153.0269,
    website: "https://www.citybowlsclub.com.au",
    phone: "(07) 3831 4199",
    email: "info@citybowlsclub.com.au",
    memberCount: 240,
    greens: 2,
    rinks: 10,
    surfaceType: "synthetic",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Night Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Disabled Access"],
    founded: 1912,
    description: "Brisbane CBD's premier bowls club with city views from Spring Hill. Modern synthetic greens lit for twilight sessions.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/citybowlsbrisbane",
    socialMedia: { facebook: "citybowlsbrisbane" },
    tags: ["cbd", "city-views", "night-bowls", "corporate-events"],
    isFeatured: true,
  },
  {
    id: "qld-paddington",
    name: "Paddington Bowls Club",
    city: "Paddington",
    stateCode: "QLD",
    state: "Queensland",
    region: "Brisbane Metro",
    address: "27 Enoggera Tce, Paddington QLD 4064",
    lat: -27.4583,
    lng: 152.9967,
    phone: "(07) 3369 3479",
    memberCount: 120,
    greens: 1,
    rinks: 6,
    surfaceType: "natural_grass",
    activities: ["Social Bowls", "Barefoot Bowls", "Corporate Events"],
    facilities: ["Clubhouse", "Bar", "Disabled Access"],
    founded: 1930,
    description: "Trendy inner-city bowls club popular with young professionals. Famous for Saturday barefoot bowls sessions.",
    status: "active",
    hasOnlinePresence: true,
    instagramUrl: "https://instagram.com/paddingtonbowls",
    socialMedia: { instagram: "paddingtonbowls" },
    tags: ["inner-city", "trendy", "barefoot-bowls", "young-crowd"],
  },
  {
    id: "qld-wynnum",
    name: "Wynnum Bowling Club",
    city: "Wynnum",
    stateCode: "QLD",
    state: "Queensland",
    region: "Brisbane Metro",
    address: "91 Preston Rd, Wynnum QLD 4178",
    lat: -27.4544,
    lng: 153.1694,
    phone: "(07) 3893 1362",
    memberCount: 160,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1950,
    description: "Bayside Brisbane bowling club with two greens and a strong competition tradition.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["bayside", "brisbane-east", "pennant"],
  },
  {
    id: "qld-cairns",
    name: "Cairns Bowling Club",
    city: "Cairns",
    stateCode: "QLD",
    state: "Queensland",
    region: "Far North Queensland",
    address: "181 Esplanade, Cairns QLD 4870",
    lat: -16.9186,
    lng: 145.7781,
    website: "https://www.cairnsbowls.com.au",
    phone: "(07) 4051 2866",
    memberCount: 190,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Disabled Access"],
    founded: 1926,
    description: "Tropical bowls club on the Cairns Esplanade. Year-round bowling under the palms with views of Trinity Inlet.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/cairnsbowls",
    socialMedia: { facebook: "cairnsbowls" },
    tags: ["tropical", "esplanade", "far-north-queensland", "year-round"],
  },
  {
    id: "qld-townsville",
    name: "Townsville RSL Bowling Club",
    city: "Townsville",
    stateCode: "QLD",
    state: "Queensland",
    region: "North Queensland",
    address: "Stagpole St, West End QLD 4810",
    lat: -19.2589,
    lng: 146.7783,
    phone: "(07) 4771 4422",
    memberCount: 150,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1946,
    description: "North Queensland's leading bowling club with a proud RSL heritage and two greens in excellent condition.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["north-queensland", "rsl", "year-round"],
  },
  {
    id: "qld-toowoomba",
    name: "Toowoomba City Bowls Club",
    city: "Toowoomba",
    stateCode: "QLD",
    state: "Queensland",
    region: "Darling Downs",
    address: "262 Margaret St, Toowoomba QLD 4350",
    lat: -27.5611,
    lng: 151.9500,
    phone: "(07) 4632 1244",
    memberCount: 140,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking"],
    founded: 1905,
    description: "Darling Downs institution in the Garden City. Cooler highland conditions ideal for bowling.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["darling-downs", "garden-city", "highland"],
  },
  {
    id: "qld-rockhampton",
    name: "Rockhampton Bowling Club",
    city: "Rockhampton",
    stateCode: "QLD",
    state: "Queensland",
    region: "Central Queensland",
    address: "13 Albert St, Rockhampton QLD 4700",
    lat: -23.3817,
    lng: 150.5100,
    phone: "(07) 4922 1611",
    memberCount: 110,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1915,
    description: "Central Queensland's premier bowling club on the banks of the Fitzroy River.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["central-queensland", "riverside", "pennant"],
  },
  {
    id: "qld-hervey-bay",
    name: "Hervey Bay Bowls Club",
    city: "Hervey Bay",
    stateCode: "QLD",
    state: "Queensland",
    region: "Fraser Coast",
    address: "22 Torquay Rd, Hervey Bay QLD 4655",
    lat: -25.2881,
    lng: 152.8433,
    phone: "(07) 4128 1622",
    memberCount: 200,
    greens: 2,
    rinks: 14,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking", "Disabled Access"],
    founded: 1960,
    description: "Whale-watching capital bowls club. Popular retirement destination with a large membership and active social calendar.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["fraser-coast", "retirees", "social", "large-club"],
  },
  {
    id: "qld-caloundra",
    name: "Caloundra Bowls Club",
    city: "Caloundra",
    stateCode: "QLD",
    state: "Queensland",
    region: "Sunshine Coast",
    address: "2 Seaview Tce, Moffat Beach QLD 4551",
    lat: -26.7897,
    lng: 153.1250,
    phone: "(07) 5491 1655",
    memberCount: 180,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking"],
    founded: 1952,
    description: "Ocean-view bowling club perched above Moffat Beach on the Sunshine Coast.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["sunshine-coast", "ocean-views", "coastal"],
  },
  {
    id: "qld-bundaberg",
    name: "Bundaberg Bowling Club",
    city: "Bundaberg",
    stateCode: "QLD",
    state: "Queensland",
    region: "Wide Bay",
    address: "16 Quay St, Bundaberg QLD 4670",
    lat: -24.8667,
    lng: 152.3500,
    phone: "(07) 4152 1444",
    memberCount: 130,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1928,
    description: "Wide Bay bowling club in the heart of Bundaberg with greens maintained to a high standard.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["wide-bay", "subtropical", "country"],
  },
  {
    id: "qld-mackay",
    name: "Mackay Bowling Club",
    city: "Mackay",
    stateCode: "QLD",
    state: "Queensland",
    region: "Mackay",
    address: "24 Shakespeare St, Mackay QLD 4740",
    lat: -21.1411,
    lng: 149.1861,
    phone: "(07) 4957 3544",
    memberCount: 110,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1935,
    description: "Tropical North Queensland bowling club with year-round play and strong local support.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["north-queensland", "tropical", "community"],
  },
  {
    id: "qld-ipswich",
    name: "Ipswich Bowls Club",
    city: "Ipswich",
    stateCode: "QLD",
    state: "Queensland",
    region: "Brisbane Metro",
    address: "22 Limestone St, Ipswich QLD 4305",
    lat: -27.6153,
    lng: 152.7611,
    phone: "(07) 3281 1688",
    memberCount: 140,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking"],
    founded: 1898,
    description: "One of Queensland's oldest bowling clubs with a heritage-listed clubhouse in Ipswich's historic precinct.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["historic", "heritage", "west-brisbane"],
  },
  // === SOUTH AUSTRALIA (8) ===
  {
    id: "sa-adelaide-city",
    name: "Adelaide Bowling Club",
    city: "Adelaide",
    stateCode: "SA",
    state: "South Australia",
    region: "Adelaide Metro",
    address: "South Tce, Adelaide SA 5000",
    lat: -34.9300,
    lng: 138.6000,
    website: "https://www.adelaidebowlingclub.com.au",
    phone: "(08) 8223 5093",
    email: "info@adelaidebowlingclub.com.au",
    memberCount: 220,
    greens: 2,
    rinks: 14,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Pro Shop", "Disabled Access"],
    founded: 1867,
    description: "One of Australia's oldest bowling clubs, located on the Adelaide Parklands. Two pristine greens in the heart of the city.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/adelaidebowlingclub",
    socialMedia: { facebook: "adelaidebowlingclub" },
    tags: ["historic", "parklands", "city-centre", "oldest"],
    isFeatured: true,
    metaTitle: "Adelaide Bowling Club - Historic Lawn Bowls in Adelaide CBD",
    metaDescription: "One of Australia's oldest bowling clubs on Adelaide's South Terrace. Pennant, social bowls and corporate events.",
  },
  {
    id: "sa-glenelg",
    name: "Glenelg Bowling Club",
    city: "Glenelg",
    stateCode: "SA",
    state: "South Australia",
    region: "Adelaide Metro",
    address: "2 Sussex St, Glenelg SA 5045",
    lat: -34.9833,
    lng: 138.5167,
    phone: "(08) 8295 2253",
    memberCount: 180,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking", "Disabled Access"],
    founded: 1899,
    description: "Seaside bowling club near Glenelg beach. Strong pennant tradition and popular barefoot bowls overlooking Holdfast Bay.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["beachside", "holdfast-bay", "barefoot-bowls"],
  },
  {
    id: "sa-north-adelaide",
    name: "North Adelaide Bowling Club",
    city: "North Adelaide",
    stateCode: "SA",
    state: "South Australia",
    region: "Adelaide Metro",
    address: "30 Brougham Pl, North Adelaide SA 5006",
    lat: -34.9078,
    lng: 138.5978,
    phone: "(08) 8267 2283",
    memberCount: 160,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1880,
    description: "Elegant North Adelaide club on the parklands with superb natural grass greens and a rich bowling heritage.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["parklands", "heritage", "pennant"],
  },
  {
    id: "sa-port-adelaide",
    name: "Port Adelaide Bowling Club",
    city: "Port Adelaide",
    stateCode: "SA",
    state: "South Australia",
    region: "Adelaide Metro",
    address: "22 Dale St, Port Adelaide SA 5015",
    lat: -34.8444,
    lng: 138.5028,
    phone: "(08) 8447 1455",
    memberCount: 130,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1882,
    description: "Historic Port Adelaide club near the waterfront. Two greens and a strong community bowling tradition.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["port", "historic", "community", "waterfront"],
  },
  {
    id: "sa-victor-harbor",
    name: "Victor Harbor Bowling Club",
    city: "Victor Harbor",
    stateCode: "SA",
    state: "South Australia",
    region: "Fleurieu Peninsula",
    address: "Bay Rd, Victor Harbor SA 5211",
    lat: -35.5500,
    lng: 138.6167,
    phone: "(08) 8552 1499",
    memberCount: 150,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking"],
    founded: 1924,
    description: "Picturesque bowling club in the popular coastal holiday town of Victor Harbor on the Fleurieu Peninsula.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["fleurieu-peninsula", "coastal", "holiday-town"],
  },
  {
    id: "sa-murray-bridge",
    name: "Murray Bridge Bowling Club",
    city: "Murray Bridge",
    stateCode: "SA",
    state: "South Australia",
    region: "Murraylands",
    address: "Bridge St, Murray Bridge SA 5253",
    lat: -35.1189,
    lng: 139.2631,
    phone: "(08) 8532 2233",
    memberCount: 100,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1910,
    description: "Riverside bowling club on the Murray River. Heart of the Murraylands bowling community.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["murraylands", "riverside", "country"],
  },
  {
    id: "sa-mount-gambier",
    name: "Mount Gambier Bowling Club",
    city: "Mount Gambier",
    stateCode: "SA",
    state: "South Australia",
    region: "Limestone Coast",
    address: "15 Margaret St, Mount Gambier SA 5290",
    lat: -37.8333,
    lng: 140.7667,
    phone: "(08) 8725 2020",
    memberCount: 110,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1895,
    description: "South-east South Australia's leading bowling club in the shadow of the famous Blue Lake.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["limestone-coast", "country", "blue-lake"],
  },
  {
    id: "sa-barossa",
    name: "Tanunda Bowling Club",
    city: "Tanunda",
    stateCode: "SA",
    state: "South Australia",
    region: "Barossa Valley",
    address: "63 Murray St, Tanunda SA 5352",
    lat: -34.5289,
    lng: 138.9622,
    phone: "(08) 8563 2493",
    memberCount: 90,
    greens: 1,
    rinks: 8,
    surfaceType: "natural_grass",
    activities: ["Social Bowls", "Pennant/Competition", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1920,
    description: "Charming Barossa Valley bowling club surrounded by world-famous vineyards. A bowl and a glass of Barossa shiraz.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["barossa-valley", "wine-region", "country"],
  },
  // === WESTERN AUSTRALIA (8) ===
  {
    id: "wa-dalkeith-nedlands",
    name: "Dalkeith Nedlands Bowling Club",
    city: "Dalkeith",
    stateCode: "WA",
    state: "Western Australia",
    region: "Perth Metro",
    address: "60 Waratah Ave, Dalkeith WA 6009",
    lat: -31.9789,
    lng: 115.8028,
    website: "https://www.dalkeithbowls.com.au",
    phone: "(08) 9386 8277",
    email: "info@dalkeithbowls.com.au",
    memberCount: 250,
    greens: 2,
    rinks: 14,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Pro Shop", "Disabled Access"],
    founded: 1926,
    description: "Perth's premier riverside bowling club near the Swan River. Two beautifully maintained greens and first-class facilities.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/dalkeithbowls",
    socialMedia: { facebook: "dalkeithbowls" },
    tags: ["riverside", "premier", "swan-river", "pennant"],
    isFeatured: true,
    metaTitle: "Dalkeith Nedlands Bowling Club - Perth Premium Lawn Bowls",
    metaDescription: "Perth's premier riverside bowling club near the Swan River. Pennant, social bowls, barefoot bowls and corporate events.",
  },
  {
    id: "wa-subiaco",
    name: "Subiaco Bowling Club",
    city: "Subiaco",
    stateCode: "WA",
    state: "Western Australia",
    region: "Perth Metro",
    address: "200 Hamersley Rd, Subiaco WA 6008",
    lat: -31.9489,
    lng: 115.8222,
    phone: "(08) 9381 5011",
    memberCount: 180,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking"],
    founded: 1913,
    description: "Vibrant inner-Perth club in the heart of Subiaco. Known for its lively social bowls and craft beer scene.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/subiacobowls",
    socialMedia: { facebook: "subiacobowls" },
    tags: ["inner-city", "subiaco", "social", "craft-beer"],
  },
  {
    id: "wa-south-perth",
    name: "South Perth Bowling Club",
    city: "South Perth",
    stateCode: "WA",
    state: "Western Australia",
    region: "Perth Metro",
    address: "59 Coode St, South Perth WA 6151",
    lat: -31.9722,
    lng: 115.8611,
    phone: "(08) 9367 2555",
    memberCount: 200,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking", "Disabled Access"],
    founded: 1921,
    description: "Stunning club overlooking the Perth city skyline across the Swan River. Two greens and a popular function venue.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["city-skyline-views", "swan-river", "functions"],
  },
  {
    id: "wa-fremantle",
    name: "Fremantle Bowling Club",
    city: "Fremantle",
    stateCode: "WA",
    state: "Western Australia",
    region: "Fremantle",
    address: "1 Ellen St, Fremantle WA 6160",
    lat: -32.0569,
    lng: 115.7456,
    phone: "(08) 9335 2221",
    memberCount: 160,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1895,
    description: "Historic port-city bowling club in the heart of Fremantle. Walking distance from the Cappuccino Strip and Fremantle Markets.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["fremantle", "historic", "port-city"],
  },
  {
    id: "wa-mandurah",
    name: "Mandurah Bowling & Recreation Club",
    city: "Mandurah",
    stateCode: "WA",
    state: "Western Australia",
    region: "Peel",
    address: "55 Ormsby Tce, Mandurah WA 6210",
    lat: -32.5289,
    lng: 115.7222,
    phone: "(08) 9535 2672",
    memberCount: 190,
    greens: 2,
    rinks: 14,
    surfaceType: "synthetic",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Disabled Access"],
    founded: 1948,
    description: "Major Peel region bowling club on the Mandurah Estuary. Modern synthetic greens and a thriving social scene.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/mandurahibowls",
    socialMedia: { facebook: "mandurahibowls" },
    tags: ["peel", "estuary", "synthetic", "large-club"],
  },
  {
    id: "wa-bunbury",
    name: "Bunbury Bowling Club",
    city: "Bunbury",
    stateCode: "WA",
    state: "Western Australia",
    region: "South West",
    address: "49 Stirling St, Bunbury WA 6230",
    lat: -33.3311,
    lng: 115.6411,
    phone: "(08) 9721 3422",
    memberCount: 130,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1910,
    description: "South West regional bowling club with well-maintained greens in Bunbury's centre.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["south-west", "regional", "country"],
  },
  {
    id: "wa-geraldton",
    name: "Geraldton Bowling Club",
    city: "Geraldton",
    stateCode: "WA",
    state: "Western Australia",
    region: "Mid West",
    address: "Shenton St, Geraldton WA 6530",
    lat: -28.7744,
    lng: 114.6142,
    phone: "(08) 9921 1777",
    memberCount: 100,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1905,
    description: "Mid West WA bowling club in the coastal city of Geraldton. Year-round play in warm Indian Ocean conditions.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["mid-west", "coastal", "year-round"],
  },
  {
    id: "wa-albany",
    name: "Albany Bowling Club",
    city: "Albany",
    stateCode: "WA",
    state: "Western Australia",
    region: "Great Southern",
    address: "31 Middleton Rd, Albany WA 6330",
    lat: -35.0228,
    lng: 117.8814,
    phone: "(08) 9841 3422",
    memberCount: 110,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1888,
    description: "One of WA's oldest bowling clubs in the Great Southern port city of Albany.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["great-southern", "historic", "port-city"],
  },
  // === TASMANIA (5) ===
  {
    id: "tas-hobart-sandy-bay",
    name: "Sandy Bay Bowling Club",
    city: "Hobart",
    stateCode: "TAS",
    state: "Tasmania",
    region: "Greater Hobart",
    address: "10 Long Point Rd, Sandy Bay TAS 7005",
    lat: -42.8986,
    lng: 147.3272,
    website: "https://www.sandybaybowls.com.au",
    phone: "(03) 6223 2741",
    email: "info@sandybaybowls.com.au",
    memberCount: 180,
    greens: 2,
    rinks: 12,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Disabled Access"],
    founded: 1876,
    description: "Tasmania's premier bowling club with stunning views of the Derwent River and Mount Wellington. Two championship-quality natural greens.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/sandybaybowls",
    socialMedia: { facebook: "sandybaybowls" },
    tags: ["derwent-river", "mount-wellington-views", "premier", "historic"],
    isFeatured: true,
    metaTitle: "Sandy Bay Bowling Club - Hobart's Premier Lawn Bowls",
    metaDescription: "Tasmania's premier bowling club with Derwent River views. Pennant, social bowls, barefoot bowls in Sandy Bay, Hobart.",
  },
  {
    id: "tas-launceston",
    name: "Launceston Bowling Club",
    city: "Launceston",
    stateCode: "TAS",
    state: "Tasmania",
    region: "Northern Tasmania",
    address: "8 High St, Launceston TAS 7250",
    lat: -41.4400,
    lng: 147.1350,
    phone: "(03) 6331 3611",
    memberCount: 150,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1865,
    description: "One of Australia's oldest bowling clubs in the heart of Launceston. Two well-maintained greens near the Tamar River.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["historic", "oldest", "tamar-river", "northern-tasmania"],
  },
  {
    id: "tas-devonport",
    name: "Devonport Bowling Club",
    city: "Devonport",
    stateCode: "TAS",
    state: "Tasmania",
    region: "North West Tasmania",
    address: "72 North Fenton St, Devonport TAS 7310",
    lat: -41.1800,
    lng: 146.3567,
    phone: "(03) 6424 2977",
    memberCount: 110,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1905,
    description: "North-west Tasmania's main bowling club near the Spirit of Tasmania terminal. Two greens in a scenic coastal setting.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["north-west", "coastal", "spirit-of-tasmania"],
  },
  {
    id: "tas-burnie",
    name: "Burnie Bowling Club",
    city: "Burnie",
    stateCode: "TAS",
    state: "Tasmania",
    region: "North West Tasmania",
    address: "8 West Park Gr, Burnie TAS 7320",
    lat: -41.0567,
    lng: 145.9033,
    phone: "(03) 6431 2755",
    memberCount: 90,
    greens: 1,
    rinks: 8,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1912,
    description: "Community bowling club on Tasmania's north-west coast with ocean views from the green.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["north-west", "coastal", "community"],
  },
  {
    id: "tas-kingston",
    name: "Kingston Beach Bowling Club",
    city: "Kingston",
    stateCode: "TAS",
    state: "Tasmania",
    region: "Greater Hobart",
    address: "6 Beach Rd, Kingston Beach TAS 7050",
    lat: -42.9833,
    lng: 147.3000,
    phone: "(03) 6229 6233",
    memberCount: 100,
    greens: 1,
    rinks: 8,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1935,
    description: "Relaxed beachside bowling club south of Hobart. Popular summer barefoot bowls overlooking Kingston Beach.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["beachside", "south-hobart", "barefoot-bowls"],
  },
  // === NORTHERN TERRITORY (3) ===
  {
    id: "nt-darwin",
    name: "Darwin Bowling Club",
    city: "Darwin",
    stateCode: "NT",
    state: "Northern Territory",
    region: "Top End",
    address: "18 Gilruth Ave, The Gardens NT 0820",
    lat: -12.4434,
    lng: 130.8456,
    website: "https://www.darwinbowlingclub.com.au",
    phone: "(08) 8981 6866",
    email: "info@darwinbowlingclub.com.au",
    memberCount: 160,
    greens: 2,
    rinks: 12,
    surfaceType: "synthetic",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Night Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Disabled Access"],
    founded: 1938,
    description: "The Top End's premier bowling club overlooking Fannie Bay. Synthetic greens for year-round tropical play with spectacular sunset sessions.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/darwinbowlingclub",
    socialMedia: { facebook: "darwinbowlingclub" },
    tags: ["tropical", "top-end", "sunset-sessions", "fannie-bay"],
    isFeatured: true,
    metaTitle: "Darwin Bowling Club - Top End Lawn Bowls",
    metaDescription: "Darwin's premier bowling club at Fannie Bay. Tropical bowls, sunset sessions, barefoot bowls and corporate events.",
  },
  {
    id: "nt-alice-springs",
    name: "Alice Springs Bowling Club",
    city: "Alice Springs",
    stateCode: "NT",
    state: "Northern Territory",
    region: "Red Centre",
    address: "Traeger Ave, Alice Springs NT 0870",
    lat: -23.6980,
    lng: 133.8807,
    phone: "(08) 8952 2844",
    memberCount: 80,
    greens: 1,
    rinks: 8,
    surfaceType: "synthetic",
    activities: ["Social Bowls", "Barefoot Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1948,
    description: "Outback bowling club in the heart of the Red Centre. Synthetic greens handle the desert conditions for year-round play under the MacDonnell Ranges.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["outback", "red-centre", "macdonnell-ranges", "desert"],
  },
  {
    id: "nt-katherine",
    name: "Katherine Bowling Club",
    city: "Katherine",
    stateCode: "NT",
    state: "Northern Territory",
    region: "Big Rivers",
    address: "Stuart Hwy, Katherine NT 0850",
    lat: -14.4667,
    lng: 132.2667,
    phone: "(08) 8972 2377",
    memberCount: 50,
    greens: 1,
    rinks: 6,
    surfaceType: "synthetic",
    activities: ["Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1960,
    description: "Remote Top End bowling club serving the Katherine community. Synthetic green for dry-season play.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["remote", "top-end", "community"],
  },
  // === AUSTRALIAN CAPITAL TERRITORY (5) ===
  {
    id: "act-canberra-city",
    name: "Canberra City Bowling Club",
    city: "Canberra",
    stateCode: "ACT",
    state: "Australian Capital Territory",
    region: "Inner Canberra",
    address: "1 Binara St, Canberra ACT 2601",
    lat: -35.2809,
    lng: 149.1300,
    website: "https://www.canberracitybowls.com.au",
    phone: "(02) 6248 8444",
    email: "info@canberracitybowls.com.au",
    memberCount: 200,
    greens: 2,
    rinks: 12,
    surfaceType: "synthetic",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Corporate Events", "Night Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar & Bistro", "Function Rooms", "Parking", "Disabled Access"],
    founded: 1930,
    description: "The capital's premier bowling club in the Civic precinct. Modern synthetic greens with night lighting for year-round play.",
    status: "active",
    hasOnlinePresence: true,
    facebookUrl: "https://facebook.com/canberracitybowls",
    socialMedia: { facebook: "canberracitybowls" },
    tags: ["civic", "capital", "night-bowls", "corporate-events"],
    isFeatured: true,
    metaTitle: "Canberra City Bowling Club - Capital Lawn Bowls",
    metaDescription: "Canberra's premier bowling club in Civic. Synthetic greens, night bowls, barefoot bowls and corporate events.",
  },
  {
    id: "act-tuggeranong",
    name: "Tuggeranong Vikings Bowling Club",
    city: "Tuggeranong",
    stateCode: "ACT",
    state: "Australian Capital Territory",
    region: "South Canberra",
    address: "Ricardo St, Wanniassa ACT 2903",
    lat: -35.3889,
    lng: 149.0833,
    phone: "(02) 6293 7200",
    memberCount: 160,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking", "Disabled Access"],
    founded: 1978,
    description: "South Canberra's leading bowling club within the Tuggeranong Vikings sporting complex.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["vikings", "south-canberra", "sporting-complex"],
  },
  {
    id: "act-belconnen",
    name: "Belconnen Bowling Club",
    city: "Belconnen",
    stateCode: "ACT",
    state: "Australian Capital Territory",
    region: "North Canberra",
    address: "Chandler St, Belconnen ACT 2617",
    lat: -35.2389,
    lng: 149.0644,
    phone: "(02) 6251 3411",
    memberCount: 140,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching", "Tournaments"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1975,
    description: "North Canberra bowling club with two well-maintained greens and a friendly atmosphere.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["north-canberra", "community", "pennant"],
  },
  {
    id: "act-weston-creek",
    name: "Weston Creek Bowling Club",
    city: "Weston Creek",
    stateCode: "ACT",
    state: "Australian Capital Territory",
    region: "West Canberra",
    address: "Parkinson St, Weston ACT 2611",
    lat: -35.3333,
    lng: 149.0500,
    phone: "(02) 6288 4622",
    memberCount: 100,
    greens: 1,
    rinks: 8,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar", "Parking"],
    founded: 1982,
    description: "Friendly west Canberra bowling club with a single beautifully maintained green and strong community ties.",
    status: "active",
    hasOnlinePresence: false,
    tags: ["west-canberra", "community", "friendly"],
  },
  {
    id: "act-queanbeyan",
    name: "Queanbeyan Bowling Club",
    city: "Queanbeyan",
    stateCode: "ACT",
    state: "Australian Capital Territory",
    region: "ACT Region",
    address: "94 Crawford St, Queanbeyan NSW 2620",
    lat: -35.3531,
    lng: 149.2294,
    phone: "(02) 6297 1466",
    memberCount: 130,
    greens: 2,
    rinks: 10,
    surfaceType: "natural_grass",
    activities: ["Pennant/Competition", "Social Bowls", "Barefoot Bowls", "Coaching"],
    facilities: ["Clubhouse", "Bar & Bistro", "Parking"],
    founded: 1922,
    description: "Historic bowling club on the edge of the ACT. Serves both Queanbeyan and Canberra bowlers with two excellent greens.",
    status: "active",
    hasOnlinePresence: true,
    tags: ["act-region", "cross-border", "historic"],
  },
];

// Helper functions
export function getClubById(id: string): ClubData | undefined {
  return CLUBS.find((c) => c.id === id);
}

export function getClubsByState(stateCode: string): ClubData[] {
  return CLUBS.filter((c) => c.stateCode === stateCode);
}

export function getClubsByRegion(region: string): ClubData[] {
  return CLUBS.filter((c) => c.region === region);
}

export function getStatesWithClubs(): string[] {
  return [...new Set(CLUBS.map((c) => c.stateCode))].sort();
}

export function searchClubs(query: string): ClubData[] {
  const q = query.toLowerCase();
  return CLUBS.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.city.toLowerCase().includes(q) ||
      c.state.toLowerCase().includes(q) ||
      c.description?.toLowerCase().includes(q) ||
      c.tags.some((t) => t.includes(q)) ||
      c.region?.toLowerCase().includes(q)
  );
}

export function getClubStats() {
  const states = getStatesWithClubs();
  const regions = [...new Set(CLUBS.filter((c) => c.region).map((c) => c.region))];
  const totalMembers = CLUBS.reduce((sum, c) => sum + (c.memberCount ?? 0), 0);
  return {
    totalClubs: CLUBS.length,
    totalStates: states.length,
    totalRegions: regions.length,
    totalMembers,
    activeClubs: CLUBS.filter((c) => c.status === "active").length,
    seasonalClubs: CLUBS.filter((c) => c.status === "seasonal").length,
  };
}
