/**
 * Seed script to populate the clubs table with ALL researched US lawn bowling clubs.
 * Data sourced from 4 regional research files (98 clubs total):
 *   - USA_CLUBS_WEST.md (57 clubs)
 *   - USA_CLUBS_EAST.md (13 clubs)
 *   - USA_CLUBS_SOUTH.md (19 clubs)
 *   - USA_CLUBS_MIDWEST.md (9 clubs)
 *
 * Usage: npx tsx scripts/seed-clubs.ts
 * Requires: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env.local
 */

import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

function slugify(name: string, city: string, stateCode: string): string {
  return `${name}-${city}-${stateCode}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

interface ClubSeed {
  name: string;
  city: string;
  state: string;
  state_code: string;
  region: "west" | "east" | "south" | "midwest";
  address?: string;
  website?: string;
  phone?: string;
  email?: string;
  member_count?: number;
  greens?: number;
  rinks?: number;
  surface_type?: string;
  division?: string;
  activities?: string[];
  facilities?: string[];
  founded?: number;
  description?: string;
  status?: string;
  has_online_presence?: boolean;
  facebook_url?: string;
  instagram_url?: string;
  tags?: string[];
}

// ============================================================
// COMPLETE CLUB DATA — All 98 clubs from 4 regional research files
// ============================================================
const clubs: ClubSeed[] = [
  // =====================================================================
  // WEST REGION — 57 clubs
  // =====================================================================

  // === ARIZONA (7 clubs) ===
  {
    name: "Bell Lawn Bowls Club",
    city: "Sun City",
    state: "Arizona",
    state_code: "AZ",
    region: "west",
    address: "Bell Recreation Center, 16820 N. 99th Ave., Sun City, AZ 85351",
    website: "https://suncityaz.org/recreation/clubs/bell-lawn-bowls/",
    phone: "623-583-4432",
    email: "cblbc@gmail.com",
    greens: 2,
    rinks: 16,
    surface_type: "synthetic",
    division: "south_central",
    activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking", "Restrooms"],
    description: "Part of Sun City's five-club lawn bowling complex. Hosted U.S. Open of Lawn Bowling.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community", "year-round"],
  },
  {
    name: "Fairway/Mountain View Lawn Bowls Club",
    city: "Sun City",
    state: "Arizona",
    state_code: "AZ",
    region: "west",
    address: "Fairway Recreation Center, 10600 W. Peoria Ave., Sun City, AZ",
    website: "https://suncityaz.org/recreation/clubs/fairway-mountain-view-lawn-bowls/",
    greens: 2,
    surface_type: "synthetic",
    division: "south_central",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    description: "Combined club operating across two separate recreation centers.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community"],
  },
  {
    name: "Johnson Lawn Bowls Club",
    city: "Sun City West",
    state: "Arizona",
    state_code: "AZ",
    region: "west",
    address: "R.H. Johnson Recreation Center, 19803 R.H. Johnson Blvd., Sun City West, AZ",
    website: "https://lawnbowls.scwclubs.com/",
    greens: 4,
    rinks: 32,
    surface_type: "synthetic",
    division: "south_central",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking", "Restrooms"],
    description: "One of the largest facilities in the US with 4 greens. Hosted international competitions.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community", "large-facility", "year-round"],
  },
  {
    name: "Lakeview Lawn Bowls Club",
    city: "Sun City",
    state: "Arizona",
    state_code: "AZ",
    region: "west",
    address: "Lakeview Recreation Center, 10626 W. Thunderbird Blvd., Sun City, AZ",
    website: "https://suncityaz.org/recreation/clubs/lakeview-lawn-bowls/",
    greens: 2,
    surface_type: "synthetic",
    division: "south_central",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse", "Parking"],
    description: "Scenic lakeside setting with lighted greens for evening bowling.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community", "lake-view", "night-bowling"],
  },
  {
    name: "Leisure World Lawn Bowling Club",
    city: "Mesa",
    state: "Arizona",
    state_code: "AZ",
    region: "west",
    address: "Leisure World Community Resort, 908 S. Power Rd., Mesa, AZ",
    greens: 1,
    surface_type: "unknown",
    division: "south_central",
    activities: ["Social Bowls"],
    facilities: ["Parking"],
    description: "Green prominently located at resort entrance. Daily bowling year-round.",
    status: "active",
    has_online_presence: false,
    tags: ["55+", "retirement-community", "year-round"],
  },
  {
    name: "Oakmont Lawn Bowls Club",
    city: "Sun City",
    state: "Arizona",
    state_code: "AZ",
    region: "west",
    address: "Oakmont Recreation Center, 10725 W. Oakmont Dr., Sun City, AZ",
    website: "https://suncityaz.org/recreation/clubs/oakmont-lawn-bowls/",
    greens: 2,
    surface_type: "synthetic",
    division: "south_central",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    description: "Original Sun City lawn bowling location. Hosted North American Challenge.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community", "historic"],
  },
  {
    name: "Paradise RV Resort Lawn Bowls Club",
    city: "Sun City",
    state: "Arizona",
    state_code: "AZ",
    region: "west",
    address: "Paradise RV Resort, 10950 W. Union Hills Dr., Sun City, AZ 85373",
    phone: "623-977-0344",
    greens: 1,
    surface_type: "unknown",
    division: "south_central",
    activities: ["Social Bowls", "Coaching/Lessons"],
    facilities: ["Parking"],
    description: "RV resort setting catering to seasonal/snowbird visitors.",
    status: "seasonal",
    has_online_presence: false,
    tags: ["55+", "rv-resort", "seasonal"],
  },

  // === CALIFORNIA — Northern (PIMD, 12 clubs) ===
  {
    name: "Berkeley Lawn Bowling Club",
    city: "Berkeley",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "2270 Acton St., Berkeley, CA 94702",
    website: "https://berkeleylawnbowling.org/",
    phone: "510-841-2174",
    email: "berkeleylawnbowling@gmail.com",
    member_count: 95,
    greens: 2,
    surface_type: "natural_grass",
    division: "pacific_intermountain",
    activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons", "Open Days"],
    facilities: ["Clubhouse"],
    founded: 1928,
    description: "Non-profit since 1963. Diverse membership of retirees, grad students, writers, golfers.",
    status: "active",
    has_online_presence: true,
    tags: ["public-park", "beginner-friendly", "diverse"],
  },
  {
    name: "Del Mesa Carmel Lawn Bowling Club",
    city: "Carmel",
    state: "California",
    state_code: "CA",
    region: "west",
    website: "http://dmclbc.org/",
    email: "DMCLawnBowling@gmail.com",
    member_count: 55,
    greens: 1,
    surface_type: "natural_grass",
    division: "pacific_intermountain",
    activities: ["Social Bowls"],
    facilities: ["Clubhouse"],
    description: "Active since late 1960s. Only regulation green in Monterey County. Open to non-residents.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community"],
  },
  {
    name: "Fresno Lawn Bowls Club",
    city: "Fresno",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "Holmes Park, Fresno, CA",
    website: "http://www.fresnolawnbowls.org/",
    phone: "559-224-2240",
    greens: 1,
    surface_type: "natural_grass",
    division: "pacific_intermountain",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Parking"],
    description: "Only lawn bowling club in California's Central Valley.",
    status: "active",
    has_online_presence: true,
    tags: ["public-park"],
  },
  {
    name: "Oakland Lawn Bowling Club",
    city: "Oakland",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "660 Bellevue Ave., Lakeside Park, Oakland, CA 94610",
    website: "https://www.oaklandlawnbowlingclub.com/",
    phone: "510-625-9937",
    greens: 2,
    surface_type: "natural_grass",
    division: "pacific_intermountain",
    activities: ["Social Bowls", "League/Pennant", "Corporate Events"],
    facilities: ["Clubhouse"],
    founded: 1903,
    description: "Founded 1903 by Scottish bowlers. Beautiful Lake Merritt location.",
    status: "active",
    has_online_presence: true,
    tags: ["historic", "public-park", "lake-view"],
  },
  {
    name: "Oakmont Lawn Bowling Club",
    city: "Santa Rosa",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "310 White Oak Dr., Santa Rosa, CA 95409",
    website: "https://www.oakmontlawnbowling.com/",
    phone: "707-539-1511",
    greens: 1,
    surface_type: "synthetic",
    division: "pacific_intermountain",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse"],
    description: "Hosted North American Challenge (1998). Oakmont Village community.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community"],
  },
  {
    name: "Palo Alto Lawn Bowls Club",
    city: "Palo Alto",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "474 Embarcadero Rd., Palo Alto, CA",
    website: "https://www.palbc.org/",
    greens: 1,
    rinks: 8,
    surface_type: "natural_grass",
    division: "pacific_intermountain",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking", "Restrooms"],
    founded: 1933,
    description: "Est. 1933. Clubhouse with full kitchen and locker rooms.",
    status: "active",
    has_online_presence: true,
    tags: ["beginner-friendly"],
  },
  {
    name: "Rossmoor Lawn Bowling Club",
    city: "Walnut Creek",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "Hillside Clubhouse, 3400 Lower Golden Rain Rd., Walnut Creek, CA 94595",
    website: "https://www.rlbc.net/",
    phone: "925-289-8011",
    greens: 3,
    rinks: 24,
    surface_type: "natural_grass",
    division: "pacific_intermountain",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking", "Restrooms"],
    founded: 1967,
    description: "3 greens with 8 rinks each. Certification required before play.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community", "large-facility"],
  },
  {
    name: "San Francisco Lawn Bowling Club",
    city: "San Francisco",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "Bowling Green Dr., Golden Gate Park, San Francisco, CA",
    website: "https://www.sflbc.org/",
    member_count: 130,
    greens: 3,
    surface_type: "natural_grass",
    division: "pacific_intermountain",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Open Days"],
    facilities: ["Clubhouse", "Parking", "Restrooms"],
    founded: 1901,
    description: "Oldest public lawn bowling club in America (1901). 1915 Edwardian clubhouse is a SF City Landmark.",
    status: "active",
    has_online_presence: true,
    tags: ["historic", "public-park", "beginner-friendly", "free-lessons"],
  },
  {
    name: "San Jose Lawn Bowls Club",
    city: "San Jose",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "Willow Street Frank Bramhall Park, San Jose, CA",
    website: "https://sjlbc-home.org/",
    greens: 1,
    surface_type: "synthetic",
    division: "pacific_intermountain",
    activities: ["Social Bowls", "Coaching/Lessons", "Tournaments", "Corporate Events"],
    facilities: ["Parking"],
    description: "2017 city renovation created world-class championship synthetic green.",
    status: "active",
    has_online_presence: true,
    tags: ["public-park", "championship-green"],
  },
  {
    name: "Santa Clara Lawn Bowls Club",
    city: "Santa Clara",
    state: "California",
    state_code: "CA",
    region: "west",
    website: "https://www.santaclaralawnbowls.org/",
    phone: "408-204-0154",
    greens: 1,
    surface_type: "natural_grass",
    division: "pacific_intermountain",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Parking"],
    description: "Active evening bowling schedule in summer.",
    status: "active",
    has_online_presence: true,
    tags: ["public-park"],
  },
  {
    name: "Santa Cruz Lawn Bowls Club",
    city: "Santa Cruz",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "137 Dakota Ave., San Lorenzo Park, Santa Cruz, CA 95060",
    website: "https://www.sclawnbowls.org/",
    phone: "831-469-4807",
    greens: 1,
    surface_type: "synthetic",
    division: "pacific_intermountain",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Parking"],
    description: "Beautiful downtown location close to ocean and bay. Artificial world-class green.",
    status: "active",
    has_online_presence: true,
    tags: ["public-park", "coastal"],
  },
  {
    name: "Sunnyvale Lawn Bowls Club",
    city: "Sunnyvale",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "Vargas Lawn Bowling Green, Martin Murphy Jr. Historical Park, Sunnyvale, CA",
    website: "https://www.svlbc.org/",
    phone: "408-730-7356",
    greens: 1,
    surface_type: "natural_grass",
    division: "pacific_intermountain",
    activities: ["Social Bowls", "Coaching/Lessons", "Tournaments"],
    facilities: ["Parking"],
    description: "Located in historic park setting.",
    status: "active",
    has_online_presence: true,
    tags: ["public-park", "historic"],
  },

  // === CALIFORNIA — Southern (Southwest Division, 22 clubs) ===
  {
    name: "Beverly Hills Lawn Bowling Club",
    city: "Beverly Hills",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "Roxbury Memorial Park, 471 S. Roxbury Dr., Beverly Hills, CA 90210",
    website: "https://bhlbc.com/",
    email: "info@bhlbc.com",
    phone: "323-405-1147",
    greens: 2,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Restrooms"],
    founded: 1926,
    description: "Celebrity history including Walt Disney as a member. Rebuilt community center (2013-2014).",
    status: "active",
    has_online_presence: true,
    tags: ["historic", "celebrity-history"],
  },
  {
    name: "Cambria Lawn Bowls Club",
    city: "Cambria",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "Joslyn Recreation Center, 950 Main St., Cambria, CA 93428",
    email: "cambrialbc@gmail.com",
    greens: 1,
    surface_type: "synthetic",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse"],
    founded: 1968,
    description: "Northernmost club in Southwest Division. Central Coast location.",
    status: "active",
    has_online_presence: true,
    facebook_url: "https://www.facebook.com/CambriaLawnBowlsClub",
    tags: ["coastal"],
  },
  {
    name: "Casta del Sol Lawn Bowling Club",
    city: "Mission Viejo",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "24351 Via Albeniz, Mission Viejo, CA",
    greens: 1,
    surface_type: "synthetic",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse"],
    description: "Private 55+ gated community club.",
    status: "unverified",
    has_online_presence: false,
    tags: ["55+", "retirement-community"],
  },
  {
    name: "Coronado Lawn Bowling Club",
    city: "Coronado",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "1019 7th St., Coronado, CA",
    website: "https://coronadolawnbowling.com/",
    phone: "619-319-5509",
    greens: 1,
    rinks: 6,
    surface_type: "synthetic",
    division: "southwest",
    activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1935,
    description: "World-class artificial green dedicated March 2010. New Spreckels Center opened 2017.",
    status: "active",
    has_online_presence: true,
    tags: ["coastal", "year-round"],
  },
  {
    name: "Friendly Valley Lawn Bowls Club",
    city: "Newhall",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "19345 Avenue of the Oaks, Newhall, CA 91321",
    website: "https://friendlyvalley.com/lawn-bowls",
    phone: "805-252-3223",
    greens: 1,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse"],
    founded: 1966,
    description: "Private 55+ golf-themed community. Greens dedicated 1977.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community"],
  },
  {
    name: "Hemet-Joslyn Lawn Bowls Club",
    city: "Hemet",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "Gibbel Park, 2625 W. Devonshire Ave., Hemet, CA 92543",
    email: "hemetlawnbowlsclub@gmail.com",
    phone: "951-652-0981",
    greens: 1,
    surface_type: "synthetic",
    division: "southwest",
    activities: ["Social Bowls", "League/Pennant"],
    facilities: ["Parking"],
    founded: 1976,
    description: "Welcomes Canadian snowbird visitors. Greens dedicated May 1977.",
    status: "active",
    has_online_presence: false,
    tags: ["snowbird-friendly"],
  },
  {
    name: "Hermosa Beach Lawn Bowling Club",
    city: "Hermosa Beach",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "861 Valley Dr., Hermosa Beach, CA",
    website: "https://hblbc.org/",
    phone: "310-372-9080",
    greens: 1,
    surface_type: "unknown",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Parking"],
    founded: 1936,
    description: "Founded 1936 by former Hermosa Beach Mayor John Clark.",
    status: "active",
    has_online_presence: true,
    instagram_url: "https://instagram.com/hermosalbc",
    tags: ["coastal", "beach-community"],
  },
  {
    name: "Holmby Park Lawn Bowling Club",
    city: "Los Angeles",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "646 Comstock Ave., Los Angeles, CA 90024",
    website: "https://www.losangeleslawnbowling.com/",
    phone: "424-425-5996",
    member_count: 130,
    greens: 2,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Coaching/Lessons", "Tournaments", "Open Days"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1927,
    description: "130 members from 17 countries. $95/year dues unchanged since 2008. Gorgeous Holmby Hills setting.",
    status: "active",
    has_online_presence: true,
    tags: ["international", "beginner-friendly", "year-round"],
  },
  {
    name: "Laguna Beach Lawn Bowling Club",
    city: "Laguna Beach",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "455 Cliff Dr., Heisler Park, Laguna Beach, CA",
    website: "https://lagunabeachlawnbowlingclub.com/",
    member_count: 376,
    greens: 2,
    rinks: 16,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Open Days"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1931,
    description: "LARGEST lawn bowling club in the USA (376 members). Ocean-view setting in Heisler Park. 'Lawn Bowling Capital of the United States' (city declaration 1957).",
    status: "active",
    has_online_presence: true,
    tags: ["largest-in-usa", "ocean-view", "year-round", "beginner-friendly"],
  },
  {
    name: "Laguna Woods Lawn Bowling Club",
    city: "Laguna Woods",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "24112 Moulton Parkway (Gate #12), Laguna Woods, CA 92637",
    website: "https://www.lwlbc.org/",
    phone: "949-951-3027",
    greens: 2,
    surface_type: "synthetic",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse"],
    description: "Hosted North American Challenge (2019) and US Open (2023). 7-day-a-week schedule.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community", "year-round"],
  },
  {
    name: "Long Beach Lawn Bowling Club",
    city: "Long Beach",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "1109 Federation Dr., Long Beach, CA 90804",
    website: "https://longbeachlbc.com/",
    phone: "562-433-9063",
    member_count: 100,
    greens: 3,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1928,
    description: "3 greens. Home to 2 past National Champions. Bowls USA Hall of Fame member.",
    status: "active",
    has_online_presence: true,
    tags: ["year-round", "competitive", "large-facility"],
  },
  {
    name: "MacKenzie Park Lawn Bowls Club",
    city: "Santa Barbara",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "MacKenzie Park, Los Positas Rd., Santa Barbara, CA",
    website: "https://mplbc.com/",
    phone: "805-563-2143",
    email: "mackenzieparklbc@gmail.com",
    greens: 2,
    rinks: 16,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    description: "Modern clubhouse with kitchen. One of two lawn bowling clubs in Santa Barbara.",
    status: "active",
    has_online_presence: true,
    tags: ["year-round"],
  },
  {
    name: "Newport Harbor Lawn Bowling Club",
    city: "Corona del Mar",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "1550 Crown Dr. North, Corona del Mar, CA 92625",
    website: "https://www.newportharborlbc.com/",
    phone: "949-640-1022",
    greens: 2,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Open Days"],
    facilities: ["Clubhouse", "Parking"],
    description: "Described as one of the largest and most beautiful clubs in the US.",
    status: "active",
    has_online_presence: true,
    tags: ["coastal", "year-round", "beginner-friendly"],
  },
  {
    name: "Oaks North Lawn Bowling Club",
    city: "San Diego",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "12578 Oaks North Dr., San Diego, CA 92128",
    website: "https://www.oaksnorthcommunity.org/lawn-bowling/",
    phone: "858-487-4832",
    greens: 1,
    surface_type: "synthetic",
    division: "southwest",
    activities: ["Social Bowls", "League/Pennant", "Tournaments"],
    facilities: ["Clubhouse"],
    founded: 1974,
    description: "Active since 1974. Second largest recreational group at community center.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community"],
  },
  {
    name: "Oxnard-Joslyn Lawn Bowls Club",
    city: "Oxnard",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "350 N. C St., Wilson Park, Oxnard, CA 93030",
    website: "https://www.oxnardlbc.com/",
    phone: "805-385-8034",
    greens: 1,
    surface_type: "synthetic",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    description: "Part of Joslyn Center network. Downtown location in Wilson Park.",
    status: "active",
    has_online_presence: true,
    tags: ["public-park"],
  },
  {
    name: "Pasadena Lawn Bowling Club",
    city: "Pasadena",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "275 S. Raymond Ave., Central Park, Pasadena, CA",
    website: "https://www.plbcc.org/",
    greens: 2,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Open Days"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1921,
    description: "OLDEST continuously operating lawn bowling club in USA (est. 1921). 'Birthplace of California Lawn Bowling'. Hosts Rose Lawn Bowl on New Year's Eve.",
    status: "active",
    has_online_presence: true,
    tags: ["historic", "oldest-in-usa", "year-round"],
  },
  {
    name: "Pomona Lawn Bowling Club",
    city: "Pomona",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "451 E. Arrow Highway, Pomona, CA 91767",
    website: "http://pomonalawnbowlingclub.com/",
    phone: "909-625-5532",
    greens: 1,
    surface_type: "unknown",
    division: "southwest",
    activities: ["Social Bowls"],
    facilities: ["Parking"],
    description: "Active for 80+ years in city park setting.",
    status: "active",
    has_online_presence: true,
    tags: ["public-park"],
  },
  {
    name: "Redlands Lawn Bowling Club",
    city: "Redlands",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "Sylvan Park, 411 N. University St., Redlands, CA",
    website: "https://www.redlandslawnbowlingclub.com/",
    phone: "909-792-4874",
    member_count: 45,
    greens: 2,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1921,
    description: "Second oldest in SoCal. Mission Revival clubhouse (1926) is a designated historic resource. 'Rock and Bowl' evening events.",
    status: "active",
    has_online_presence: true,
    tags: ["historic", "year-round"],
  },
  {
    name: "Riverside Lawn Bowling Club",
    city: "Riverside",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "4020 Bowling Green Dr., Fairmount Park, Riverside, CA",
    website: "https://riversidelawnbowlingclub.godaddysites.com/",
    phone: "951-784-7602",
    greens: 2,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1926,
    description: "Celebrating 100th anniversary in 2026. In historic Fairmount Park.",
    status: "active",
    has_online_presence: true,
    tags: ["historic", "public-park", "beginner-friendly"],
  },
  {
    name: "San Diego Lawn Bowling Club",
    city: "San Diego",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "2125 Park Blvd., Balboa Park, San Diego, CA 92134",
    website: "https://sandiegolawnbowling.org/",
    phone: "619-238-5457",
    member_count: 100,
    greens: 2,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments", "Junior Programs", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1932,
    description: "Iconic Balboa Park location. Produced numerous national and international champions. Youth membership from age 12.",
    status: "active",
    has_online_presence: true,
    instagram_url: "https://instagram.com/sandiegolawnbowling",
    tags: ["balboa-park", "year-round", "beginner-friendly", "junior-programs"],
  },
  {
    name: "Santa Ana Lawn Bowling Club",
    city: "Santa Ana",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "510 E. Memory Lane, Santiago Park, Santa Ana, CA 92706",
    website: "https://www.santaanalawnbowling.com/",
    greens: 2,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1938,
    description: "Green built 1935-36 with WPA funding. New Deal-era historic connection.",
    status: "active",
    has_online_presence: true,
    tags: ["historic", "public-park"],
  },
  {
    name: "Santa Anita Bowling Green Club",
    city: "Arcadia",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "Arcadia County Park, 405 S. Santa Anita Ave., Arcadia, CA",
    website: "https://santaanitalawnbowling.com/",
    greens: 4,
    rinks: 24,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    description: "ONE OF ONLY 2 CLUBS IN USA WITH 4 GREENS. Night bowling on lighted greens. Near Metro Gold Line.",
    status: "active",
    has_online_presence: true,
    tags: ["large-facility", "night-bowling", "tournament-venue", "year-round"],
  },
  {
    name: "Santa Barbara Lawn Bowls Club",
    city: "Santa Barbara",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "1216 De La Vina St., Santa Barbara, CA 93101",
    website: "https://www.santabarbaralbc.org/",
    email: "sblawnbowlsclub@gmail.com",
    phone: "805-574-0221",
    greens: 1,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Corporate Events"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1937,
    description: "Non-profit co-sponsored by City Parks & Rec. Hybrid Bermuda grass on sand bed.",
    status: "active",
    has_online_presence: true,
    tags: ["year-round", "corporate-events"],
  },
  {
    name: "Santa Monica Lawn Bowls Club",
    city: "Santa Monica",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "Douglas Park, Wilshire Blvd., Santa Monica, CA",
    member_count: 75,
    greens: 1,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1945,
    description: "Est. 1945 (80th anniversary 2025). Laser-leveled hybrid Bermuda on sand.",
    status: "active",
    has_online_presence: false,
    tags: ["public-park", "year-round"],
  },
  {
    name: "Sun City Lawn Bowls Club",
    city: "Menifee",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "26921 Sun City Blvd., Sun City, CA 92586",
    website: "https://www.suncitylawnbowls.com/",
    email: "suncitylawnbowls22@gmail.com",
    greens: 2,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1963,
    description: "First games 1963. Night bowling in summer. Del Webb retirement community.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community", "night-bowling"],
  },
  {
    name: "The Groves Lawn Bowling Club",
    city: "Irvine",
    state: "California",
    state_code: "CA",
    region: "west",
    address: "5200 Irvine Blvd., Irvine, CA 92620",
    email: "woodyjoya@gmail.com",
    greens: 1,
    surface_type: "synthetic",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments", "Corporate Events"],
    facilities: ["Clubhouse"],
    description: "Hosts divisional tournaments. Available for private and corporate events.",
    status: "active",
    has_online_presence: false,
    tags: ["corporate-events"],
  },

  // === COLORADO (1 club) ===
  {
    name: "Washington Park Lawn Bowling Club",
    city: "Denver",
    state: "Colorado",
    state_code: "CO",
    region: "west",
    address: "Washington Park, E. Mississippi Ave. & S. Franklin St., Denver, CO",
    website: "https://washingtonparklawnbowlingclub.com/",
    member_count: 45,
    greens: 1,
    surface_type: "natural_grass",
    division: "southwest",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1924,
    description: "Colorado's ONLY lawn bowling club. Octagonal clubhouse built 1925. Coed since founding.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["historic", "seasonal", "public-park"],
  },

  // === HAWAII (1 club) ===
  {
    name: "Honolulu Lawn Bowls Club",
    city: "Honolulu",
    state: "Hawaii",
    state_code: "HI",
    region: "west",
    address: "Ala Moana Beach Park, Honolulu, HI",
    website: "https://www.honolululawnbowlsclub.com/",
    email: "honolululawnbowlsclub@gmail.com",
    member_count: 50,
    greens: 1,
    surface_type: "natural_grass",
    division: "pacific_intermountain",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Barefoot Bowls"],
    facilities: ["Parking"],
    founded: 1935,
    description: "ONLY lawn bowling green in Hawaii. Constructed 1935-36 by Australian servicemen on crushed coral. First club to admit women.",
    status: "active",
    has_online_presence: true,
    tags: ["year-round", "tropical", "historic", "barefoot-bowls"],
  },

  // === OREGON (2 clubs) ===
  {
    name: "King City Lawn Bowling Club",
    city: "King City",
    state: "Oregon",
    state_code: "OR",
    region: "west",
    website: "http://kingcitylawnbowling.com/",
    greens: 1,
    surface_type: "natural_grass",
    division: "northwest",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse", "Parking"],
    description: "Accessible and affordable club near Portland. Guests can bowl for $10/game.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["55+", "public-park", "seasonal"],
  },
  {
    name: "Portland Lawn Bowling Club",
    city: "Portland",
    state: "Oregon",
    state_code: "OR",
    region: "west",
    address: "7535 SE 23rd Ave., Westmoreland Park, Portland, OR 97202",
    website: "https://www.portlandlawnbowling.com/",
    phone: "971-808-4825",
    greens: 1,
    surface_type: "natural_grass",
    division: "northwest",
    activities: ["Social Bowls", "League/Pennant", "Tournaments", "Open Days", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1933,
    description: "Shares facilities with Portland Petanque Club and Croquet Club. Active community outreach via Meetup and Groupon.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["public-park", "seasonal", "beginner-friendly"],
  },

  // === UTAH (1 club) ===
  {
    name: "SunRiver Lawn Bowling Club",
    city: "St. George",
    state: "Utah",
    state_code: "UT",
    region: "west",
    address: "SunRiver Community Center, 4275 Country Club Dr., St. George, UT 84790",
    greens: 1,
    surface_type: "synthetic",
    division: "south_central",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse", "Parking"],
    description: "Hosts lawn bowls event for Huntsman Senior Games (October annually).",
    status: "active",
    has_online_presence: false,
    tags: ["55+", "retirement-community"],
  },

  // === WASHINGTON (3 clubs) ===
  {
    name: "Jefferson Park Lawn Bowling Club",
    city: "Seattle",
    state: "Washington",
    state_code: "WA",
    region: "west",
    address: "4103 Beacon Ave. S., Seattle, WA",
    website: "https://seattlebowls.org/",
    greens: 2,
    surface_type: "natural_grass",
    division: "northwest",
    activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1945,
    description: "Year-round play. Clubhouse rental program. Seattle Parks & Recreation partnership.",
    status: "active",
    has_online_presence: true,
    tags: ["public-park", "year-round", "beginner-friendly"],
  },
  {
    name: "Spokane Lawn Bowling Club",
    city: "Spokane",
    state: "Washington",
    state_code: "WA",
    region: "west",
    address: "East Mission Park, Spokane, WA",
    website: "https://spokanelawnbowlingclub.weebly.com/",
    phone: "509-434-4791",
    greens: 1,
    surface_type: "natural_grass",
    division: "northwest",
    activities: ["Social Bowls", "Coaching/Lessons"],
    facilities: ["Parking"],
    description: "Seasonal play (late spring through October). Lessons through Parks & Rec department.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["public-park", "seasonal"],
  },
  {
    name: "Tacoma Lawn Bowling Club",
    city: "Tacoma",
    state: "Washington",
    state_code: "WA",
    region: "west",
    address: "Wright Park, Tacoma, WA",
    website: "https://www.tacomabowls.org/",
    email: "tacomalawnbowlingclub@gmail.com",
    greens: 1,
    surface_type: "natural_grass",
    division: "northwest",
    activities: ["Social Bowls", "Tournaments", "Open Days"],
    facilities: ["Parking"],
    founded: 1929,
    description: "Founded 1929. Longtime community fixture. Leases green from Parks Tacoma.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["historic", "public-park", "seasonal"],
  },

  // =====================================================================
  // EAST REGION — 13 clubs
  // =====================================================================

  // === CONNECTICUT (3 clubs) ===
  {
    name: "Fernleigh Lawn Bowling Club",
    city: "West Hartford",
    state: "Connecticut",
    state_code: "CT",
    region: "east",
    address: "35 Lancaster Road, West Hartford, CT",
    website: "http://www.flbc.info/",
    member_count: 60,
    greens: 1,
    rinks: 7,
    surface_type: "natural_grass",
    division: "northeast",
    activities: ["Social Bowls", "League/Pennant", "Tournaments"],
    facilities: ["Clubhouse"],
    founded: 1923,
    description: "One of the longest-running lawn bowling clubs in the Northeast. Evening play with lighting.",
    status: "seasonal",
    has_online_presence: true,
    facebook_url: "https://www.facebook.com/FernleighLawnBowlingClub/",
    tags: ["historic", "seasonal", "night-bowling"],
  },
  {
    name: "Greenwich Lawn Bowling Association",
    city: "Greenwich",
    state: "Connecticut",
    state_code: "CT",
    region: "east",
    address: "Bruce Park, Greenwich, CT",
    greens: 1,
    surface_type: "natural_grass",
    division: "northeast",
    activities: ["Social Bowls", "Open Days"],
    facilities: ["Parking"],
    founded: 1940,
    description: "Located in Greenwich's oldest public park (est. 1908). Green maintained by municipal parks department.",
    status: "seasonal",
    has_online_presence: false,
    tags: ["public-park", "seasonal"],
  },
  {
    name: "Thistle Lawn Bowling Club",
    city: "West Hartford",
    state: "Connecticut",
    state_code: "CT",
    region: "east",
    address: "1561 Asylum Avenue (Elizabeth Park), West Hartford, CT 06117",
    website: "https://thistlelawnbowlinginfo.wordpress.com/",
    email: "ThistleLBC@gmail.com",
    greens: 2,
    surface_type: "natural_grass",
    division: "northeast",
    activities: ["Social Bowls", "League/Pennant"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1913,
    description: "Oldest lawn bowling club in Connecticut (1913). Located in historic Elizabeth Park.",
    status: "seasonal",
    has_online_presence: true,
    facebook_url: "https://www.facebook.com/ThistleLawnBowling/",
    tags: ["historic", "seasonal", "public-park"],
  },

  // === DELAWARE (1 club) ===
  {
    name: "DuPont Country Club Lawn Bowling Club",
    city: "Wilmington",
    state: "Delaware",
    state_code: "DE",
    region: "east",
    address: "DuPont Country Club, Rockland Road, Wilmington, DE",
    website: "https://www.dupontcountryclub.com/",
    phone: "(302) 654-4435",
    surface_type: "natural_grass",
    division: "northeast",
    activities: ["Social Bowls"],
    facilities: ["Clubhouse", "Parking", "Restrooms"],
    founded: 1956,
    description: "Full country club with lawn bowling facilities added in 1956. Originally DuPont Company employee club.",
    status: "unverified",
    has_online_presence: true,
    tags: ["private-club", "country-club"],
  },

  // === MARYLAND (1 club) ===
  {
    name: "Leisure World Lawn Bowls Club",
    city: "Silver Spring",
    state: "Maryland",
    state_code: "MD",
    region: "east",
    address: "3700 Rossmoor Boulevard, Silver Spring, MD 20906",
    website: "https://leisureworldmaryland.com/",
    phone: "301-598-1300",
    greens: 1,
    surface_type: "unknown",
    division: "northeast",
    activities: ["Social Bowls"],
    facilities: ["Clubhouse"],
    description: "Part of Leisure World 55+ community. One of 80+ clubs/organizations in the community.",
    status: "active",
    has_online_presence: false,
    tags: ["55+", "retirement-community"],
  },

  // === NEW JERSEY (1 club) ===
  {
    name: "Essex County Lawn Bowling Club",
    city: "Bloomfield",
    state: "New Jersey",
    state_code: "NJ",
    region: "east",
    address: "Watsessing Park, Bloomfield, NJ",
    website: "https://www.njbowls.com/",
    email: "njbowls1924@gmail.com",
    member_count: 35,
    greens: 1,
    surface_type: "synthetic",
    division: "northeast",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1924,
    description: "Only synthetic surface lawn bowling club in Northern NJ. Celebrated centennial in 2024.",
    status: "active",
    has_online_presence: true,
    facebook_url: "https://www.facebook.com/njbowls/",
    tags: ["synthetic-surface", "historic"],
  },

  // === NEW YORK (2 clubs) ===
  {
    name: "Ausable Lawn Bowling Club",
    city: "St. Huberts",
    state: "New York",
    state_code: "NY",
    region: "east",
    address: "137 Ausable Road, St. Huberts, NY 12943",
    website: "https://www.ausableclub.org/",
    phone: "(518) 576-4411",
    greens: 1,
    surface_type: "natural_grass",
    division: "northeast",
    activities: ["Social Bowls", "Coaching/Lessons"],
    facilities: ["Clubhouse"],
    founded: 1887,
    description: "Ultra-exclusive Adirondack private club dating to 1887. Members and guests only.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["private-club", "seasonal", "exclusive"],
  },
  {
    name: "New York Lawn Bowling Club",
    city: "New York",
    state: "New York",
    state_code: "NY",
    region: "east",
    address: "Central Park, west of 69th Street, New York, NY",
    website: "https://www.nybowls.com/",
    phone: "(212) 920-4352",
    greens: 2,
    surface_type: "natural_grass",
    division: "northeast",
    activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons", "Open Days", "Corporate Events"],
    facilities: ["Clubhouse", "Restrooms"],
    founded: 1926,
    description: "Iconic Central Park location. Premier lawn bowling club in the Eastern US. Free community outreach programs.",
    status: "seasonal",
    has_online_presence: true,
    facebook_url: "https://www.facebook.com/newyorklbc/",
    instagram_url: "https://instagram.com/nybowls",
    tags: ["iconic", "central-park", "corporate-events", "seasonal", "beginner-friendly"],
  },

  // === PENNSYLVANIA (3 clubs) ===
  {
    name: "Buck Hill Falls Lawn Bowling Association",
    city: "Buck Hill Falls",
    state: "Pennsylvania",
    state_code: "PA",
    region: "east",
    address: "Buck Hill Falls community, Barrett Township, PA",
    website: "https://www.buckhillfalls.com/public/community/lawn-bowling",
    greens: 2,
    rinks: 4,
    surface_type: "natural_grass",
    division: "northeast",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1931,
    description: "Has hosted National Finals multiple times. Historical celebrity bowlers including Walt Disney.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["historic", "private-community", "seasonal"],
  },
  {
    name: "Frick Park Lawn Bowling Club",
    city: "Pittsburgh",
    state: "Pennsylvania",
    state_code: "PA",
    region: "east",
    address: "7300 Reynolds Street, Pittsburgh, PA 15208",
    website: "https://www.lawnbowlingpittsburgh.org/",
    email: "info@lawnbowlingpittsburgh.org",
    member_count: 86,
    greens: 2,
    surface_type: "natural_grass",
    division: "northeast",
    activities: ["Social Bowls", "League/Pennant", "Tournaments", "Open Days", "Coaching/Lessons", "Junior Programs"],
    facilities: ["Clubhouse", "Parking", "Restrooms"],
    founded: 1938,
    description: "Best-run club in the Eastern US. Online registration, free Thursday night open bowls, university partnerships, winter indoor short mat program.",
    status: "seasonal",
    has_online_presence: true,
    instagram_url: "https://instagram.com/frickparklawnbowlingclub",
    tags: ["best-run-eastern", "free-lessons", "beginner-friendly", "seasonal", "junior-programs"],
  },
  {
    name: "Skytop Lawn Bowling Club",
    city: "Skytop",
    state: "Pennsylvania",
    state_code: "PA",
    region: "east",
    address: "Skytop Lodge, Route 390, Skytop, PA",
    website: "https://www.skytop.com/activity/lawn-bowling/",
    greens: 1,
    surface_type: "natural_grass",
    division: "northeast",
    activities: ["Social Bowls", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    description: "Luxury Pocono Mountains resort. Complimentary daily classes spring through fall.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["resort", "seasonal", "luxury"],
  },

  // === VIRGINIA (1 club) ===
  {
    name: "Chesapeake Bay Lawn Bowls",
    city: "Hartfield",
    state: "Virginia",
    state_code: "VA",
    region: "east",
    address: "1834 Twiggs Ferry Road, Hartfield, VA 23071",
    website: "https://www.cblawnbowls.com/",
    phone: "(804) 694-9771",
    email: "EdDebH@earthlink.net",
    greens: 1,
    surface_type: "natural_grass",
    division: "northeast",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Open Days"],
    facilities: ["Clubhouse", "Parking"],
    description: "Year-round play (weather permitting). Free lawn bowling on Tuesdays. Successor to historic Williamsburg Inn LBC.",
    status: "active",
    has_online_presence: true,
    tags: ["year-round", "free-lessons", "beginner-friendly"],
  },

  // =====================================================================
  // SOUTH REGION — 19 clubs
  // =====================================================================

  // === FLORIDA (13 clubs) ===
  {
    name: "Clearwater Lawn Bowls Club",
    city: "Clearwater",
    state: "Florida",
    state_code: "FL",
    region: "south",
    address: "1040 Calumet Street, Clearwater, FL 33755",
    website: "https://clearwaterlawnbowlingclub.org/",
    phone: "(727) 641-9144",
    member_count: 100,
    greens: 1,
    rinks: 22,
    surface_type: "synthetic",
    division: "southeast",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons", "Open Days"],
    facilities: ["Clubhouse", "Parking", "Restrooms"],
    founded: 1924,
    description: "22 Har-Tru rinks -- largest number of rinks of any club in the Southern US. Celebrated 100th anniversary in 2024.",
    status: "active",
    has_online_presence: true,
    facebook_url: "https://www.facebook.com/p/Clearwater-Lawn-Bowling-Club-100065712870434/",
    tags: ["historic", "year-round", "beginner-friendly", "large-facility"],
  },
  {
    name: "Delray Beach Lawn Bowling Club",
    city: "Delray Beach",
    state: "Florida",
    state_code: "FL",
    region: "south",
    address: "Veterans Park, Atlantic Ave, Delray Beach, FL",
    phone: "(561) 719-6614",
    greens: 1,
    rinks: 6,
    surface_type: "synthetic",
    division: "southeast",
    activities: ["Social Bowls", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1962,
    description: "Har-Tru surface. Welcomes local, state, national, and international guests.",
    status: "active",
    has_online_presence: false,
    tags: ["year-round", "beginner-friendly"],
  },
  {
    name: "Kings Point West Lawn Bowling Club",
    city: "Sun City Center",
    state: "Florida",
    state_code: "FL",
    region: "south",
    address: "2526 Lancaster Drive, Sun City Center, FL 33573",
    website: "https://sites.google.com/view/kingspointwestlawnbowlingclub/",
    greens: 1,
    surface_type: "unknown",
    division: "southeast",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    description: "Within Kings Point community (part of Sun City Center). Ages 55-90.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community", "year-round"],
  },
  {
    name: "Lakeland Lawn Bowling Club",
    city: "Lakeland",
    state: "Florida",
    state_code: "FL",
    region: "south",
    address: "Lake Parker Park, Gate 4, 820 E. Robson Street, Lakeland, FL 33805",
    greens: 1,
    rinks: 8,
    surface_type: "synthetic",
    division: "southeast",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1923,
    description: "One of the oldest clubs in Florida (est. 1923). Pro carpet surface described as 'very fast'.",
    status: "active",
    has_online_presence: true,
    facebook_url: "https://www.facebook.com/people/Lakeland-Lawn-Bowling-Club/100054508418442/",
    tags: ["historic", "year-round"],
  },
  {
    name: "Maple Leaf Lawn Bowling Club",
    city: "Port Charlotte",
    state: "Florida",
    state_code: "FL",
    region: "south",
    address: "2100 Kings Highway, Port Charlotte, FL 33980",
    website: "https://www.lawnbowlingml.com/",
    phone: "(941) 627-6917",
    member_count: 100,
    greens: 1,
    rinks: 8,
    surface_type: "unknown",
    division: "southeast",
    activities: ["Social Bowls", "Tournaments"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1987,
    description: "Self-described as 'Home of International Lawn Bowling in SW Florida'. Members from USA, Canada, and UK.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["55+", "retirement-community", "seasonal", "international"],
  },
  {
    name: "Mount Dora Lawn Bowling Club",
    city: "Mount Dora",
    state: "Florida",
    state_code: "FL",
    region: "south",
    address: "125 N Edgerton Court, Mount Dora, FL 32757",
    website: "https://www.mountdoralbc.com/",
    phone: "(352) 383-2294",
    email: "secretary@mountdoralbc.com",
    member_count: 240,
    greens: 1,
    rinks: 14,
    surface_type: "synthetic",
    division: "southeast",
    activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons", "Open Days"],
    facilities: ["Clubhouse", "Parking", "Restrooms"],
    description: "One of the largest Bowls USA-affiliated clubs (240+ members). 14 Har-Tru rinks. Night bowling under lights.",
    status: "active",
    has_online_presence: true,
    facebook_url: "https://www.facebook.com/MTDoraLawnBowling/",
    tags: ["largest-membership", "year-round", "night-bowling", "beginner-friendly"],
  },
  {
    name: "Sarasota Lawn Bowling Club",
    city: "Sarasota",
    state: "Florida",
    state_code: "FL",
    region: "south",
    address: "951 Circus Boulevard, Sarasota, FL 34232",
    website: "https://www.sarasotalawnbowlingclub.com/",
    email: "sarasotalawnbowling@gmail.com",
    greens: 1,
    surface_type: "unknown",
    division: "southeast",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    description: "Also offers croquet. Hosts certified coach training programs. Tiered membership system.",
    status: "active",
    has_online_presence: true,
    tags: ["year-round", "beginner-friendly"],
  },
  {
    name: "St. Petersburg Lawn Bowling Club",
    city: "St. Petersburg",
    state: "Florida",
    state_code: "FL",
    region: "south",
    address: "536 4th Avenue N, St. Petersburg, FL 33701",
    phone: "(727) 347-2770",
    email: "stpetelawnbowling@gmail.com",
    greens: 2,
    rinks: 13,
    surface_type: "unknown",
    division: "southeast",
    activities: ["Social Bowls", "Tournaments", "Open Days"],
    facilities: ["Clubhouse", "Parking", "Restrooms"],
    founded: 1916,
    description: "Oldest formally organized lawn bowling club in Florida (1916). 10th oldest in the US. Clubhouse on the National Register of Historic Places.",
    status: "active",
    has_online_presence: true,
    facebook_url: "https://www.facebook.com/stpetelawnbowling/",
    tags: ["historic", "national-register", "year-round"],
  },
  {
    name: "Sun City Center Lawn Bowling Club",
    city: "Sun City Center",
    state: "Florida",
    state_code: "FL",
    region: "south",
    address: "1009 N. Pebble Beach Boulevard, Sun City Center, FL 33573",
    website: "https://www.suncitycenterlbc.com/",
    phone: "(813) 938-3176",
    email: "sccinfo@suncitycenterlbc.com",
    greens: 3,
    surface_type: "unknown",
    division: "southeast",
    activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking", "Restrooms"],
    founded: 1962,
    description: "Hosted US National Championships (2023). Evening bowling under lights. Multiple sub-clubs.",
    status: "active",
    has_online_presence: true,
    facebook_url: "https://www.facebook.com/groups/2089445384418998/",
    tags: ["55+", "retirement-community", "year-round", "night-bowling", "championship-venue"],
  },
  {
    name: "Sun-n-Fun Lawn Bowling Club",
    city: "Sarasota",
    state: "Florida",
    state_code: "FL",
    region: "south",
    address: "7125 Fruitville Road, Sarasota, FL 34240",
    phone: "(941) 371-2505",
    greens: 1,
    surface_type: "unknown",
    division: "southeast",
    activities: ["Social Bowls", "League/Pennant", "Coaching/Lessons"],
    facilities: ["Parking"],
    description: "Located within Sun Outdoors Sarasota (formerly Sun-n-Fun RV Resort).",
    status: "seasonal",
    has_online_presence: false,
    tags: ["rv-resort", "seasonal"],
  },
  {
    name: "The Villages Lawn Bowls Club",
    city: "The Villages",
    state: "Florida",
    state_code: "FL",
    region: "south",
    address: "1228 Rio Grande Ave., The Villages, FL 32162",
    website: "http://www.thevillageslbc.org/",
    greens: 3,
    rinks: 7,
    surface_type: "natural_grass",
    division: "southeast",
    activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 2014,
    description: "Relatively new club (2014) in America's largest retirement community (130,000+ residents). 3 separate greens across different locations.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community", "year-round", "growing"],
  },
  {
    name: "World Parkway Lawn Bowling Club",
    city: "Clearwater",
    state: "Florida",
    state_code: "FL",
    region: "south",
    address: "On Top of the World Community, Clearwater, FL",
    phone: "(727) 725-9683",
    greens: 1,
    surface_type: "unknown",
    division: "southeast",
    activities: ["Social Bowls"],
    facilities: ["Parking"],
    description: "On Top of the World (OTOW) community. Club within a club structure. Primarily social/recreational.",
    status: "seasonal",
    has_online_presence: false,
    tags: ["55+", "retirement-community", "seasonal"],
  },

  // === NORTH CAROLINA (2 clubs) ===
  {
    name: "Asheville Lawn Bowling Club",
    city: "Asheville",
    state: "North Carolina",
    state_code: "NC",
    region: "south",
    address: "220 Amboy Road, Carrier Park, Asheville, NC 28806",
    website: "https://www.ashevillelawnbowls.com/",
    greens: 1,
    surface_type: "synthetic",
    division: "southeast",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Parking"],
    description: "Claims 'premier artificial green in the USA'. Thursday bowling + brewery pub crawl. Non-retirement community club.",
    status: "active",
    has_online_presence: true,
    tags: ["year-round", "younger-demographic", "brewery"],
  },
  {
    name: "Pinehurst Lawn Bowls Club",
    city: "Pinehurst",
    state: "North Carolina",
    state_code: "NC",
    region: "south",
    address: "80 Carolina Vista Drive, Pinehurst, NC 28374",
    website: "https://www.pinehurst.com/activities/lawn-sports/",
    phone: "(860) 857-3334",
    email: "bowlingatpinehurst@gmail.com",
    greens: 2,
    surface_type: "natural_grass",
    division: "southeast",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1920,
    description: "Part of world-famous Pinehurst Resort. Has hosted US Championships and North American Challenge.",
    status: "active",
    has_online_presence: true,
    tags: ["resort", "year-round", "championship-venue"],
  },

  // === ARKANSAS (1 club) ===
  {
    name: "Village Green Bowls Club",
    city: "Hot Springs Village",
    state: "Arkansas",
    state_code: "AR",
    region: "south",
    address: "200 DeSoto Park Lane, Hot Springs Village, AR 71909",
    website: "https://www.village-green-bowls-club.com/",
    phone: "(361) 813-0260",
    email: "villagegreenbowlsclub@gmail.com",
    greens: 1,
    surface_type: "natural_grass",
    division: "none",
    activities: ["Social Bowls", "Tournaments", "League/Pennant"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1978,
    description: "Only lawn bowling club in Arkansas. Robust tournament schedule with themed events.",
    status: "active",
    has_online_presence: true,
    tags: ["55+", "retirement-community", "year-round"],
  },

  // === TENNESSEE (1 club) ===
  {
    name: "Fogg Street Lawn Club",
    city: "Nashville",
    state: "Tennessee",
    state_code: "TN",
    region: "south",
    address: "648 Fogg Street, Nashville, TN",
    website: "https://www.foggstreet.com/",
    phone: "(615) 678-6200",
    email: "info@foggstreet.com",
    greens: 1,
    rinks: 8,
    surface_type: "natural_grass",
    division: "none",
    activities: ["Social Bowls", "Corporate Events", "Barefoot Bowls"],
    facilities: ["Bar/Lounge", "Restrooms", "Parking"],
    founded: 2024,
    description: "Nashville's first rooftop British lawn bowling experience. Commercial bar/restaurant with complimentary bowling. Winter conversion to Bavarian Ice Stock curling.",
    status: "active",
    has_online_presence: true,
    tags: ["commercial-venue", "rooftop", "bar", "year-round", "younger-demographic"],
  },

  // =====================================================================
  // MIDWEST REGION — 9 clubs
  // =====================================================================

  // === ILLINOIS (1 club) ===
  {
    name: "Lakeside Lawn Bowling Club",
    city: "Chicago",
    state: "Illinois",
    state_code: "IL",
    region: "midwest",
    address: "Jackson Park, 5800 South Lake Shore Drive, Chicago, IL",
    website: "https://www.lawnbowlingchicago.com/",
    phone: "(773) 610-8569",
    email: "info@lawnbowlingchicago.com",
    greens: 2,
    surface_type: "natural_grass",
    division: "central",
    activities: ["Social Bowls", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1927,
    description: "Located in historic Jackson Park (1893 World's Columbian Exposition site), adjacent to Museum of Science and Industry. Afternoon tea at 3 PM.",
    status: "unverified",
    has_online_presence: true,
    tags: ["historic", "seasonal", "public-park"],
  },

  // === INDIANA (1 club) ===
  {
    name: "Fort Wayne Lawn Bowls",
    city: "Fort Wayne",
    state: "Indiana",
    state_code: "IN",
    region: "midwest",
    address: "3837 N. Wells Street, Fort Wayne, IN 46808",
    website: "https://fortwaynelawnbowls.com/",
    greens: 1,
    surface_type: "natural_grass",
    division: "central",
    activities: ["Social Bowls", "League/Pennant", "Corporate Events", "Coaching/Lessons"],
    facilities: ["Clubhouse", "Parking"],
    founded: 2025,
    description: "First lawn bowling facility in Indiana. Innovative dual-sport model (curling + lawn bowls). Strong accessibility mission. Expected to open spring 2026.",
    status: "unverified",
    has_online_presence: true,
    tags: ["new-club", "dual-sport", "accessible"],
  },

  // === MINNESOTA (4 clubs) ===
  {
    name: "Brit's Pub Lawn Bowling",
    city: "Minneapolis",
    state: "Minnesota",
    state_code: "MN",
    region: "midwest",
    address: "1110 Nicollet Mall, Minneapolis, MN 55403",
    website: "https://britspub.com/minneapolis-brit-s-pub-lawn-bowling",
    phone: "(612) 332-3908",
    email: "manager@britspub.com",
    greens: 1,
    rinks: 4,
    surface_type: "natural_grass",
    division: "none",
    activities: ["Social Bowls", "League/Pennant", "Corporate Events", "Barefoot Bowls"],
    facilities: ["Bar/Lounge", "Restrooms"],
    founded: 1998,
    description: "Iconic rooftop lawn bowling green above a British pub. 10-year league waitlist. Most unique venue in the US.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["rooftop", "bar", "commercial-venue", "unique-venue", "long-waitlist", "seasonal"],
  },
  {
    name: "Brookview Golf and Lawn Bowling",
    city: "Golden Valley",
    state: "Minnesota",
    state_code: "MN",
    region: "midwest",
    address: "200 Brookview Parkway, Golden Valley, MN 55426",
    website: "https://www.brookviewgolf.com/lawn-bowling",
    phone: "(763) 512-2300",
    greens: 1,
    rinks: 8,
    surface_type: "natural_grass",
    division: "none",
    activities: ["Social Bowls", "Corporate Events"],
    facilities: ["Clubhouse", "Parking"],
    description: "Largest lawn bowling green in Minnesota. Municipal rental facility. Fire pit and ambient lighting.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["municipal", "rental-facility", "seasonal"],
  },
  {
    name: "Centennial Lakes Park Lawn Bowling",
    city: "Edina",
    state: "Minnesota",
    state_code: "MN",
    region: "midwest",
    address: "7499 France Avenue South, Edina, MN 55435",
    website: "https://www.edinamn.gov/2145/Activities-Events",
    phone: "(952) 833-9580",
    email: "centenniallakes@EdinaMN.gov",
    surface_type: "natural_grass",
    division: "central",
    activities: ["Social Bowls", "League/Pennant", "Tournaments"],
    facilities: ["Clubhouse", "Parking"],
    description: "Championship-caliber bentgrass greens described as 'some of the finest in the Midwest'. $20/hour per rink.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["municipal", "rental-facility", "seasonal", "championship-green"],
  },
  {
    name: "Madden's on Gull Lake Lawn Bowling",
    city: "Brainerd",
    state: "Minnesota",
    state_code: "MN",
    region: "midwest",
    address: "11266 Pine Beach Peninsula, Brainerd, MN 56401",
    website: "https://www.maddens.com/recreation/",
    greens: 1,
    surface_type: "natural_grass",
    division: "none",
    activities: ["Social Bowls", "League/Pennant"],
    facilities: ["Clubhouse", "Parking", "Restrooms"],
    description: "Only resort-based lawn bowling venue in the Midwest. USCA-sanctioned croquet lawns on same quality surface.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["resort", "seasonal"],
  },

  // === OHIO (2 clubs) ===
  {
    name: "Cincinnati Lawn Bowling Club",
    city: "Cincinnati",
    state: "Ohio",
    state_code: "OH",
    region: "midwest",
    address: "3811 Newtown Road, Cincinnati, OH 45244",
    website: "https://www.cincinnatilawnbowlingclub.org/",
    phone: "(513) 378-6068",
    email: "info@lawnbowling.org",
    greens: 1,
    surface_type: "natural_grass",
    division: "central",
    activities: ["Social Bowls", "Tournaments", "Coaching/Lessons"],
    facilities: ["Parking"],
    founded: 1922,
    description: "Only lawn bowling venue within approximately 250 miles of Cincinnati. Green praised by international visitors. Trial membership option.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["historic", "seasonal", "beginner-friendly"],
  },
  {
    name: "Lorain Lakeview Park Lawn Bowling",
    city: "Lorain",
    state: "Ohio",
    state_code: "OH",
    region: "midwest",
    address: "1800 W. Erie Avenue, Lorain, OH 44052",
    website: "https://www.loraincountymetroparks.com/lakeview-park",
    phone: "(440) 245-1193",
    surface_type: "natural_grass",
    division: "central",
    activities: ["Social Bowls", "League/Pennant"],
    facilities: ["Parking"],
    description: "20-acre lakeside recreational park with lighthouse views.",
    status: "seasonal",
    has_online_presence: true,
    tags: ["public-park", "lake-view", "seasonal"],
  },

  // === WISCONSIN (1 club) ===
  {
    name: "Milwaukee Lake Park Lawn Bowls Club",
    city: "Milwaukee",
    state: "Wisconsin",
    state_code: "WI",
    region: "midwest",
    address: "3131 East Newberry Boulevard, Milwaukee, WI 53211",
    website: "https://milwaukeelawnbowls.com/",
    greens: 2,
    surface_type: "natural_grass",
    division: "central",
    activities: ["Social Bowls", "League/Pennant", "Tournaments", "Coaching/Lessons", "Open Days"],
    facilities: ["Clubhouse", "Parking"],
    founded: 1920,
    description: "Over 100 years of tradition in Frederick Law Olmsted-designed Lake Park. Bowls USA '100% member club'. Member portal app.",
    status: "seasonal",
    has_online_presence: true,
    facebook_url: "https://www.facebook.com/MKELawnBowling",
    tags: ["historic", "lake-view", "seasonal", "beginner-friendly"],
  },
];

async function seed() {
  console.log(`\nSeeding ${clubs.length} clubs...\n`);

  let inserted = 0;
  let errors = 0;

  // Count clubs by region
  const regionCounts: Record<string, number> = {};
  for (const club of clubs) {
    regionCounts[club.region] = (regionCounts[club.region] ?? 0) + 1;
  }
  console.log("Region breakdown:");
  for (const [region, count] of Object.entries(regionCounts)) {
    console.log(`  ${region}: ${count} clubs`);
  }
  console.log();

  for (const club of clubs) {
    const slug = slugify(club.name, club.city, club.state_code);

    const record = {
      slug,
      name: club.name,
      city: club.city,
      state: club.state,
      state_code: club.state_code,
      region: club.region,
      address: club.address ?? null,
      website: club.website ?? null,
      phone: club.phone ?? null,
      email: club.email ?? null,
      member_count: club.member_count ?? null,
      greens: club.greens ?? null,
      rinks: club.rinks ?? null,
      surface_type: club.surface_type ?? "unknown",
      division: club.division ?? null,
      activities: club.activities ?? [],
      facilities: club.facilities ?? [],
      founded: club.founded ?? null,
      description: club.description ?? null,
      status: club.status ?? "unverified",
      has_online_presence: club.has_online_presence ?? false,
      facebook_url: club.facebook_url ?? null,
      instagram_url: club.instagram_url ?? null,
      tags: club.tags ?? [],
    };

    const { error } = await supabase
      .from("clubs")
      .upsert(record, { onConflict: "slug" });

    if (error) {
      console.error(`  FAIL ${club.name}: ${error.message}`);
      errors++;
    } else {
      console.log(`  OK   ${club.name} (${club.city}, ${club.state_code})`);
      inserted++;
    }
  }

  console.log(`\nDone: ${inserted} inserted/updated, ${errors} errors`);
  console.log(`Total clubs in seed: ${clubs.length}`);
}

seed().catch(console.error);
