-- H-002: This file was a DUPLICATE of 20260311_pennant_season.sql.
-- Consolidated in PR for AI-2436. The authoritative pennant schema is in
-- 20260311_pennant_season.sql — this file is intentionally empty.
--
-- The original duplicate used CREATE TABLE IF NOT EXISTS + DROP POLICY IF EXISTS
-- so removing it has no effect on existing databases (the first migration already ran).
-- For fresh deployments, 20260311_pennant_season.sql is the single source of truth.
